{literal}
<script type="text/javascript">
//Comments submission
$(document).ready(function() {
		$("#comment_submit").click(function(){
				
			$.post("/contrib/save-comments", $("#comment_form").serialize(),
				function(data) {
					//alert(data);
					var obj = $.parseJSON(data);
					$("#comments_list").html(obj.comments);
					$("#comment_count").text(obj.count);
					$("#comment_count_1").html('<i class="icon-comment"></i> '+obj.count);
					$("#article_comments").val('');
				}
			);	
		});
		
		//refreshing comments
		
		var comment_type=$("#comment_type").val();
		var identifier=$("#identifier").val();
		 /* setInterval(function() {
			//$('#comments_list').load('/contrib/save-comments?comment_type='+comment_type+'&identifier='+identifier);
			$.getJSON('/contrib/save-comments?comment_type='+comment_type+'&identifier='+identifier,
				{
					format: "json"
				},
				function(data) {
					$("#comments_list").html(data.comments);
					$("#comment_count").text(data.count);
					$("#comment_count_1").html('<i class="icon-comment"></i> '+data.count);
					$("#article_comments").val('');
				});
		}, 60000); */ 
		
		//changing active status of a comment
		$("[id^=delete_comment_]").live('click', function() {
			
			var parentLi=$(this).parents("li:first").attr('id');
			var deleteButton=$(this).attr('id').split("_");
			var comment_id=deleteButton[2];
			deleteComments(comment_id,comment_type,identifier);
				
		});
	});	
/** ajax function to delete/inactive comment data**/
function deleteComments(comment_id,comment_type,identifier)
{
        var target_page = '/contrib/save-comments?comment_action=delete&comment_id='+comment_id+'&comment_type='+comment_type+'&identifier='+identifier;
		
		$.post(target_page, function(data){									
				
				var obj = $.parseJSON(data);
				$("#comments_list").html(obj.comments);
				$("#comment_count").text(obj.count);
				$("#comment_count_1").html('<i class="icon-comment"></i> '+obj.count);
				$("#article_comments").val('');							
			});
}
	
</script>
{/literal}
<div class="mod">
	 <h4 id="comment"><i class="icon-comment"></i> Commentaires</h4>
	 <ul class="media-list" id="comments_list">
	 {if $commentDetails |@count gt 0}
		 	{foreach from=$commentDetails item=comment}
				<li class="media" id="comment_{$comment.identifier}">
					{if $comment.delete eq 'yes'}
						<button  class="close" type="button" id="delete_comment_{$comment.identifier}">&times;</button>
					{/if}	
					<a class="pull-left imgframe" href="#" role="button" data-toggle="modal" data-target="#viewProfile-ajax">
						<img alt="Topito" class="media-object" width="60px" src="{$comment.profile_pic}">
					</a>
					<div class="media-body">
						<h4 class="media-heading">
							<a  role="button" data-toggle="modal" data-target="#viewProfile-ajax">{$comment.profile_name}</a></h4>
							{$comment.comments}
						<p class="muted">{$comment.time}</p>
					</div>
				</li>		
			{/foreach}	
		
	{/if}	
	</ul>
	<div class="row-fluid">
		<div class=" well">
			<form action="" method="POST" id="comment_form">
				<h4>Commenter / poser une question</h4>
				<fieldset>
					<textarea class="span12" placeholder="Ecrire un commentaire" name="article_comments" id="article_comments"></textarea>
					<button type="button" id="comment_submit" name="comment_submit" class="btn">Envoyer</button>
					<input type="hidden" name="comment_type" value="{$comment_type}" id="comment_type">
					<input type="hidden" name="identifier" value="{$identifier}" id="identifier">
				</fieldset>
			</form>
		</div>
	</div>
</div>