<!-- display result for the bl wl check -->
<div class="modal-header">
    <button type="button" class="close" id="reload" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>{if $blwloutput.blkeyword neq '' || $blblock neq 'no'}Blacklist Alert{else}Whitelist Alert{/if}</h3>
</div>
<div class="modal-body">
<div class="row-fluid">
	<div class="span12">
      {if $singlefile eq 'yes'}
         {if $blwloutput.blkeyword neq ''}
         <div class="span12 pull-center">
             <h4 class="clearfix">Nous avons trouv&eacute; des mot cl&eacute;s interdits dans vos fichiers</h4>
             <p>Conform&eacute;ment au brief, vous devez les supprimer et ressoumettre vos articles</p>
         </div>
         <table id="bllist" class="table table-bordered">
            <thead>
            <tr>
                <th>File Name</th>
                <th>Keywords</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{$blwloutput.filename}<br>{$documenttitle}</td>
                <td>{$blwloutput.blkeyword}</td>
                </td>
            </tr>
            </tbody>
         </table>
         <div class="form-group span6">
            <button type="button" class="btn btn-info pull-right" id="blackclose" name="blackclose" onclick="" >Close</button>
         </div>
         {/if}
         {if $blwloutput.wlkeyword neq ''}
         <div class="span12 pull-center">
            <h4 class="clearfix">Erreur !  Mot cl&eacute; principal manquant ou modifi&eacute;</h4>
            <p>Conform&eacute;ment au brief, vous devez les inserer le mot cl&eacute; principal dans chaque paragraphe de chaque article.</p>
            <p>Si vous avez modefi&eacute; <b>tous les mot cl&eacute;s</b> ci-dessous pour corriger une faute grammaticale, merci de nous l'indiquer</p>
         </div>
         <table id="wllist" class="table table-bordered">
            <thead>
            <tr>
                <th>File Name</th>
                <th>Keywords Missed</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{$blwloutput.filename}</td>
                <td>{$blwloutput.wlkeyword}
                    <input type="text" id="proposewl" class="propose" name="proposewl" placeholder="Entrer le mot cl&eacute; corrig&eacute;" />
                </td>
            </tr>
            </tbody>
         </table>
         <div class="form-group span12">
            <div class="pull-center">
                <button type="button" class="btn btn-info" id="blackclose" name="blackclose" onclick="" >Close</button>
                <button type="button" class="btn btn-success "  id="addnewkeywordsingle" name="addnewkeywordsingle"   >Valider</button>
            </div>
         </div>
         {/if}
            <input type="hidden" id="articlepath" name="articlepath" value="{$articlepath}" />
            <input type="hidden" id="articlename" name="articlename" value="{$articleName}" />
            <input type="hidden" id="filename" name="filename" value="{$blwloutput.filename}" />
            <input type="hidden" id="participationId" name="participationId" value="{$participationId}" />
      {else}
        <form method="POST"  id="newwlkeywords" action="/contrib/sendarticlewithwlnewkeyword/">
          {if $blblock neq 'no'}
             <div class="pull-center">
                <h4 class="clearfix">Nous avons trouv&eacute; des mot cl&eacute;s interdits dans vos fichiers</h4>
                <p>Conform&eacute;ment au brief, vous devez les supprimer et ressoumettre vos articles</p>
             </div>
             <table id="bllist" class="table table-bordered">
                <thead>
                <tr>
                    <th>File Name</th>
                    <th>Keywords</th>
                </tr>
                </thead>
                <tbody>
                {foreach from=$output item=blword}
                    {if $blword.blkeyword}
                    <tr>
                        <td>{$blword.filename}</td>
                        <td>{$blword.blkeyword}</td>
                    </tr>
                    {/if}
                {/foreach}
                </tbody>
             </table>
             <div class="form-group span6">
                <button type="button" class="btn btn-info pull-right" id="blackclose" name="blackclose"  >Close</button>
             </div>
          {/if}
          {if $blblock eq 'no' && $errormessage eq ''}
          <div class="pull-center">
            <h4 class="clearfix">Erreur !  Mot cl&eacute; principal manquant ou modifié</h4>
            <p>Conform&eacute;ment au brief, vous devez les inserer le mot cl&eacute; principal dans chaque paragraphe de chaque article.</p>
            <p>Si vous avez modefi&eacute; <b>tous les mot cl&eacute;s</b> ci-dessous pour corriger une faute grammaticale, merci de nous l'indiquer</p>
          </div>
          <table id="wllist" class="table table-bordered">
            <thead>
            <tr>
                <th>File Name</th>
                <th>Keywords Missed</th>
            </tr>
            </thead>
            <tbody>
                {foreach from=$output item=wblword name=wblwords}
                    {assign var=index value=$smarty.foreach.wblwords.index+1}
                    {if $wblword.wlkeyword}
                    <tr>
                        <td>{$wblword.filename}</td>
                        <td>{$wblword.wlkeyword}
                            <input type="text" placeholder="Entrer le mot cl&eacute; corrig&eacute;" id="proposewl_{$index}" class="propose" name="proposewl[]" />
                            <input type="hidden" id="articlepath" name="articlepath[]" value="{$wblword.articlepath}" />
                            <input type="hidden" id="articlename" name="articlename[]" value="{$wblword.articleName}" />
                            <input type="hidden" id="filename" name="filename[]" value="{$wblword.filename}" />
                            <input type="hidden" id="zipfilename" name="zipfilename[]" value="{$wblword.zipfilename}" />
                            <input type="hidden" id="wordcount" name="wordcount[]" value="{$wblword.wordcount}" />
                            <input type="hidden" id="participationId" name="participationId[]" value="{$wblword.participationId}" /></td>
                        </td>
                    </tr>
                    {/if}
                {/foreach}
            </tbody>
          </table>
          <div class="form-group span12">
            <div class="pull-center">
                <button type="button" class="btn btn-info" id="blackclose" name="blackclose" onclick="" >Close</button>
                <button type="button" class="btn btn-success" id="addnewkeyword" name="addnewkeyword"   >Valider</button>
            </div>
          </div>
          {/if}
        </form>
      {/if}
	</div>
</div>
</div>
{literal}
<script>

    $('#reload').click(function() {
        location.reload();
    });
    $('#blackclose').click(function() {
        location.reload();
    });
    $('#reuploadoption1').click(function() {
        bootbox.confirm("Are you sure with this action",function(e){
            if (e)
            {
                location.reload();
            }
            else
            {
                return false;
            }
        });
    });
    $('#reuploadoption2').click(function() {
        $('.propose').show();
        $('#addnewkeyword').show();
        $('#addnewkeywordsingle').show();
    });
    $('#addnewkeyword').click(function() {
        var arr = [];
        var chks = document.getElementsByName('proposewl[]');//here rr[] is the name of the textbox
        for (var i = 0; i < chks.length; i++)
        {
            if (chks[i].value=="")
            {
                bootbox.alert("Please enter new keywords");
                chks[i].focus();
                return false;
            }else
                arr.push(chks[i].value);
        }
        var target_page = "/Contrib/sendarticlewithwlnewkeyword?nkword="+arr+"&data="+$("#newwlkeywords").serialize();
        $.post(target_page, function(data){   //alert(data);
            var obj = $.parseJSON(data);
            if(obj.status=="success"){
                location.reload();
            }else if(obj.status=="wlnwkwmissing"){
                bootbox.alert("The proposed keyword is not present in your document");
            }

        });
    });
    $('#addnewkeywordsingle').click(function() {
        var newkeyword = $('#proposewl').val();
         var articlepath = $('#articlepath').val();
         var articleName = $('#articlename').val();
         var participationId = $('#participationId').val();
         var filename = $('#filename').val();
        if($('#proposewl').val() == ''){
            bootbox.alert("Please enter the new white list keyword");
        }else{
            var target_page = "/Contrib/sendarticlewithwlnewkeyword?newkeyword="+newkeyword+"&articlepath="+articlepath
             +"&articleName="+articleName+"&filename="+filename+"&participation_id="+participationId+"&single=yes";
            $.post(target_page, function(data){   //alert(data);
                var obj = $.parseJSON(data);
                //location.reload();
                if(obj.status=="success"){
                    location.reload();
                }else if(obj.status=="wlnwkwmissing"){
                   bootbox.alert("The proposed keyword is not present in your document");
                }

            });
        }
    });


</script>    
{/literal}