{literal}
<script type="text/javascript">
$('body').removeClass('homepage');
$('body').addClass('mission');
</script>
{/literal}

<div class="container">
<br>
{if $missionDetails | @count gt 0}
	{foreach from=$missionDetails item=article name=details}
	<ul class="breadcrumb">
		<li><a href="/contrib/home">Accueil</a> <span class="divider">/</span></li>
		<li><a href="/contrib/ongoing">Mes participations</a> <span class="divider">/</span></li>
		<li class="active">{$article.title}</li>
	</ul> 
	{if $article.status eq 'disapproved'}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<a class="btn-link disabled btn-mini pull-right" href="#">Je ne pourrai pas tenir ces d&eacute;lais.</a>
		<i class="icon-exclamation-sign"></i> Vos articles devant &ecirc;tre repris, vous obtenez un nouveau d&eacute;lai de livraison de {$article.article_resubmit_time_text} pour les mettre &agrave; jour. 
	</div>
	{/if}
	
	<!-- start, Summary -->
	<section id="summary">
		<div class="row-fluid">
			<div class="span8">
				{if $article.ao_type eq 'premium'}
					{if $article.missiontest eq 'yes'}
						<span class="label label-mission-test">Mission Test</span>
					{else}
						<span class="label label-premium">Mission Premium</span>&nbsp;&nbsp;<img src="{$article.bo_user_pic}"></img>&nbsp;&nbsp; g&eacute;r&eacute;e par <b>{$article.bo_user}</b>. <a href="/contrib/compose-mail?senduser={$article.created_user}">contactez-le !</a>
					{/if}
					<h1>{$article.title}</h1>	
				{else}	
					{if $article.missiontest eq 'yes'}
						<span class="label label-mission-test">Mission Test</span>
					{else}
						<span class="label label-quote">Mission Libert&eacute;</span>
					{/if}	
					<h1>{$article.title}</h1>	
				{/if}	
			</div>
			<div class="span3 stat">
				<p>Date de livraison</p>
				<!-- add classname "less24" if time is < 24h  -->
				<!-- p class="num-large less24">Livrée</p-->
				{if $article.status eq 'bid' OR $article.status eq 'disapproved' OR $article.status eq 'disapprove_client' }
					<p class="num-large less24">
						<span id="dtime_{$article.article_id}_{$article.article_submit_expires}">
							<span id="dtext_{$article.article_id}_{$article.article_submit_expires}">{$article.article_submit_expires}</span>
						</span>
					</p>
				{else}
					<p class="num-large less24" style="font-size:18px">{$article.status_trans}</p>
				{/if}	
			</div>
			{*<div class="span2 stat">
				<p>Tarif</p>
				<p class="num-large">{$article.price_user|zero_cut:2} &euro;</p>
			</div>*}
			<div class="span1 stat">
				<div class="icon-comment-large new"><a href="#comment" class="scroll" id="comment_count">{$commentDetails|@count}</a></div>
			<!--  to active if new comment, add classname "new" -->
			<!--div class="icon-comment-large new"><a href="#comment">3</a></div-->


			</div>
		</div>
	</section>
	<!-- end, summary --> 
 
	<div class="row-fluid"> 
		<div class="span9">
			<section id="file-management">				
				<div class="row-fluid file-management-cont">    
					<i class="outbox"></i><h4 class="clearfix">Votre Edit-Box</h4>	 
					<p>Ajoutez vos fichiers contenant les articles que vous avez r&eacute;alis&eacute;s pour cette mission</p>				
					
					<table style="margin-left: 4%" class="table mod span11 offset1">
						<thead>
						<tr>
							<th class="span6">Fichier</th>
							<th class="span4" style="text-align:center">Date</th>
							<th class="span2">Poids</th>
						</tr>
						</thead>
						<tbody>
							{if $AllVersionArticles | @count gt 0}
								{foreach item=versionarticle from=$AllVersionArticles name=articledetails}
									<tr><td class="span8"><i class="icon-download"></i> <a href="/contrib/download-version-article?processid={$versionarticle.id}">{$versionarticle.article_name}</a></td>
									<td class="span4 muted" style="text-align:center">{$versionarticle.article_sent_at|date_format:"%d/%m/%Y %H:%M"}</td>
									<td class="span2 muted">{$versionarticle.file_size}</td></tr>
								{/foreach}
							
							{else}
								<tr><td colspan="4"></td></tr>
							{/if}	
						</tbody>
					</table>
					{if $article.status eq 'bid' OR $article.status eq 'disapproved' OR $article.status eq 'disapprove_client'}
					<div class="pull-center">		
						<p>
							<span class="btn btn-primary fileinput-button">
								<i class="icon-plus icon-white"></i>
								<span id="send-status">Ajouter un fichier...</span>
								<!--<input type="file" id="send-article" name="article">-->
							</span>
							<input type="hidden" name="participation_id" value="{$participation_id}" id="send_participate_id">
						</p>	
					</div>
					<p>&mdash;</p>
					{/if}
					
					<!-- call to action set -->
					<div class="pull-center btn-group">
						{if $article.status eq 'bid' OR $article.status eq 'disapproved' OR $article.status eq 'disapprove_client' OR $article.status eq 'time_out'}
							<button href="/contrib/ask-more-time?ao_type={$article.ao_type}&article_id={$article.article_id}" role="button" data-toggle="modal" data-target="#moretime-ajax" class="btn" rel="tooltip" data-original-title="Demander un d&eacute;lai suppl&eacute;mentaire"><i class="icon-time"></i><sup>+</sup> Demander un d&eacute;lai suppl&eacute;mentaire</button>
						{/if}	
						<a data-original-title="Aide" rel="tooltip" class="btn" href="/contrib/compose-mail?senduser=111201092609847"><i class="icon-question-sign"></i> Aide</a>
					</div>
					
				</div>
			</section>
			<section id="a_o">
				<div class="mod">
					<div class="summary clearfix">
						<h4>D&eacute;tails du projet</h4>
						<ul class="unstyled">
							<li><strong>Appel &agrave; r&eacute;daction</strong> <span class="bullet">&#9679;</span></li>
							<li> Langue : <img class="flag flag-{$article.language}" src="/FO/images/shim.gif"> <span class="bullet">&#9679;</span></li>
							<li>Cat&eacute;gorie : {$article.category} <span class="bullet">&#9679;</span></li>
							<li>Nb. mots : {$article.num_min} - {$article.num_max} / article
							
							{if $article.spec_exists eq 'yes'}
								<li class="pull-right"><a href="/contrib/download-file?type=clientbrief&article_id={$article.article_id}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> T&eacute;l&eacute;charger le brief client</a></li>
							{/if}	
						</ul>
					</div>
				</div>
			</section>
			{include file="Contrib/article-comments.phtml"}
		</div>

		<div class="span3">
		<!--  right column  -->
			<aside>
				<div class="aside-bg">
					<div class="editor-price">
						<p class="quote-price">Royalties :<strong> {$article.price_user|zero_cut:2} &euro;</strong></p>
						{if $article.ao_type neq 'premium'}
							<ul class="unstyled stripe">
								<li>Commission Edit-place inclus : {$article.ep_commission}%</li>
								<li>  Prix total r&eacute;gl&eacute; par le client : {$article.final_price|zero_cut:2} &euro;</li>
							</ul>
						{/if}	
					</div> 
					<div id="selected-editor" class="aside-block">
						<div class="editor-container">
							<h4>Votre client</h4>
							<img src="{$article.client_pic}" title="{$article.company_name}">
							<p class="editor-name">{$article.company_name}</p>
							{if $article.ao_type eq 'premium'}
								<a href="/contrib/compose-mail?senduser=110923143523902" class="btn btn-small">Contactez-nous</a>
							{else}
								<p>Tel : {$article.phone_number}</p> 
								<!--<a href="/contrib/compose-mail?senduser={$article.article_id}" class="btn btn-small">Envoyer un message</a>-->
								<p>Email : {$article.email}</p> 
							{/if}	
						</div>
					</div>
					{if $article.ao_type neq 'premium'}
					<div class="aside-block" id="liberte-guide" style="margin-top: 40px">
						<h4>Guide du r&eacute;dacteur</h4>
						<div class="pull-center inc"><span class="label label-quote">mission liberte</span></div>
						<p><strong>Avant de d&eacute;marrer... </strong></p>
						<ul>
							<li>Contactez le client par email ou t&eacute;l&eacute;phone d&egrave;s que vous &ecirc;tes s&eacute;lectionn&eacute;(e).     </li>
							<li>Demandez une confirmation du brief, du timing de rendu et du nombre d&rsquo;articles.</li>
						</ul>
						<p><strong>Une fois les articles r&eacute;dig&eacute;s...</strong></p>
						<ul>
							<li>T&eacute;l&eacute;chargez les &eacute;l&eacute;ments sur la plateforme.</li>
							<li>N'envoyez jamais votre travail complet par email au client.</li>
						</ul>
						<hr>
						<p class="pull-center"><a href="/contrib/download-file?type=guide_mission_liberte" class="btn btn-small"><i class="icon-download"></i> T&eacute;l&eacute;charger le guide complet</a></p>
					</div>
					{/if}
					<div class="aside-block" id="garantee">
						<h4>Vos garanties</h4>
						<dl>
							<dt><span class="umbrella"></span>edit-place est votre m&eacute;diateur</dt>
							<dd>En cas de contestation (d&eacute;lai de livraison, reprise d&rsquo;articles, remboursement...)</dd>
							<dt><span class="locked"></span>Paiement s&eacute;curis&eacute;</dt>
							<dd>Notre solution de paiement en ligne vous garantit une transaction en toute tranquillit&eacute;</dd>
						</dl>
					</div>
				</div>
			</aside>  
		</div>
	</div>
{/foreach}
{/if}	
</div>
<link rel="stylesheet" type="text/css" href="{$livesite}/FO/css/common/bootstrap-wysihtml5.css"></link>
<script src="{$livesite}/FO/script/common/wysihtml5-0.3.0.min.js"></script>
<script src="{$livesite}/FO/script/common/bootstrap-wysihtml5.js"></script> 
<script src="{$livesite}/FO/script/common/locales/bootstrap-wysihtml5.fr-FR.js"></script>
{literal}
<script type="text/javascript">
var cur_date={/literal}{$smarty.now}{literal};
	var js_date=(new Date().getTime())/ 1000;
	var diff_date=Math.floor(js_date-cur_date);
	$("#menu_ongoing").addClass("active");
	startMissionTimer('dtime','dtext');
	
/**article uploading**/
$(function(){
		var btnUpload=$('.fileinput-button');
		var status=$('#send-status');
		var participation_id=$('#send_participate_id').val();
		new AjaxUpload(btnUpload, {
			action: 'sendarticle',
			name: 'send_article',
			data:{participation_id:participation_id},
			onSubmit: function(file, ext){
				 if (! (ext && /^(doc|docx|pdf|xls|xlsx|zip|rar)$/.test(ext))){ 
                    // extension is not allowed 
					status.html('seuls les fichiers doc,docx,xls,xlsx,pdf,zip,rar sont accept&eacute;s').css('color','#FF0000');
					return false;
					}

				 /*if (! (ext && /^(doc|docx|rtf)$/.test(ext))){ 
                    // extension is not allowed 
					status.html('Only doc,docx,rtf files are allowed').css('color','#FF0000');
					return false;
					}*/
				status.html('<img src="/FO/images/icon-generic.gif" /> Chargement..');
			},
			onComplete: function(file, response){
				//On completion clear the status
				status.html('<img src="/FO/images/icon-generic.gif" /> Chargement..');
				//alert(response);
				var patt=/not readable/g;
				var result=patt.test(response);
				
				if(result)
				{
					status.text('File is not readable').css('color','#FF0000');
				}
				else
				{
					var obj = $.parseJSON(response);
					//alert(obj.status);
					if(obj.status=="success"){							
						location.reload();					
					}				
					else{
						windows.location="/contrib/ongoing";
					}
				}	
			}
		});			
	});	
	
	
</script>
{/literal}

<div id="moretime-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
<h3 id="myModalLabel">Demande de d&eacute;lai suppl&eacute;mentaire</h3>
</div>
<div class="modal-body">

</div>

</div>