{php}

ini_set('default_charset', 'UTF-8');
mb_internal_encoding('UTF-8');
{/php}

{literal}

<script type="text/javascript">
$('body').removeClass('homepage');
$('body').addClass('mission');
</script>
<style type="text/css">
.btn-success_custom
{
	background-color: #5BB75B;    
    border-width: 0;
    color: #FFFFFF;
	font-weight:600
	background-image: linear-gradient(to bottom, #62C462, #51A351);
    background-repeat: repeat-x;
    border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
}
.btn-success_custom:hover, .btn-success_custom:active, .btn-success_custom.active, .btn-success_custom.disabled, .btn-success_custom[disabled] {
    background-color: #51A351;
    color: #FFFFFF;
}
.btn-success
{
margin-top: 0;
padding:5px 13px;
}
</style>
{/literal}

<div class="container">
<br>
{if $missionDetails | @count gt 0}
	{foreach from=$missionDetails item=article name=details}
	<ul class="breadcrumb">
		<li><a href="/contrib/home">Accueil</a> <span class="divider">/</span></li>
		<li><a href="/contrib/ongoing">Mes participations</a> <span class="divider">/</span></li>
		<li class="active">{$article.title}</li>
	</ul> 
	{if $article.status eq 'disapproved'}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<a class="btn-link disabled btn-mini pull-right" href="#">Je ne pourrai pas tenir ces d&eacute;lais.</a>
		<i class="icon-exclamation-sign"></i> Vos articles devant &ecirc;tre repris, vous obtenez un nouveau d&eacute;lai de livraison de {$article.article_resubmit_time_text} pour les mettre &agrave; jour. 
	</div>
	{/if}
	
	<!-- start, Summary -->
	<section id="summary">
		<div class="row-fluid">
			<div class="span8">
				{if $article.ao_type eq 'premium'}
					{if $article.missiontest eq 'yes'}
						<span data-placement="right" rel="tooltip" data-original-title="Garanteed long-term Mission" class="label label-test-mission"><i class="icon-star icon-white"></i>  Staffing</span>
					{else}
						<span class="label label-premium">Mission Premium</span>&nbsp;&nbsp;g&eacute;r&eacute;e par <b>{$article.bo_user}</b>. <a style="color:#fff;font-weight:bold;text-decoration:underline;" href="/contrib/compose-mail?senduser={$article.article_id}">Contactez-le !</a>
					{/if}
					<h1>{$article.title}</h1>
				{else}	
					{if $article.missiontest eq 'yes'}
						<span data-placement="right" rel="tooltip" data-original-title="Garanteed long-term Mission" class="label label-test-mission"><i class="icon-star icon-white"></i>  Staffing</span>
					{else}
						<span class="label label-quote">Mission Libert&eacute;</span>
					{/if}	
					<h1>{$article.title}</h1>	
				{/if}	
			</div>
			<div class="span3 stat">
				<p>Date de livraison</p>
				<!-- add classname "less24" if time is < 24h  -->
				<!-- p class="num-large less24">Livrée</p-->
				{if $article.status eq 'bid' OR $article.status eq 'disapproved' OR $article.status eq 'disapprove_client' }
					<p class="num-large less24">
						<span id="dtime_{$article.article_id}_{$article.article_submit_expires}">
							<span id="dtext_{$article.article_id}_{$article.article_submit_expires}">{$article.article_submit_expires}</span>
						</span>
					</p>
				{else}
					<p class="num-large less24" style="font-size:18px">{$article.status_trans}</p>
				{/if}	
			</div>
			{*<div class="span2 stat">
				<p>Tarif</p>
				<p class="num-large">{$article.price_user|zero_cut:2} &euro;</p>
			</div>*}
			<div class="span1 stat">
				<div class="icon-comment-large new"><a href="#comment" class="scroll" id="comment_count">{$commentDetails|@count}</a></div>
			<!--  to active if new comment, add classname "new" -->
			<!--div class="icon-comment-large new"><a href="#comment">3</a></div-->


			</div>
		</div>
	</section>
	<!-- end, summary --> 
 
	<div class="row-fluid"> 
		<div class="span9">
			<section id="a_o">
				<div class="mod">
					<div class="summary clearfix">
						<h4>D&eacute;tails du projet</h4>
						<ul class="unstyled">
							<li><strong>Appel &agrave; r&eacute;daction</strong> <span class="bullet">&#9679;</span></li>
							<li> Langue : <img class="flag flag-{$article.language}" src="/images/shim.gif"> <span class="bullet">&#9679;</span></li>
							<li>Cat&eacute;gorie : {$article.category} <span class="bullet">&#9679;</span></li>
							<li>Nb. mots : {$article.num_min} - {$article.num_max} / article
							{if $article.spec_exists eq 'yes'}
								<li class="pull-right"><a href="/contrib/download-file?type=clientbrief&article_id={$article.article_id}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> T&eacute;l&eacute;charger le brief client</a></li>
							{/if}	
						</ul>
					</div>
				</div>
			</section>
			<section id="file-management">				
				<div class="row-fluid file-management-cont">    
					<i class="outbox"></i><h4 class="clearfix">Votre Edit-Box</h4>	 
					<p>Ajoutez vos fichiers contenant les articles que vous avez r&eacute;alis&eacute;s pour cette mission</p>				
					{if $article.status eq 'bid' OR $article.status eq 'disapproved' OR $article.status eq 'disapprove_client'}
					{if $clientId eq '120218054512919v'}
                    <form action="/contrib/sendarticle" method="post" enctype="multipart/form-data">
                    <div class="pull-center">
							<p>
                                <!--<span class="btn btn-primary fileinput-button">
                                    <i class="icon-plus icon-white"></i>
                                    <span id="send-status">Ajouter un fichier...</span>-->
									<input type="file" id="send-article" name="article" class="span3">
								<!--</span>-->
								<button type="submit" class="btn btn-success" name="submit_article" id="submit_article" style="display:''">Envoyer</button>
								<input type="hidden" name="participation_id" value="{$participation_id}" id="send_participate_id">
                                <input type="hidden" name="clientId" value="{$clientId}" id="clientId">
							</p>	
						</div>
                    </form>
                    {else}
                        <div class="pull-center">
                            <p>
                                <span class="btn btn-primary fileinput-button">
                                    <i class="icon-plus icon-white"></i>
                                    <span id="send-status">Ajouter un fichier...</span>
                                <!--<input type="file" id="send-article" name="article">-->
                                </span>
                                <button type="button" class="btn btn-success" name="submit_article" id="submit_article" style="display:''">Envoyer</button>
                                <input type="hidden" name="participation_id" value="{$participation_id}" id="send_participate_id">
                                <input type="hidden" name="clientId" value="{$clientId}" id="clientId">
                            </p>
                        </div>
                    {/if}
                    {/if}
					
					<table style="margin-left: 4%" class="table mod span11 offset1">
						<thead>
						<tr>
							<th class="span6">Fichier</th>
							<th class="span4" style="text-align:center">Date</th>
							<th class="span2">Poids</th>
						</tr>
						</thead>
						<tbody>
							{if $AllVersionArticles | @count gt 0}
								{foreach item=versionarticle from=$AllVersionArticles name=articledetails}
									<tr><td class="span8"><i class="icon-download"></i> <a href="/contrib/download-version-article?processid={$versionarticle.id}">{$versionarticle.article_name}</a></td>
									<td class="span4 muted" style="text-align:center">{$versionarticle.article_sent_at|date_format:"%d/%m/%Y %H:%M"}</td>
									<td class="span2 muted">{$versionarticle.file_size}</td></tr>
								{/foreach}
							
							{else}
								<tr><td colspan="4"></td></tr>
							{/if}	
						</tbody>
					</table>

					
					<!-- call to action set -->
					<div class="pull-center btn-group">
						{if $article.status eq 'bid' OR $article.status eq 'disapproved' OR $article.status eq 'disapprove_client' OR $article.status eq 'time_out'}
							<button href="/contrib/ask-more-time?ao_type={$article.ao_type}&article_id={$article.article_id}" role="button" data-toggle="modal" data-target="#moretime-ajax" class="btn" rel="tooltip" data-original-title="Demander un d&eacute;lai suppl&eacute;mentaire"><i class="icon-time"></i><sup>+</sup> Demander un d&eacute;lai suppl&eacute;mentaire</button>
						{/if}	
						<a data-original-title="Aide" rel="tooltip" class="btn" href="/contrib/compose-mail?senduser=111201092609847"><i class="icon-question-sign"></i> Aide</a>
					</div>
					
							
				</div>
			</section>
			{include file="Contrib/article-comments.phtml"}
		</div>

		<div class="span3">
		<!--  right column  -->
			<aside>
				<div class="aside-bg">
					<div class="editor-price">
						<p class="quote-price">Royalties :<strong>{if $article.free_article eq 'yes'}&nbsp;GRATUIT{else}&nbsp; {$article.price_user|zero_cut:2} &euro;{/if}</strong></p>
						{if $article.ao_type neq 'premium'}
							<ul class="unstyled stripe">
								<li>Commission Edit-place inclus : {$article.ep_commission}%</li>
								<li>  Prix total r&eacute;gl&eacute; par le client : {$article.final_price|zero_cut:2} &euro;</li>
							</ul>
						{/if}	
					</div> 
					<div id="selected-editor" class="aside-block">
						<div class="editor-container">
							<h4>Votre client</h4>
							<img src="{$article.client_pic}" title="{$article.company_name}">
							<p class="editor-name">{$article.company_name}</p>
							{if $article.ao_type eq 'premium'}
								<a href="/contrib/compose-mail?senduser=110923143523902" class="btn btn-small">Contactez-nous</a>
							{else}
								<p>Tel : {$article.phone_number}</p> 
								<!--<a href="/contrib/compose-mail?senduser={$article.article_id}" class="btn btn-small">Envoyer un message</a>-->
								<p>Email : {$article.email}</p> 
							{/if}	
						</div>
					</div>
					{if $article.ao_type neq 'premium'}
					<div class="aside-block" id="liberte-guide" style="margin-top: 40px">
						<h4>Guide du r&eacute;dacteur</h4>
						<div class="pull-center inc"><span class="label label-quote">mission liberte</span></div>
						<p><strong>Avant de d&eacute;marrer... </strong></p>
						<ul>
							<li>Contactez le client par email ou t&eacute;l&eacute;phone d&egrave;s que vous &ecirc;tes s&eacute;lectionn&eacute;(e).     </li>
							<li>Demandez une confirmation du brief, du timing de rendu et du nombre d&rsquo;articles.</li>
						</ul>
						<p><strong>Une fois les articles r&eacute;dig&eacute;s...</strong></p>
						<ul>
							<li>T&eacute;l&eacute;chargez les &eacute;l&eacute;ments sur la plateforme.</li>
							<li>N'envoyez jamais votre travail complet par email au client.</li>
						</ul>
						<hr>
						<p class="pull-center"><a href="/contrib/download-file?type=guide_mission_liberte" class="btn btn-small"><i class="icon-download"></i> T&eacute;l&eacute;charger le guide complet</a></p>
					</div>
					{/if}
					<div class="aside-block" id="garantee">
						<h4>Vos garanties</h4>
						<dl>
							<dt><span class="umbrella"></span>edit-place est votre m&eacute;diateur</dt>
							<dd>En cas de contestation (d&eacute;lai de livraison, reprise d&rsquo;articles, remboursement...)</dd>
							<dt><span class="locked"></span>Paiement s&eacute;curis&eacute;</dt>
							<dd>Notre solution de paiement en ligne vous garantit une transaction en toute tranquillit&eacute;</dd>
						</dl>
					</div>
				</div>
			</aside>  
		</div>
	</div>
{/foreach}
{/if}	
</div>
<link rel="stylesheet" type="text/css" href="{$livesite}/FO/css/common/bootstrap-wysihtml5.css"></link>
<script src="{$livesite}/FO/script/common/wysihtml5-0.3.0.min.js"></script>
<script src="{$livesite}/FO/script/common/bootstrap-wysihtml5.js"></script> 
<script src="{$livesite}/FO/script/common/locales/bootstrap-wysihtml5.fr-FR.js"></script>
{literal}
<script type="text/javascript">
var cur_date={/literal}{$smarty.now}{literal};
	var js_date=(new Date().getTime())/ 1000;
	var diff_date=Math.floor(js_date-cur_date);
	$("#menu_ongoing").addClass("active");
	startMissionTimer('dtime','dtext');
/**article uploading**/
$(function(){
		var btnUpload=$('.fileinput-button');
		var status=$('#send-status');
		var participation_id=$('#send_participate_id').val();
        var client_id=$('#clientId').val();
        var blwlcheck=$('#blwlcheck').val();
	var uploader=new AjaxUpload(btnUpload, {
			action: 'sendarticle',
			name: 'send_article',
			data:{participation_id:participation_id, clientId:client_id},
			autoSubmit: false,
            contentType: "application/x-www-form-urlencoded;charset=UTF8",

        onChange: function(file, ext){ //alert(ext);
                if($('#clientId').val() == '120218054512919')  //150128182032170- venere test id
                {
                if(ext == 'docx' || ext == 'zip' || ext == 'rar'){ //alert('hey');

                    $("#submit_article").show();
                }
                    else {
                        status.html('seuls les fichiers docx,zip,rar sont accept&eacute;s').css({
                            'color': '#fff',
                            "background": "none repeat scroll 0 0 #f47d31",
                            "border-radius": "10px",
                            "padding": "4px"
                        });
                    return false;
                }
                }else{
                    if (! (ext && /^(doc|docx|pdf|xls|xlsx|zip|rar)$/.test(ext))){
                    // extension is not allowed 
                        status.html('seuls les fichiers doc,docx,xls,xlsx,pdf,zip,rar sont accept&eacute;s').css({'color':'#fff',"background": "none repeat scroll 0 0 #f47d31","border-radius":"10px","padding": "4px"});
					return false;
				}
                    else
                    {
                        $("#submit_article").show();

                    }
                }
                status.html('<img src="/FO/images/icon-generic.gif" /> '+file);
			},
			onComplete: function(file, response){   //alert(response);
				//On completion clear the status
                status.html('<img src="/FO/images/icon-generic.gif" /> Chargement..');
				//alert(response);
				var patt=/not readable/g;
				var result=patt.test(response);

                if(result)
				{
                    status.text('Lecture de votre fichier impossible').css({'color':'#fff',"background": "none repeat scroll 0 0 #f47d31","border-radius":"10px","padding": "4px"});
				}
				else
				{
                    $("#loading").modal('hide');
                    //alert(response);
                    //console.log(response);
                   // window.my_json_res = response;
                    /*var obj = $.parseJSON(response);
                   // var obj = decodeURIComponent($.parseJSON(response));
                    if(obj.status=="blwlerror"){ alert('hey');
                        //bootbox.alert("Your file is not meeting the client's requirement "+res[0],function() {
                          //  location.reload();
                        //});
                        alert("hello");
                        $('#wlblresult .modal-body').html(decodeURIComponent(obj.result));
                        $("#wlblresult").modal('show');
                    }
                    else {
                        //status.text('File already sent for this article').css({'color':'#fff',"background": "none repeat scroll 0 0 #f47d31","border-radius":"10px","padding": "4px"});
                      //  location.reload();
                    }*/

					var obj = $.parseJSON(response); //alert(response);
					if(obj.status=="success"){
						location.reload();					
					}
					else if(obj.status=="file_sent"){
						//status.text('File already sent for this article').css({'color':'#fff',"background": "none repeat scroll 0 0 #f47d31","border-radius":"10px","padding": "4px"});	
						location.reload();						
					}
                    else if(obj.status=="blwlerror"){
                         $('#wlblresult').html(decodeURIComponent(obj.result));
                         $("#wlblresult").modal('show');
                    }
                    else if(obj.status=="blwlerrormessage"){
                        //status.html('your zip or rar file should only contain .doc files (not .docx)').css({'color':'#fff',"background": "none repeat scroll 0 0 #f47d31","border-radius":"10px","padding": "4px"});
                        $("#wlblalert").modal('show');
                        $("#wlblalert .modal-body").html("Votre archive zip/rar ne doit contenir que des fichiers .docx");
                        return false;
                    }
                    else if(obj.status=="docerrormessage"){
                        $("#wlblalert").modal('show');
                        if(obj.result == 'multi')
                            $("#wlblalert .modal-body").html("Votre archive zip/rar ne doit contenir que des fichiers .docx. Sauvegardez vos fichiers dans le format requis et les transf&eacute;rer de nouveau.");
                        else
                            $("#wlblalert .modal-body").html("Votre fichier n'a pas &eacute;t&eacute; sauvegard&eacute; au format .docx. Merci de sauvegarder votre fichier dans le format requis.");
                        //bootbox.alert("Your file(s) have not been saved in .doc. Please saved your file(s) with the good extension and reupload.");
                        //status.html('<img src="/images/icon-generic.gif" /> '+file);
                        return false;
                    }
                    else{
                       // location.reload();
						windows.location="/contrib/ongoing";
					}
				}	
			}
		});	

	$("#submit_article").click(function(e){
        if($('#clientId').val() == '120218054512919')  //150128182032170- venere test id
        {
            $("#loading").modal('show');
            $('html,body').animate({ scrollTop: 10 }, 'slow');
        }
		uploader.submit();

	});
		
});	
	
	
</script>
{/literal}
<div id = "confirmDiv"></div>
<div id="moretime-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
<h3 id="myModalLabel">Demande de d&eacute;lai suppl&eacute;mentaire</h3>
</div>
<div class="modal-body">

</div>

</div>
<!--///show loading time for file uploading ///-->
<div id="loading" class="modal hide fade" tabindex="-1" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 >Analyse du fichier en cours</h3>
    </div>
    <div class="modal-body">
        <h3>Transfert en cours...
            <img src="/FO/images/progressbar.gif"></h3>
    </div>

</div>

<!--///show loading time for file uploading ///-->
<div id="wlblresult" class="modal container hide fade" tabindex="-1" >


</div>

<div id="wlblalert" class="modal hide fade" tabindex="-1" >
    <div class="modal-header">
        <button type="button" id="close" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Alerte</h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="form-group pull-center">

    </div>
    <div class="span1" style="height:5px;"></div>
</div>
{literal}
<script>

    $('#reload').click(function() {
        location.reload();
    });
    $('#blackclose').click(function() {
        location.reload();
    });


</script>
{/literal}

