{literal}
<script type="text/javascript">
    var cur_date=0,js_date=0,diff_date=0;
    cur_date={/literal}{$smarty.now}{literal};
    js_date=(new Date().getTime())/ 1000;
    diff_date=Math.floor(js_date-cur_date);
    $("#menu_ongoing").addClass("active");
    startMissionTimer('dtime','dtext');

var mtype='{/literal}{$smarty.get.mission_type}{literal}';
var mid='{/literal}{$smarty.get.mission_identifier}{literal}';

if(mtype && mid )
{
	$.get('/contrib/article-details?req_from=ongoing&misson_type='+mtype+'&mission_identifier='+mid, function(data) {
		$("#viewOffer-ajax .modal-body").html(data);
		$("#viewOffer-ajax").modal('show');
	});
}
$(document).ready(function(){
    //call this funcion to load Recent Ao offers on the page using ajax//
    loadOngoingAjaxRecentAoOffers();
    //call tp load Published Articles//
    loadOngoingAjaxPublishedArticles();
    loadOngoingAjaxEncoursArticles();

    loadOngoingAjaxAwaitingArticles();
});
function loadOngoingAjaxRecentAoOffers(){
    console.log('initiated loadOngoingAjaxRecentAoOffers');
    $.ajax({
        type: 'POST',
        url: '/contrib/load-ongoing-ajax-recent-ao-offers',
        success: function (data) {
            $("#recent_AO_Offers").html(data);
        }
    });
}
function loadOngoingAjaxPublishedArticles(){
    console.log('initiated loadOngoingAjaxPublishedArticles');
    $.ajax({
        type: 'POST',
        url: '/contrib/load-ongoing-ajax-published-articles',
        success: function (data) {
            $("#previous-work").html(data);
        }
    });
}
function loadOngoingAjaxEncoursArticles(){
    console.log('initiated loadOngoingAjaxEncoursArticles');
    $.ajax({
        type: 'POST',
        url: '/contrib/load-ongoing-ajax-encours-articles',
        success: function (data) {
            $("#ongoing-stack").html(data);
        }
    });
}

function loadOngoingAjaxAwaitingArticles(){
	console.log('initiated loadOngoingAjaxAwaitingArticles');
    $.ajax({
        type: 'POST',
        url: '/contrib/load-ongoing-ajax-awaiting-articles',
        success: function (data) {
            $("#awaiting_Articles").html(data);
        }
    });
}

    $( document ).ajaxComplete(function() {
        console.log( "Triggered ajaxComplete handler." );
        starttimmer();
    });
</script>
{/literal}
 <div class="container">
	<div class="row-fluid"><h1>Mes participations</h1>  </div>
 
	<div class="row-fluid">
		<div class="span8">
			<section id="quick-classified">
				<div class="mod" id="awaiting_Articles">
					<!--Author: Thilagam-->
					<!--Date: 18/5/2016-->
					<!--Reason:The code is moved to ongoing_ajax.phtml.To load the data through ajax-->
                    <img src="/FO/images/loading-data.gif" alt="Loading..">
				</div>

				<!-- List of classifieds that contributor might like -->
				<div class="mod" id="recent_AO_Offers">
                    <!-- Loading...-->
					<!--Author: Thilagam-->
					<!--Date: 18/5/2016-->
					<!--Reason:To replace the text with image-->
                    <img src="/FO/images/loading-data.gif" alt="Loading..">
				</div>


			</section>
		</div>
		
		<div class="span4">
		<!--  right column  -->
	  
			<aside id="participation">
				<div class="aside-bg mission">
					<h3>Mes missions</h3>
					<div  id="ongoing-stack">
					<!-- Loading...-->
					<!--Author: Thilagam-->
					<!--Date: 18/5/2016-->
					<!--Reason:To replace the text with image-->
                    <img src="/FO/images/loading-data.gif" alt="Loading..">						
					</div>	<!-- id="ongoing-stack" -->

					<div class="aside-block" id="previous-work">
                        <!-- Loading...-->
						<!--Author: Thilagam-->
						<!--Date: 18/5/2016-->
						<!--Reason:To replace the text with image-->
                        <img src="/FO/images/loading-data.gif" alt="Loading..">
					</div>
				</div><!-- aside-bg mission -->
			</aside>  	
		</div>
		
	</div>
</div>