{literal}
<script type="text/javascript">
// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();	
	startTimer('time1','text1'); //timer ids starting with
	startTimer('time2','text2');//timer ids starting with
</script>
{/literal}
{if $pollDetails | @count gt 0}
	{foreach from=$pollDetails item=poll name=details}
	<section id="a_o">
		
			{if $mission_type eq 'poll_premium'}
				<div class="dp">
				<span data-placement="right" rel="tooltip" data-original-title="Cette annonce est susceptible de devenir une mission Premium" class="label label-quote-premium">Devis premium</span>
			{elseif $mission_type eq 'poll_nopremium'}
				<div class="dl">
				<span data-placement="right" rel="tooltip" data-original-title="Vous travaillerez en direct avec le client" class="label label-quote">Devis  Libert&eacute;</span>	
			{/if}			
			<h2>{$poll.title}</h2>

			<div class="summary clearfix">
					<ul class="unstyled">
						<li><strong>Appel &agrave; r&eacute;daction</strong> <span class="bullet">&#9679;</span></li>
						<li> Langue : <img class="flag flag-{$poll.language}" src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$poll.language_name}"> <span class="bullet">&#9679;</span></li>
						<li>Cat&eacute;gorie : {$poll.category} <span class="bullet">&#9679;</span></li>
						<li>Nb. de mots : {$poll.min_sign} - {$poll.max_sign} / article <span class="bullet">&#9679;</span></li>
						<li><a href="#comment" class="scroll" id="comment_count_1"><i class="icon-comment"></i> {$commentCount}</a></li>
						{if $poll.spec_exists eq 'yes'}
							<li class="pull-right"><a href="/contrib/download-file?type=pollbrief&article_id={$poll.pollId}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> T&eacute;l&eacute;charger le brief client</a></li>
						{/if}	
					</ul>
				</div>

			<div class="a_o-details">
				<!-- start, colonne generale -->
				<div class="row-fluid">
					<div class="span7">
					<!-- start, colonne stat -->
						<div class="row-fluid stat-block">
							<div class="span4 section">Temps restant
								<p>
									{if $upcoming eq 'yes'}
										&#9679;&#9679;&#9679;
									{else}
										<span id="time1_{$poll.pollId}_{$poll.timestamp}">
											<span id="text1_{$poll.pollId}_{$poll.timestamp}">{$poll.timestamp}</span>
										</span>
									{/if}	
								</p>
						  </div>
								<div class="span4 section"><span rel="popover" data-placement="top" data-html="true" data-content="* Temps indicatif si le devis devient mission  premium" data-trigger="hover">Temps estim&eacute; de production
							    <p>
										{if $upcoming eq 'yes'}
											&#9679;&#9679;&#9679;
										{else}
											<em>{$poll.production_time}</em> h
										{/if}									</p>
								</span>								</div>
							<div class="span4 section">Client<p><img src="{$poll.client_pic}"  class="logo"/></p></div>
						</div>
						<div class="row-fluid note">
							<div class="span12">
								{if $mission_type eq 'poll_premium'}
									<p><i class="icon-info-sign icon-white"></i> R&eacute;pondez à ce devis et <strong>soyez prioritaire pendant 24h</strong> si l'annonce se transforme en <span class="label label-premium">mission premium</span></p>
								{elseif $mission_type eq 'poll_nopremium'}
									<p><i class="icon-info-sign icon-white"></i> <strong>Tentez votre chance !</strong> Attention, Il peut s'agir d'une simple demande d'information ou d'une vraie mission de r&eacute;daction.</p>
								{/if}
							</div>

						</div>
					<!-- end, colonne stat -->
					</div>

					<div class="span5">
						<table class="table">
							{if $upcoming eq 'yes'}
								<tr><td class="title">Ouverture de l'annonce</td><td class="countdown">{$poll.publishtime_format}</td></tr>
								<tr>
									<td colspan="2" class="cta" >
										<span id="alert_{$poll.pollId}">											
											{if $poll.alert_subscribe eq 'no'}
												<button class="btn" onclick="subscribeAOAlert('{$poll.pollId}','yes','poll');"><i class="icon-bell"></i> Etre alert&eacute;</button>
											{elseif $poll.alert_subscribe eq 'yes'}
												<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$poll.pollId}','no','poll');"><i class="icon-remove icon-white"></i> Alerte programm&eacute;e</a>
											{/if}
										</span>
										
									</td>
								</tr>
							{else}
								<tr><td class="title">Participants</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="Info participants" data-placement="left" data-html="true" {if $poll.participants_pic} data-content="{$poll.participants_pic}" data-trigger="hover"{/if}>{$poll.totalParticipation}</a></em></td></tr>
								<tr><td class="title">Dernier prix propos&eacute;</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="Tous les prix proposés" data-placement="left" data-html="true" {if $poll.participants_price} data-content="{$poll.participants_price}" data-trigger="hover"{/if}>
								{if $poll.latestPrice} 
									{$poll.latestPrice} &euro;
								{else}
									NA
								{/if}
								
								</a></em></td></tr>
								{if !$request_from && $ResponseExist eq 'yes'}
								<tr><td colspan="2" class="cta" id="tender_select_{$poll.pollId}">								
									{if $poll.display eq 'no' || $disabled eq 'yes'}
										<button class="btn btn-large btn-primary disabled">Annonce ajout&eacute;e</button>	
									{elseif $poll.attended eq 'YES'}								
										<button  onClick="fnCartDevisModifiers('p_remove','{$poll.pollId}','');" class="btn btn-large btn-danger">Annonce ajout&eacute;e</button>
									{elseif $poll.attended eq 'NO'}
										<button onClick="fnCartDevisModifiers('p_add','{$poll.pollId}','');" class="btn btn-large btn-primary">Je participe ! </button>
									{/if}	
									</td></tr>
								{/if}
							{/if}	
						</table>
					</div>
				</div>
				<!-- end, colonne generale -->
				{if $upcoming neq 'yes'}
					<!-- Start, question form -->
						{include file="Contrib/popup_devis-q.phtml"}	
					<!-- Stop, question form -->				
				{/if}	
				
			</div>
			<!-- Start, comment form -->
			{include file="Contrib/article-comments.phtml"}
			<!-- Stop, comment form -->
			
		</div>
	</section>

	<a href="#brand" class="pull-right btn btn-small disabled anchor-top scroll"><i class="icon-arrow-up"></i></a>
	<div id = "confirmDiv"></div>
	{include file="Contrib/popup_confirm_selection.phtml"}
{/foreach}
{else}
<section>
	<div class="row-fluid">
		<div class="pull-center span10 offset1">
			<p class="text-error lead"> Vous ne pouvez pas participer &agrave; cette mission.</p>
		</div>
	</div>
</section>
{/if}	
{literal}
<script>
 	$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});
</script>	
{/literal}