{literal}
<script type="text/javascript">
$("#menu_profile").addClass("active");

/**cv uploading**/
$(function(){
		var btnUpload=$('#upload_cv');
		var status=$('#cv_status');
		new AjaxUpload(btnUpload, {
			action: 'upload-cv',
			name: 'cv_file',
			onSubmit: function(file, ext){
				 if (! (ext && /^(doc|docx|pdf)$/.test(ext))){ 
                    // extension is not allowed 
					status.text('Only doc,docx,pdf files are allowed').css('color','#FF0000');
					return false;
					}

				 /*if (! (ext && /^(doc|docx|rtf)$/.test(ext))){ 
                    // extension is not allowed 
					status.html('Only doc,docx,rtf files are allowed').css('color','#FF0000');
					return false;
					}*/
				status.html('<img src="/FO/images/icon-generic.gif" /> uploading..');
			},
			onComplete: function(file, response){
				//On completion clear the status
				status.html('');
				
				var obj = $.parseJSON(response);
				if(obj.status=="success"){
					
					status.html('CV publi&eacute; le : <time datetime="'+obj.published+'">'+obj.published+'</time>.');		
					$("#download_cv").show();		
					
				}				
				else{
					status.html('Error in upload').css('color','#FF0000');
				}
			}
		});			
	});
</script>
{/literal}
<div class="container">
 
	<section id="status">
		<div class="row-fluid">
			<div class="profilehead-mod">
				<div class="span2">
					<div class="editor-container">
						{if $profileType eq 'senior'}
							<span data-original-title="Niveau Senior" data-content="J'ai au moins 5 articles valid&eacute;s sur Edit-place. Je suis un contributeur confirm&eacute; chez Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S&eacute;nior</span>
						{elseif $profileType eq 'junior'}
							<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Junior</span>
						{elseif $profileType eq 'sub-junior'}
							<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D&eacute;butant</span>	
						{/if}	
							
						<a class="imgframe-large" href="/contrib/modify-profile"><img src="{$profile_image}" title="{$client_email}"></a>
					</div>
				</div>
				<div class="span7 profile-name">
					<h3>{$client_email}</h3>
					<p class="" style="">{$ep_contrib_age} ans  <span class="muted">&bull;</span>  {$allCategories}  <span class="muted">&bull;</span> {$ep_language} {if $allLanguages} , {$allLanguages}{/if}</p>
					<blockquote>
						<i class="icon-leaf"></i> {$ep_contrib_profile_self_details}
					</blockquote>
				</div>

				<div class="span3 stat">
					<div class="progress progress-success">
						<div class="bar" style="width: {$profile_percentage}%"></div>
					</div>
					Votre profil est rempli &agrave; <strong>{$profile_percentage}%</strong>
					<hr>
					<p class=""><a class="btn btn-small btn-block btn-primary" href="/contrib/modify-profile"><i class="icon-refresh icon-white"></i> Actualiser mon profil</a></p>
					<p><a href="/contrib/public-profile" role="button" data-toggle="modal" data-target="#viewProfile-ajax" class="btn btn-small btn-block"> Voir mon profil public</a></p>
				</div>
			</div>
		</div>
	</section>
	 <!-- end, contributor status --> 
	<div class="row-fluid"> 
		<div class="span8">
			<section id="skills">
				<div class="mod">
					<h4>Langues</h4>
					<strong>{$ep_language}</strong> (langue maternelle)
					{if $language_more|@count gt 0}
						{foreach from=$language_more item=lang}
							<div class="skillstat row-fluid">
								<div class="span6">
									<p><strong>{$lang.name}</strong>  {$lang.percent}%</p>
									<div class="progress">
										<div class="bar" style="width: {$lang.percent}%"></div>
									</div>
									<span class="pull-left legend muted">D&eacute;butant</span> <span class="pull-right legend muted">Bilingue</span>
								</div>
							</div>
						{/foreach}
					{/if}	
				</div>

				<div class="mod">
					<h4>Domaines de comp&eacute;tences</h4>

					{if $category_more|@count gt 0}
						{foreach from=$category_more item=category}
							<div class="skillstat row-fluid">
								<div class="span6">
									<p><strong data-original-title="{$category.name}" rel="tooltip">{$category.name}</strong>  {$category.percent}%</p>
									<div class="progress">
										<div class="bar" style="width: {$category.percent}%"></div>
									</div>
									<span class="pull-left legend muted">D&eacute;butant</span> <span class="pull-right legend muted">Expert</span>
								</div>
							</div>		
						{/foreach}
					{/if}			
				</div>
				<div class="mod">
					<h4>Exp&eacute;riences professionnelles</h4>
					{if $jobDetails|@count gt 0}
					<dl>
						{foreach from=$jobDetails item=job name="job_details"}
							<dt>{$job.title}</dt>
							<dd class="company">{$job.institute}</dd>
							<dd class="muted">
								Type de contrat : {if $job.contract=='cdi'}CDI{elseif $job.contract=='cdd'}CDD{elseif $job.contract=='freelance'}Freelance{elseif $job.contract=='intern'}Interim{/if}
							</dd>
							<dd class="muted">
								<time datetime="{$job.start_date}">{$job.start_date}</time> - <time datetime="{$job.end_date}">{$job.end_date}</time>
							</dd>
						{/foreach}							
					</dl>
					{/if}
				</div>
				<div class="mod">
					<h4>Formations</h4>
					{if $educationDetails|@count gt 0}
					<dl>	
						{foreach from=$educationDetails item=education name="edu_details"}
							<dt>{$education.title}</dt>
							<dd class="company">{$education.institute}</dd>
							<dd class="muted">
								<time datetime="{$education.start_date}">{$education.start_date}</time> - <time datetime="{$education.end_date}">{$education.end_date}</time>
							</dd>
							{/foreach}
					</dl>
					{/if}

				</div>
                <div class="mod">
                    <h4>Informations personnelles</h4>
                    <address>
                        <strong>{$ep_contrib_profile_fname} {$ep_contrib_profile_lname}</strong><br>
                        {$ep_contrib_profile_address}<br>
                        {$ep_contrib_profile_city}, {$ep_contrib_profile_postalcode}<br>
                        <abbr title="T&eacute;l&eacute;phone">Tel:</abbr> {$ep_contrib_profile_telephone}
                    </address>
                    Nationalit&eacute; : {$nationality}
                </div>
                {*<!-- added by naseer on 03-08-2015 -->
                <!-- if condition to display all based on the option user have selected --> *}
                {if $options_flag eq 'reg_check'}
                <div class="mod">
                    <h4>En cours d'immatriculation</h4>
                        <strong>Num&eacute;ro de passeport :</strong> {$passport_no}
                        <br />
                        <strong>Carte d'identit&eacute; :</strong> {$id_card}
                </div>
                {elseif $options_flag eq 'com_check'}
                <div class="mod">
                    <h4>Soci&eacute;t&eacute;</h4>
                    <address>
                        <strong>Nom de la soci&eacute;t&eacute; : {$com_name}</strong><br>
                        Address : {$com_address}<br>
                        Ville : {$com_city},<br/>
                        Code postal : {$com_zipcode}<br>
                        <abbr title="T&eacute;l&eacute;phone">Tel:</abbr> {$com_phone}<br />
                        TVA Number : {$com_tva_number}<br />
                        {$com_country}
                    </address>
                    {if $com_country eq "FRANCE"}
                    SIREN : {$com_siren}
                    {/if}
                </div>
                {elseif $options_flag eq 'tva_check'}
                <div class="mod">
                    <h4> Assujetti  &agrave; la TVA (entreprise - auto-entrepreneur) </h4>
                    Num&eacute;ro de TVA Intracommunautaire: {$tva_number}
                </div>
                {/if}
                <div class="mod">
                    <h4>Software Ownership and Experience Level</h4>
                    <table class="table table-bordered">
                        <tr>
                            <td></td>
                            <td>Beginner</td>
                            <td>Intermediate</td>
                            <td>Advanced</td>
                            <td>I own it</td>
                        </tr>
                        {assign var="previous_software" val=""}
                        {foreach from=$ep_software_array key=softwarekey item=software name="SoftwareList"}
                        {assign var=s_index value=$smarty.foreach.SoftwareList.index+1}

                        <!--code to check if the value is saved in DB-->
                        {assign var=check value=0}
                        {assign var=condition value="false"}
                        {assign var=level value="false"}
                        {assign var=own value="false"}
                        {while $check < $software_list_count}
                        {if $software_list[$check][0] eq $softwarekey}
                        {assign var=condition value="true"}
                        {assign var=level value=$software_list[$check][1]}
                        {assign var=own value=$software_list[$check][2]}
                        {/if}
                        {assign var=check value=$check+1}
                        {/while}
                        <!-- end of code to check if the value is saved in DB -->
                        {if $condition eq "true"}
                            {if $previous_software neq $software[0]}
                            <tr style="background-color: #DDDDDD;">
                                <td><b>{$software[0]}</b></td>
                                <td colspan="4"></td>
                            </tr>
                            {/if}
                        <tr>
                            <td>

                                    {$software[1]}

                            </td>
                            <td> {if $level eq 'beginner'}<i class="icon-ok "></i>{else}-{/if}</td>
                            <td> {if $level eq 'intermediate'}<i class="icon-ok "></i>{else}-{/if} </td>
                            <td>{if $level eq 'advanced'}<i class="icon-ok "></i>{else}-{/if} </td>
                            <td> {if $own eq "on"}<i class="icon-ok "></i>{else}-{/if}</td>
                        </tr>
                        <!--{*{else}
                        <tr>

                            <td>
                                <label class="checkbox">
                                    <input type="checkbox" name="software_name[{$s_index}]" id="software_{$s_index}" value="{$softwarekey}" onclick="toggle_software_details(this.id);"  disabled/>{$software[1]}
                                </label>
                            </td>

                            <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="beginner" disabled/></label></td>
                            <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="intermediate" disabled/></label></td>
                            <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="advanced" disabled/></label></td>
                            <td><label class="checkbox"><input type="checkbox" name="software_own[{$s_index}]" class="software_{$s_index}" disabled/></label></td>
                        </tr>*}-->
                        {/if}
                        {*{/for}*}
                        {assign var="previous_software" value=$software[0]}
                        {/foreach}

                    </table>

                </div>
				<div class="mod"><a href="/contrib/modify-profile" class="btn btn-primary pull-right"><i class="icon-refresh icon-white"></i> Actualiser mon profil</a>
				</div>
			</section>
		</div>
		<div class="span4">
			<!--  right column  -->
			<aside>
				<div class="aside-bg">
					<div class="aside-block" id="we-trust">
						<h4>Vos publications</h4>
						{if $publishedClients | @count gt 0}
						<ul class="unstyled">
							{foreach item=pclient from=$publishedClients}
								<li><img title="{$pclient.company_name}" src="{$pclient.client_pic}"></li>
							{/foreach}
							
						</ul>
						{/if}
						
					</div>
					<div class="aside-block" id="shipping">
						<h4>Info de facturation</h4>

						<dl>
							{*<dt>Statut</dt>
							{if $ep_contrib_profile_pay_info_type =='ssn'}
								<dd class="company">Droit d'auteur (AGESSA)</dd>
								<dd class="muted">
									N&deg; de  S&eacute;curit&eacute; sociale : {$ep_contrib_profile_SSN}
								</dd>
							{elseif $ep_contrib_profile_pay_info_type =='comp_num'}
								<dd class="company">Autoentrepreneur</dd>
								<dd class="muted">
									N&deg; de SIRET : {$ep_contrib_profile_company_number}
								</dd>
								<dd class="muted">
									Soumis &agrave; la TVA : {if $ep_contrib_profile_vat_check=='YES'}OUI{else}NON{/if}
								</dd>
							{elseif $ep_contrib_profile_pay_info_type =='out_france'}
								<dd class="company">Statut hors France </dd>
							{/if}*}		
							
							<dt>Choix de r&eacute;mun&eacute;ration</dt>
							<dd class="muted">
								<p class="btn btn-small disabled">
									{if $ep_contrib_profile_payment_type eq 'paypal'}
										Paypal
									{elseif $ep_contrib_profile_payment_type eq 'cheque'}
										Ch&egrave;que
									{elseif $ep_contrib_profile_payment_type eq 'virement'}
										VIREMENT BANCAIRE	
									{/if}	
								</p>
							</dd>
							<dt>Vos royalties</dt>
							<dd class="muted">
								Gains depuis la derniere facture : <strong><a href="/contrib/royalties">{$userRoyalty|zero_cut:2} &euro;</a></strong>
							</dd>
						</dl>
					</div>
					<div class="aside-block" id="cv">
						<h4>Mon CV</h4>
						Votre CV est consult&eacute; par Edit-place ou le  client lorsque vous avez &eacute;t&eacute; s&eacute;lectionn&eacute; pour une mission. Pensez &agrave; le mettre &agrave;  jour r&eacute;guli&egrave;rement.
						
						<p class="muted" id="cv_status">
							{if $cv_exists eq 'yes'}
								CV publi&eacute; le : <time datetime="{$cv_uploaded_at}">{$cv_uploaded_at}</time>.
							{/if}	
						</p>	
						<div class="btn-group">
							
								<a class="btn btn-small" id="download_cv" href="/contrib/download-file?type=cv" {if $cv_exists neq 'yes'} style="display:none" {/if}><i class="icon-download"></i> T&eacute;l&eacute;charger</a>
								<a class="btn btn-small" id="upload_cv" title="Aucun fichier s&eacute;lectionn&eacute;"><i class="icon-upload"></i> Nouvelle version</a>
						</div>
					</div>
				</div>
			</aside>  
		</div>
	</div>
</div>