{literal}
<script type="text/javascript">
var cur_date={/literal}{$smarty.now}{literal};
var js_date=(new Date().getTime())/ 1000;
var diff_date=Math.floor(js_date-cur_date);
 $(document).ready(function() {			 
    startCountDown();
	calculateReward();
	
	var confirm_message="En  cliquant sur &quot;Je suis d\'accord&quot;, je soumets ma participation et mes  informations ne seront pas modifiables par la suite.";
	
	$('#recruitment-submit-modal').click(function(event){
		event.preventDefault();
		var href=$(this).attr('href');
		if(validateRecruitmentChallenge())
		{
			bootbox.confirm(confirm_message,function(e){
				if (e)
				{
					$('#playQuizz-ajax').removeData('modal').modal({
						remote: href
					});
				}
				else
				{
					return false;
				}	
			});			
		}		
    })
	
	
	//price validation
	$("#recruitment-submit").click(function(){		
		if(validateRecruitmentChallenge())
		{			
			bootbox.confirm(confirm_message,function(e){
				if (e)
				{
					$("#recruitment-challenge1").submit();
				}
				else
				{
					return false;
				}	
			});
			
			
		}	
	});	
	
});	

function validateRecruitmentChallenge()
{
	var error=0,top=400,price_min=0,price_max=0,errtype='';
	var obj;
	var msg1='',msg2='';
	
	var writer_price=parseFloat($("#proposed_cost").val().replace(",","."));
	var article_per_weeks=parseInt($("#articles_per_week").val());
	var priceRegex=/^[0-9]+(\.?[0-9]+)?$/;
	var priceRegex1=/^[0-9]+(,?[0-9]+)?$/;
	
	var recruitment_id='{/literal}{$smarty.get.recruitment_id}{literal}';
	
	//alert(recruitment_id);
	var request = $.ajax({
		url: "/recruitment/get-pricerange",
		type: "POST",
		data: {recruitment_id : recruitment_id},
		async: false,
		dataType: 'json',
		success: function(data) {
			//alert(data);
			if(data.error=="time_out")
			{
				var errtype="time_out";
				//error=error+1;
				
			}	
			else
			{	
				price_min=parseFloat(data.price_min);
				price_max=parseFloat(data.price_max);
				max_articles_per_contrib=data.max_articles_per_contrib;						  
			}
		}
	});
	//alert(price_min+'--'+price_max+'--'+writer_price);
	//alert(writer_price<=price_max);
	if((writer_price>=0 && writer_price<=price_max && (priceRegex1.test(writer_price) || priceRegex.test(writer_price))))
	{
		$('#proposed_cost').addClass("valid");
	}
	else
	{
		$('#proposed_cost').addClass("error");
		error=error+1;
		if(errtype=="time_out")
			msg1="Time is out, Sorry";
		else
			msg1="Vous devez indiquer un tarif faisant partie de la fourchette de prix<br>";
	}
	
	if(article_per_weeks>0 && article_per_weeks<=max_articles_per_contrib)
	{
		$('#articles_per_week').addClass("valid");
	}
	else
	{
		$('#articles_per_week').addClass("error");
		error=error+1;
		if(errtype=="time_out")
			msg2="Time is out, Sorry";
		else
			msg2="Vous devez indiquer un nombre d'articles valide";
	}
	
	if(error>0)
	{
		$('html, body').animate( { scrollTop: top }, 'slow' );
		bootstrap_alert.error(msg1+msg2);
		return false;
	}
	else
	{			
		return true;
	}

}

function calculateReward()
{
	var total_weeks=parseFloat($("#total_weeks").val());
	var price_article=parseFloat($("#proposed_cost").val());
	var article_per_weeks=parseFloat($("#articles_per_week").val());
	//alert(total_weeks+'--'+price_article+'--'+article_per_weeks);
	var potential_reward=(total_weeks*price_article*article_per_weeks);
	if(isNaN(potential_reward))
		potential_reward=0;
	else
		potential_reward = potential_reward.toFixed(2);
	$("#potential_reward").text(potential_reward);	
}

function startCountDown()
{
 //////////show timer//////////
	$("[id^=time1_]").each(function(i) {
		var article=$(this).attr('id').split("_");
		var ts=article[2];
		$("#time1_"+article[1]+"_"+article[2]).countdown({
			timestamp   : ts,
            diff_date  : diff_date,
			callback    : function(days, hours, minutes, seconds){
				var message = "";
				if(days>0)
					message += days + " jour(s)" +" ";
				if(hours>0)	
					message += hours + " h" +" ";
				if(minutes > 0)
					message +=minutes + " mins"+ " ";
				//if(minutes < 1)
					message +=seconds +" s";
				$("#text1_"+article[1]+"_"+article[2]).html(message);
				if(days==0 && hours==0 && minutes==0 && seconds==0)
				{
					//window.location.reload();
				}
			}
		});
	});

}

function downloadTestBrief(recruitment_id)
{
	var download_href="/contrib/download-file?type=recruitment&recruitment_id="+recruitment_id;
	
	window.open(download_href, "_blank");
	setTimeout((function() {
	  window.location.reload();
	}), 250);
}
</script>
{/literal}

{if $actionmessages[0]}
	<div class="alert alert-danger"><button data-dismiss="alert" class="close" type="button">&times;</button>
		{$actionmessages[0]}
	</div>
{/if}
		
{if $recruitmentDetails|@count gt 0}
	
	{foreach from=$recruitmentDetails item=recruit name="recruit"}	
		<div class="container">
			<section id="challenge">
				<div id="status">
					<ul>
						{if $recruit.recruitmentParticipationId}
						<li class="done"><span><i class="icon-ok"></i></span> Participez</li>
						  {else}
					    <li class="active"><span>1</span> D&eacute;marrer</li>
						{/if}
					  {if $recruit.quiz_id}
						  {*
						  <li class="{if $recruit.link_quiz eq 'yes' && $recruit.qualified eq 'no'} active {elseif $recruit.recruitmentParticipationId} done{/if}"><span>2</span> Quizz</li>
						  *}
						  {if $recruit.link_quiz eq 'yes' && $recruit.qualified eq 'no'}
						  <li class="active"><span>2</span> Quizz</li>
						  {elseif $recruit.recruitmentParticipationId}
						    <li class="done"><span><i class="icon-ok"></i></span> Quizz</li>
							{else}
							 <li class=""><span>2</span> Quizz</li>
					      {/if}
						  <li class="{if $recruit.link_quiz eq 'yes' && $recruit.qualified eq 'yes' && $recruit.recruitmentParticipationId}active{/if}"><span>3</span> Article test</li>
						  <li><span>4</span> validation</li>
					  {else}
						  <li class="{if $recruit.recruitmentParticipationId}active{/if}"><span>2</span> Article test</li>
						  <li><span>3</span> validation</li>
					  {/if}
					 
				  </ul>
				</div>
			
				<h1>Participer &agrave; cette mission</h1><hr>
				<div class="row-fluid">
					<div class="span8">
						<div class="">
							<h2 style="font-weight:300">{$recruit.recruitment_title}</h2>
							<h4>
								<span class="muted">Fin de la participation dans :</span>
								<span class="time" id="time1_{$recruit.recruitment_id}_{$recruit.recruit_expires}">
									<span id="text1_{$recruit.recruitment_id}_{$recruit.recruit_expires}">{$recruit.recruit_expires}</span>
								</span>
							</h4>
							
							<br><br>
							<h4>A propos de la mission</h4>
							<p class="lead" style="line-height: 26px">
								{$recruit.editorial_chief_review|stripslashes}
							</p>
							{if $recruit.recruitment_file_name}
							<a href="/contrib/download-file?type=recruitment&recruitment_id={$recruit.recruit_art_id}" class="btn btn-default"><i class="icon-download"></i> T&eacute;l&eacute;charger le brief</a>
							{/if}
							<br><br><hr>
							<div class="row-fluid">
								<div class="span4">
									<h4>Royalties total revers&eacute;s</h4>
									<p class="lead" style="line-height: 26px">
									{* {$recruit.turnover} &euro; of royalties to be shared between {$recruit.num_hire_writers} writers. Do you want to be one of them?
									*}
									{$recruit.turnover} &euro; sur toute la dur&eacute;e de la mission. Seulement {$recruit.num_hire_writers} r&eacute;dacteur(s) recherch&eacute;(s).
									</p>
								</div>
								<div class="span4">
									<h4>Dur&eacute;e de la mission</h4>
									<p class="lead" style="line-height: 26px">
										{$recruit.delivery_time_frame} {$recruit.day_fr}
									</p>
								</div>
								<div class="span4">
									<h4>Client</h4>
									<p class="lead" style="line-height: 26px">
										<img src="{$recruit.client_pic}">
									</p>
								</div>
							</div>
							<div class="row-fluid">
								<div class="promote">
									<img width="44" src="{$recruit.bo_user_pic}" class="pull-left  img-circle">
									<div class="profile-name pull-left">
										Post&eacute; par {$recruit.bo_user}
										<div class="time">
											{$recruit.time_ago}
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="span4">
						<form class="form-horizontal" action="/recruitment/save-participation" id="recruitment-challenge1" method="POST" autocomplete="off">
							<input type="hidden" id="recruitment_id" name="recruitment_id" value="{$smarty.get.recruitment_id}">
							<input type="hidden" id="total_weeks" name="total_weeks" value="{$recruit.total_weeks}">
						
							<div id="apply_form" class="about mod">
								<h3>Votre proposition</h3> 
								<p class="text-error"> {if $recruit.active_participations} {$recruit.active_participations} personnes ont postul&eacute; &agrave; cette offre{else}Vous &ecirc;tes le premier &agrave; postuler{/if}</p>
								<hr>
								<h4>Vos Royalties</h4>
								<h2><span id="potential_reward">0</span> &euro;</h2>
								<label>Votre tarif pour un article en &euro; ?</label>
								<div class="input-prepend input-append">
									<span class="add-on">{$recruit.price_min|zero_cut:2}</span>
									<input id="proposed_cost" type="text" value="{$recruit.proposed_cost}" name="proposed_cost"  class="span8" {if $recruit.recruitmentParticipationId} disabled {/if} onkeyup="calculateReward()">
									<span class="add-on">{$recruit.price_max|zero_cut:2}</span>
								</div>


								<label>Nombre d'articles que vous pouvez envoyer par semaine ?  </label>
								<input id="articles_per_week" type="text" value="{$recruit.articles_per_week}" name="articles_per_week" {if $recruit.recruitmentParticipationId} disabled {/if}  onkeyup="calculateReward()" class="span10"  placeholder="{$recruit.max_articles_per_contrib} maximum">
								<br> <br>  
								<div class="row-fluid">
									<div id = "alert_placeholder"></div>
								</div>
								
								{if $participationexpired!='yes'}
									{if !$recruit.recruitmentParticipationId}								
										{if $recruit.link_quiz eq 'yes' && $recruit.quiz_id}
											{*<a class="btn btn-primary btn-large" data-target="#playQuizz-ajax" data-toggle="modal" role="button" href="/quiz/participate-recruitment-quiz?recruitment_id={$recruit.recruitment_id}&quiz_identifier={$recruit.quiz_id}">Valider</a>*}
											<a class="btn btn-primary btn-large" href="/quiz/participate-recruitment-quiz?recruitment_id={$recruit.recruitment_id}&quiz_identifier={$recruit.quiz_id}" id="recruitment-submit-modal">Valider</a>
										{else}
											{*<input type="submit" value="Valider" name="Validate" class="btn btn-primary btn-large">*}
											<input type="button" class="btn btn-primary btn-large" id="recruitment-submit" value="Valider">
										{/if}
									{/if}		
								{/if}								
							</div>	
						</form>	
					</div>
				</div>
				<hr>
				{if $recruit.recruitmentParticipationId}
					{include file="Contrib/recruitment-participation-challenge2.phtml"}		
				{/if}
			</section>	
		</div>	
	{/foreach}
{/if}	