{literal}
<style type="text/css">
.profilehead-mod .stat .num-large
{
color:#333;
}
</style>
<script type="text/javascript">
	$("#menu_royalties").addClass("active");
	var unpaidCount={/literal}{$unpaidCount}{literal};

	/*function to check whether payment info added or not in profile
	if not then redirect to profile page to validate payment info
	if yes will show pop up with article details */
	
$(function(){	



	$("#invoicedetails").click(function(){
		
		$.get('/contrib/check-payment-info', function(data) {			
			if(data=='YES')
			{
				if(unpaidCount>0)
				{
					$("#confirmDiv").confirmModal({	
						heading: 'Confirm',
						body: "Les missions pour lesquelles vous demandez le paiement s'ajouteront au bon de commande d&eacute;j&agrave; g&eacute;n&eacute;r&eacute; lors de votre premi&egrave;re demande ce mois-ci. La date de paiement que vous choisissez pour ce second paiement sera prise en compte pour toutes les missions. Souhaitez-vous valider cette demande&nbsp;?",
						callback: function () {				
							$("#billing-ajax").modal({
								remote: "/contrib/invoicedetails?oldinvoice=yes"
							});								
							//window.location="/contrib/generatepdf/";
						}	
					});
				}
				else{
					$("#billing-ajax").modal({
						remote: "/contrib/invoicedetails"
					});	
				}
				
			}
			else
			{
				window.location.href='/contrib/modify-profile?profile=invoice#pay_info_type';
			}
			
		});			
	});
});	
	
</script>
{/literal}	

<div class="container">
	<!-- start, get contributor status -->
	<section id="status">
		<div class="row-fluid">
			<div class="profilehead-mod">
				<div class="span6">
					<h1>Mes royalties</h1>
				</div>

				<div class="span3 stat">
					<p>En attente de paiement</p>
					<p class="num-large">{$pending_royalties|zero_cut:2} &euro;</p>
				</div>
				<div class="span3 stat"><p>Total royalties</p><p class="num-large"><a href="#">{$total_royalties|zero_cut:2} &euro;</a></p></div>
			</div>
		</div>
	</section>
	 <!-- end, contributor status --> 
    
	<section id="royalties-not-paid">
		<div class="row-fluid">
			<div class="mod">
				<div class="muted pull-right">Mise &agrave; jour au {$smarty.now|date_format:"%d/%m/%Y"}</div>
				<h4>mes missions effectu&eacute;es non pay&eacute;es <i class="icon icon-question-sign" rel="tooltip" data-original-title="Une seule facture est g&eacute;n&eacute;r&eacute;e pour toutes les  missions effectu&eacute;es entre deux demandes de paiement. Le d&eacute;lai de paiement (avec  ou sans avances) court &agrave; partir du moment o&ugrave; vous avez effectu&eacute; votre premi&egrave;re  demande (min. {$ep_contrib_min_amount} euros)."></i> </h4>
				<table class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>Date</th><th>Mission effectu&eacute;e</th><th>Tarif</th>
						</tr>
					</thead>
					{assign var=total value=0.0}
					{if $unpaidRoyalties|@count gt 0}		
						{foreach item=article from=$unpaidRoyalties name=invoice}
							<tr>
								<td>{$article.royalty_added_at|date_format:"%d/%m/%Y"}</td>
								<td><a href="/contrib/mission-published?article_id={$article.articleId}" target="_invoice">
								{$article.AOTitle} - {$article.client_name|capitalize} - {$article.article_created_date}
								</a></td>
								<td>{$article.price|zero_cut:2} &euro;</td>
							</tr>
						{assign var=total value=$total+$article.price}
						{/foreach}
						
					{else}
						
					{/if}					
				</table>
				{if $unpaidRoyalties|@count gt 0}
					<p class="alert" style="text-align: right"><strong>Montant total &agrave; r&eacute;gler : {$unpaidTotal} &euro;</strong></p>
				{/if}					
				{if $unpaidTotal >= $ep_contrib_min_amount}
					<p style="margin:-18px 0px 30px 0px;padding:8px 35px 8px 14px;">
						<!--<a href="/contrib/invoicedetails" role="button" data-toggle="modal" data-target="#billing-ajax" class="btn btn-primary pull-right">Demander le paiement</a>-->
						<button class="btn btn-primary pull-right" id="invoicedetails" name="invoicedetails" type="button">Demander le paiement</button>						
					</p>
				{else}
					<p class="alert" style="text-align: right"><strong>Vous pouvez demander le paiement &agrave; partir de {$ep_contrib_min_amount} euros de reversements.</strong></p>
				{/if}	
				
				<p class="alert" style="text-align: right"><strong>Le paiement s'effectue minimum le 15 du mois  suivant votre demande (frais d'avance allant de 0 &agrave; 8% du montant)</strong></p>
			</div>
		</div>
	</section>
	<section id="billing-list">
		<div class="row-fluid">
			<div class="mod">
				<h4>MES BONS DE COMMANDE</h4>
				<table class="table table-hover">
					<thead>
						<tr><th>Date de la demande de paiement</th><th>Nom du bon de commande</th><th>Tarif total</th><th>Statut</th><th></th></tr>
					</thead>
					<tbody>
					{if $royalties | @count gt 0}	
						{foreach item=royalty from=$royalties}
						{if $royalty.invoiceId neq "ep_invoice_2014-05-1-120224141203205"} {* We have hided invoice for user userId=120224141203205 manually for the moment. by Rakesh ; Arun will update this condition later *}
						<!-- start, row -->
						<tr>
							<td>{$royalty.invoicedate|date_format:"%d/%m/%Y"}</td>
							<td>Bon de commande edit-place # {$royalty.invoiceId|replace:'ep_invoice_':''} - <a href="/contrib/invoicedetails?invoiceid={$royalty.invoiceId|replace:'ep_invoice_':''}" role="button" data-toggle="modal" data-target="#billing-ajax" class="muted">D&eacute;tails</a></td>
							<td>{$royalty.total_invoice_paid|zero_cut:2} &euro;</td>
							<td>
								{if $royalty.status=='refuse'}
									Refus&eacute;
								{elseif $royalty.status=='Paid'}
									Pay&eacute;e
								{elseif $royalty.status=='inprocess'}
									En cours de paiement	
								{else}
									{if $royalty.pay_later_month_name}
										<span rel="tooltip" data-html="true" data-original-title="Paiement pr&eacute;vu le 15 {$royalty.pay_later_month_name}">
											Non pay&eacute;e
										</span>	
									{else}
										Non pay&eacute;e									
									{/if}
								{/if}
								
							</td>
							<td>
								{if $royalty.status=='Paid'}
									<a class="btn btn-small" href="/contrib/downloadinvoice?invoiceid={$royalty.invoiceId|replace:'ep_invoice_':''}"><i class="icon-file"></i> T&eacute;l&eacute;charger</a>
								{/if}		
							</td>
						</tr>
						{/if}
						<!-- end, row -->
						{/foreach}

					{/if}	
					</tbody>
				</table>
				<!---Pagination start-->
					<div class="pagination pull-right">
						{include file="Contrib/pagination.phtml"}
					</div>	
					<!---Pagination END-->
			</div>
		</div>			
	</section>   
</div>
<div id = "confirmDiv"></div>
<!-- ajax use start -->
<div id="billing-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">D&eacute;tails facture</h3>
	</div>
	<div class="modal-body">

	</div>
</div>
<!-- ajax use end -->