<!-- Block to display coming soon articles -->
<div class="mod">
	<h3 id="soon">Annonces termin&eacute;es</h3>
	<table class="table table-hover">
		<thead>
			<tr>
				<th><a href="#orderByType">Type</a></th>
				<th>
					{if $smarty.get.torderByTitle eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByTitle=asc#finished">Titre</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.torderByTitle eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByTitle=desc#finished">Titre</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByTitle=asc#finished">Titre</a>	
					{/if}	
				</th>
				<th class="pc">
					{if $smarty.get.torderByLang eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByLang=asc#finished">Langues</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.torderByLang eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByLang=desc#finished">Langues</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByLang=asc#finished">Langues</a>	
					{/if}								
				</th>
				<th class="pc">
					{if $smarty.get.torderByAttendee eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByAttendee=asc#finished">Participants</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.torderByAttendee eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByAttendee=desc#finished">Participants</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByAttendee=asc#finished">Participants</a>	
					{/if}
					
				</th>												
			</tr>
		</thead>
		{if $terminatedArticles |@count gt 0}
			{foreach item=article from=$terminatedArticles name="articledetails"} 								
				<tr>
					{if $article.ao_type eq 'correction'}
								<td>
									{if $article.missiontest eq 'yes'}
										<span class="label label-mission-test" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission de correction test</span>
									{else}
										<span class="label label-correction" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Correction</span>
									{/if}
								{if $article.view_to eq 'sc'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.view_to eq 'jc'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.view_to eq 'jc0'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
								</td>
								<td class="title"><a class="muted"  href="/contrib/article-details?misson_type=correction&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}  {$article.picon} </span>
					{elseif $article.ao_type eq 'poll_premium'}
								<td><span class="label label-quote-premium" data-original-title="Cette annonce est susceptible de devenir une mission Premium" rel="tooltip" data-placement="right">Devis premium</span>
								{if $article.contributors eq '0'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.contributors eq '1'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.contributors eq '3'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
								</td>
								<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=poll_premium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>
					{elseif $article.ao_type eq 'poll_nopremium'}
								<td><span class="label label-quote" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Devis Libert&eacute;</span>
								{if $article.contributors eq '0'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.contributors eq '1'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.contributors eq '3'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
								</td>
								<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=poll_nopremium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>		
						{elseif $article.premium_option}
								<td>
									{if $article.missiontest eq 'yes'}
										<span class="label label-mission-test" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Test</span>
									{else}
										<span class="label label-premium" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Premium</span>
									{/if}
								{if $article.view_to eq 'sc'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.view_to eq 'jc'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.view_to eq 'jc0'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
						</td>
						<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=premium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
					{elseif !$article.premium_option}
						<td>
							{if $article.missiontest eq 'yes'}
								<span class="label label-mission-test" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Mission Test</span>
							{else}
								<span class="label label-quote" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Mission Libert&eacute;</span>	
							{/if}
						{if $article.view_to eq 'sc'}
							<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
						{elseif $article.view_to eq 'jc'}
							<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
						{elseif $article.view_to eq 'jc0'}
							<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
						{/if}
						</td>
						<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=nopremium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
					{/if}									
					<p class="muted">{$article.category}  &bull;  Appel &agrave; r&eacute;daction  &bull;  {$article.num_min} - {$article.num_max} mots / article</p></a></td>
					<td class="pc"><img src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$article.language_name}" class="flag flag-{$article.language}"></td>
					<td class="countdown pc"><em>{$article.participants}</em></td>					
				</tr>								
			{/foreach}
		{else}
			<tr>
				<td colspan="6">
					<span class="no-data">Aucun r&eacute;sultat</span>
				</td>
			</tr>
		{/if}
	</table>
</div>