{literal}
<script language="javascript" src="/FO/script/common/jquery.dataTables.js"></script>
<link href="/FO/css/common/jquery.dataTables.css" type="text/css" rel="stylesheet" />
<script language="JavaScript" type="text/javascript" src="/FO/script/common/jquery.MultiFile.js"></script>
<!--<script language="JavaScript" type="text/javascript" src="/FO/script/common/jquery-ui-1.8.16.custom.min.js"></script>
<script language="JavaScript" type="text/javascript" src="/FO/script/common/jquery.multiselect.js"></script>
<script language="JavaScript" type="text/javascript" src="/FO/script/common/jquery.multiselect.filter.js"></script>-->
<!--<script language="JavaScript" type="text/javascript" src="/FO/script/common/multi-select/js/jquery.multi-select.js"></script>
<script language="JavaScript" type="text/javascript" src="/FO/script/common/multi-select/js/jquery.quicksearch.js"></script>
-->
<!--<link href="/FO/css/common/jquery.multiselect.css" type="text/css" rel="stylesheet" />
<link href="/FO/css/common/jquery.multiselect.filter.css" type="text/css" rel="stylesheet" />
<link href="/FO/css/common/jquery-ui-1.8.16.custom.css" type="text/css" rel="stylesheet" />-->

<style type="text/css">
    .modal.fade.in
    {
        top:30%;
    }
    body {
        color: #555555;
        font-family: "open sans",Helvetica,Arial,sans-serif;
        font-size: 14px;
        font-weight: 300;
        line-height: 1.5em;!important;

    }
    .modal-body {
        height: 350px;
        overflow: auto;!important;
    }

</style>


<script language="javascript">
    $(document).ready(function() {

        //destroy the Modal object before subsequent toggles
        $('body').on('hidden', '.modal', function () {
            $(this).removeData('modal');
        });
        $('body').on('hidden', '.modal', function () {
            $(this).removeData('modal');
        });
        //destroy the Modal object before subsequent toggles
        $('body').on('hidden', '#newrequest', function () {
            $(this).removeData('newrequest');
        });
        $('body').on('hidden.bs.modal', '.modal', function () {
            $(this).removeData('bs.modal');
        });
        $('#newrequest').bind('hidden.bs.modal', function () {
            $("html").css("margin-right", "0px");
        });
        $('#newrequest').bind('show.bs.modal', function () {
            $("html").css("margin-right", "-15px");
        });

    });
    $(function(){
        $('#scltable').dataTable({
            "iDisplayLength": 25,
            "sPaginationType": "full_numbers",
            "aaSorting": [[ 1, "ASC" ]],
            "bLengthChange": false,
            "bSortClasses": false,
            "oLanguage": {
                "sSearch": "Rechercher : "
            }
        });
    });

    function closepopover(ind)
    {
        $('#popover_'+ind).popover('hide');
    }

</script>
{/literal}

<section id="quote-listing-table">
    <div class="mod">  <a  data-target="#newrequest" data-refresh="true"  data-toggle="modal"  role="button" class="btn btn-success pull-left"  href="/ftvedito/newrequest">Ajouter Une Demande</a>
        <table id="scltable">
            <thead>
            <tr>
                <th>Contact Client</th>
                <th>Date et heure de la demande</th>
                <th>Objet de la demande</th>
                <th>Ajouter un fichier</th>
                <th>Quand</th>
                <th>Emissions &agrave; modifier</th>
                <th>Contenus &agrave; modifier</th>
                <th>Etat de la demande</th>
                <th>Commentaire(s)</th>
                <th>Ajouter un commentaire</th>
                <th>Action</th>
            </tr>
            </thead>
            {if $requestsdetail |@count gt 0}
            {foreach from=$requestsdetail item=requestsitem name=requestsloop}
            <tr>
                <td>{$requestsitem.first_name}</td>
                <td>{$requestsitem.created_at|date_format:"%d/%m/%Y %H:%M"|upper}</td>
                <td><!--<a class="label label-level" data-placement="right" data-trigger="hover" rel="tooltip" data-original-title="{$requestsitem.request_object}"
                           data-content="{$requestsitem.request_object}">{if $requestsitem.request_object != ''}{$requestsitem.request_object|escape|stripslashes|truncate:"100"|wordwrap:30:"<br />\n"}{else}-NA-{/if}</a>-->
                    <a  data-placement="right" rel="tooltip" data-original-title="Objet de la demande" data-target="#showobjectdemand" data-refresh="true"  data-toggle="modal"  role="button"  href="/ftvedito/showrequestobject?request_id={$requestsitem.identifier}">
                        {$requestsitem.request_object|escape|stripslashes|truncate:"100"|wordwrap:30:"<br />\n"}</a>
                </td>
                <td class="center"><a style="float: left;" class="hint--bottom hint--info"  data-target="#fileupload" rel="tooltip" data-original-title="Ajouter un fichier" data-refresh="true"  data-toggle="modal" data-hint="upload file"  role="button"  href="/ftvedito/uploadfiles?request_id={$requestsitem.identifier}&ftvtype=ftvedito&view=yes">
                        <img class="img-responsive"src="/FO/images/imageB3/upload_icon.jpg" height="20" width="20"/></a>
                    <a class="hint--bottom hint--info"  data-hint="download latest file" rel="tooltip" data-original-title="T&eacute;l&eacute;charger le dernier fichier"  role="button"  href="/ftvedito/downloadftv?request_id={$requestsitem.identifier}&filename={$requestsitem.recent_document}">
                        <img class="img-responsive" src="/FO/images/imageB3/download_icon.jpg" height="20" width="20" /></a>
                </td>
                <td>{$requestsitem.duration}</td>
                <td>{$requestsitem.modify_broadcast}</td>
                <td>{$requestsitem.modify_contains}</td>
                <td>{if $requestsitem.status eq 'pending'} En attente {elseif $requestsitem.status eq 'done'} Trait&eacute;e {elseif $requestsitem.status eq 'closed'}Annul&eacute;e {/if}</td>

                <td>{if $requestsitem.comments eq '-NA-'}  -NA-
                    {else}
                    <a  data-placement="right" rel="tooltip" data-original-title="Cliquez ici pour voir la suite du message" data-target="#showrecentcomment" data-refresh="true"  data-toggle="modal"  role="button"  href="/ftvedito/showrecentcomment?request_id={$requestsitem.identifier}">
                        {$requestsitem.comments|escape|stripslashes|truncate:"30"}</a>
                    {/if}
                </td>
                <td style="padding-left: 50px;"><a  data-placement="right" rel="tooltip" data-original-title="R&eacute;diger un commentaire" data-target="#addcomment" data-refresh="true"  data-toggle="modal"  role="button"  href="/ftvedito/showcomments?request_id={$requestsitem.identifier}">
                        <img class="img-responsive"  src="/FO/images/imageB3/pen.jpg" height="20" width="20" /></a>
                </td>
                <td><a  data-target="#newrequest" data-refresh="true"  data-toggle="modal" rel="tooltip" data-original-title="Dupliquer la demande" role="button"   href="/ftvedito/duplicaterequest?request_id={$requestsitem.identifier}&edit=no"><img class="img-responsive pull-left" src="/FO/images/imageB3/duplicate_icon.jpg" height="20" width="20" /></a>
                    {if $requestsitem.assigned_to eq ''}
                    <a  data-target="#newrequest" data-refresh="true"  data-toggle="modal" rel="tooltip" data-original-title="Modifier la demande" role="button"   href="/ftvedito/duplicaterequest?request_id={$requestsitem.identifier}&edit=yes"><img class="img-responsive pull-left" src="/FO/images/imageB3/edit_icon.png" height="20" width="20" /></a>
                    {/if}
                </td>
            </tr>
            {/foreach}
            {/if}
            <input type="hidden" name="articlecount" id="articlecount" value="{$articlelist|@count}" />
        </table>
    </div>
</section>
<div class="span12">
    <!---Pagination start-->
    <div class="pagination pull-right">
        {include file="Client/pagination.phtml"}
    </div>
</div>
<br>
<br>


<div class="modal fade bs-example-modal-lg" id="newrequest" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="top:35px;position: fixed;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">


        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-md" id="addcomment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="top:35px;position: fixed;">
    <div class="modal-dialog modal-md">
        <div class="modal-content">


        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-md" id="showobjectdemand" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="top:35px;position: fixed;">
    <div class="modal-dialog modal-md">
        <div class="modal-content">


        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-md" id="showrecentcomment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="top:35px;position: fixed;">
    <div class="modal-dialog modal-md">
        <div class="modal-content">


        </div>
    </div>
    <!-- <div class="modal-header">
         <button class="close" data-dismiss="modal" >&times;</button>
         <h3>Edit-place Commentaire(s)</h3>
     </div>
     <div class="modal-body" id="add_comment">
     </div>
     <div class="modal-footer">
     </div>-->
</div>
<div class="modal fade bs-example-modal-md" id="fileupload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="top:35px;position: fixed;">
    <div class="modal-dialog modal-md">
        <div class="modal-content">


        </div>
    </div>
    <!-- <div class="modal-header">
         <button class="close" data-dismiss="modal" >&times;</button>
         <h3>Upload file</h3>
     </div>
     <div class="modal-body" id="file_upload">
     </div>
     <div class="modal-footer">
     </div>-->
</div>
