 {literal}
	<script type="text/javascript" charset="utf-8" src="/FO/script/client/countdown.js"></script>
	<script type="text/javascript" charset="UTF-8">
		
	$("#menu_home").addClass("active");
		
		$(function(){
			//Load more activities Homepage
			var loading = $("#loading");
			var target_page, query, now_showing, total_activities;

			//show loading bar
			function showLoading(){
				loading.slideDown("slow");
			}
			//hide loading bar
			function hideLoading(){
				loading.slideUp("slow");
			};

			/*************************** Recent Activities ********************************/
			//update now showing after every click of show more
			function update_now()
			{
				now_showing = parseInt($("#now_showing").attr("value")) + parseInt($("#show_more").attr("value"));
				$("#now_showing").attr("value", now_showing );
				var total_activities=$("#total_activities").val();
				if(now_showing>=total_activities)
					$("#more").hide();
			}
			
			$("#more").click(function(){
				showLoading();
					
				//define target page and query string
				target_page = "/client/loadmoreactivities";
				query = $("#myForm").serialize();

				//send request and append the response data 
				$.get(target_page, query, function(data){
					if(data=="expired")
						window.location="/index/index";
					else
					{	
						now_showing = parseInt($("#now_showing").attr("value")) + parseInt($("#show_more").attr("value"));
						$("#activities").append(data);
						hideLoading();
						update_now();
					}
					});
			});
			
			/*************************** My quotes ********************************/
			function update_myquotes()
			{
				myquotes_showing = parseInt($("#myquotes_showing").attr("value")) + parseInt($("#myquotes_showing").attr("value"));
				$("#myquotes_showing").attr("value", myquotes_showing );
				var total_myquotes=$("#total_myquotes").val();
				if(myquotes_showing>=total_myquotes)
					$("#moremyquotes").hide();
					
				loadparticipationcount();
			}
			
			$("#moremyquotes").click(function(){
				showLoading();
					
				target_page = "/client/loadmoremyquotes";
				query = $("#myQuotesForm").serialize();

				$.get(target_page, query, function(data){
					if(data=="expired")
						window.location="/index/index";
					else
					{	
						myquotes_showing = parseInt($("#myquotes_showing").attr("value")) + parseInt($("#myquotes_showing").attr("value"));
						$("#myquotes").append(data);
						hideLoading();
						update_myquotes();
					}
					});
			});
			
			/*************************** Ongoing quotes ********************************/
			function update_ongoingquotes()
			{
				ongoingquotes_showing = parseInt($("#ongoingquotes_showing").attr("value")) + parseInt($("#ongoingquotes_showing").attr("value"));
				$("#ongoingquotes_showing").attr("value", ongoingquotes_showing );
				var total_ongoingquotes=$("#total_ongoingquotes").val();
				if(ongoingquotes_showing>=total_ongoingquotes)
					$("#moreongoingquotes").hide();
				loadsubmitcount();	
			}
			
			$("#moreongoingquotes").click(function(){
				showLoading();
					
				target_page = "/client/loadmoremyquotes";
				query = $("#ongoingQuotesForm").serialize();

				$.get(target_page, query, function(data){
					if(data=="expired")
						window.location="/index/index";
					else
					{	
						ongoingquotes_showing = parseInt($("#ongoingquotes_showing").attr("value")) + parseInt($("#ongoingquotes_showing").attr("value"));
						$("#ongoingquotes").append(data);
						hideLoading();
						update_ongoingquotes();
					}
					});
			});
			
			/*************************** Published quotes ********************************/
			function update_publishedquotes()
			{
				publishedquotes_showing = parseInt($("#publishedquotes_showing").attr("value")) + parseInt($("#publishedquotes_showing").attr("value"));
				$("#publishedquotes_showing").attr("value", publishedquotes_showing );
				var total_publishedquotes=$("#total_publishedquotes").val();
				if(publishedquotes_showing>=total_publishedquotes)
					$("#morepublishedquotes").hide();
			}
			
			$("#morepublishedquotes").click(function(){
				showLoading();
					
				target_page = "/client/loadmoremyquotes";
				query = $("#publishedQuotesForm").serialize();

				$.get(target_page, query, function(data){
					if(data=="expired")
						window.location="/index/index";
					else
					{	
						publishedquotes_showing = parseInt($("#publishedquotes_showing").attr("value")) + parseInt($("#publishedquotes_showing").attr("value"));
						$("#publishedquotes").append(data);
						hideLoading();
						update_publishedquotes();
					}
					});
			});
			
			/*************************** Closed quotes ********************************/
			function update_closedquotes()
			{
				closedquotes_showing = parseInt($("#closedquotes_showing").attr("value")) + parseInt($("#closedquotes_showing").attr("value"));
				$("#closedquotes_showing").attr("value", closedquotes_showing );
				var total_closedquotes=$("#total_closedquotes").val();
				if(closedquotes_showing>=total_closedquotes)
					$("#moreclosedquotes").hide();
			}
			
			$("#moreclosedquotes").click(function(){
				showLoading();
					
				target_page = "/client/loadmoremyquotes";
				query = $("#closedQuotesForm").serialize();

				$.get(target_page, query, function(data){
					if(data=="expired")
						window.location="/index/index";
					else
					{	
						closedquotes_showing = parseInt($("#closedquotes_showing").attr("value")) + parseInt($("#closedquotes_showing").attr("value"));
						$("#closedquotes").append(data);
							
						hideLoading();
						update_closedquotes();
					}
					});
			});
			
			//////////show timer participation_expires//////////
			loadparticipationcount();
			loadsubmitcount();		
	});
		
		var cur_date=$("#now").val();
		var js_date=(new Date().getTime())/ 1000;
		var diff_date=Math.floor(js_date-cur_date);
		
	function loadparticipationcount()
	{
		$("[id^='participationtimer_']").each(function(){
				var id=this.id;
				var qid=id.split("_");

				$("#participationtimer_"+qid[1]).countdown({
					timestamp	: $("#participationtime_"+qid[1]).val()-(118), 
					callback	: function(days, hours, minutes, seconds){
						var message = "";

						//add days to hours
						if(days!="0")
							message += days + "j" +"&nbsp;";
							//hours=hours+(days*24);
							
						if(hours!="0")
							message += hours + "h" +"&nbsp;";
						
						if(minutes!="0")
							message += minutes + "mn"; 

						$("#participationtimer_"+qid[1]).html(message);
						if(days==0 && hours==0 && minutes==0 && seconds==0)
							$("#participationtimer_"+qid[1]).html("Termin&eacute;");
						
					}
				});
		});
	}	

	function loadsubmitcount()
	{
		$("[id^='submittimer_']").each(function(){
				var id=this.id;
				var qid=id.split("_");

				$("#submittimer_"+qid[1]).countdown({
					timestamp	: $("#submittime_"+qid[1]).val()-(118), 
					callback	: function(days, hours, minutes, seconds){
						var message = "";

						//add days to hours
						if(days!="0")
							message += days + "j" +"&nbsp;";
							//hours=hours+(days*24);
							
						if(hours!="0")
							message += hours + "h" +"&nbsp;";
						
						if(minutes!="0")
							message += minutes + "mn"; 

						$("#submittimer_"+qid[1]).html(message);
						if(days==0 && hours==0 && minutes==0 && seconds==0)
							$("#submittimer_"+qid[1]).html("Termin&eacute;");
						
					}
				});
		});
	}	
	</script>
	
	<style>
	.pre-scrollable {
		max-height: 200px;
	}
	</style>	
 {/literal}
 
	 <div class="container">
    <h3>Bienvenue dans votre espace client !</h3>
    <p>Votre espace client est votre tableau de bord pour recevoir vos devis, sélectionner votre journaliste et télécharger vos contenus.</p>
    <hr>

    <div class="row">   
		<div class="span9">
			<div class="tabbable tabs-left">
				<ul class="nav nav-tabs" id="homeTab">
					<li {if $smarty.get.type!="new"}class="active"{/if}><a href="#hometab1" data-toggle="tab">Activités récentes</a></li>
					<li {if $smarty.get.type=="new"}class="active"{/if}><a href="#hometab2" data-toggle="tab">Mes devis <span class="badge badge-warning pull-right">{$myquotescount}</span></a></li>
					<li><a href="#hometab3" data-toggle="tab">Mission en cours</a></li>
					<li><a href="#hometab4" data-toggle="tab">Missions validées</a></li>
					<li><a href="#hometab5" data-toggle="tab">Missions fermées</a></li>
				</ul>
				
				<div class="tab-content">
					<!-- -------------------------------------------- Recent Activities ------------------------------------- -->
					<div class="tab-pane fade {if $smarty.get.type!='new'}in active{/if}" id="hometab1">
						<section id="timeline">
							<h4 class="shadowline">Activités récentes</h4>
    						<ul class="media-list" id="activities">
								{foreach from=$activities item=activity}	
									{if $activity.type!="comment" || ($activity.type=="comment" && $activity.active=="yes")} 
									<li class="media {if $activity.usertype=='client'}client{/if} {if $activity.type=='bopublish'}editplace-write{/if}">
										{if $activity.type=="bopublish"}
											<a class="pull-left">
												<img class="media-object" src="/FO/images/ep-feed-logo_90x90.png">
											</a>
										{else}
											<a class="pull-left imgframe" {if $activity.usertype=="contributor"} onclick="loadcontribprofile('{$activity.activity_by}');" data-target="#viewContribProfile" style="cursor:pointer;"{/if} role="button" data-toggle="modal" >
												{if $activity.usertype=="contributor"}
													<img class="media-object" src="{$activity.profilepic}">
												{else}
													<div class="media-object container-logo">
														<img class="max" src="{$activity.profilepic}">
													</div>
												{/if}
											</a>
										{/if}
										<div class="media-body">
											<h4 class="media-heading">
											<a  role="button" data-toggle="modal" {if $activity.usertype=="contributor"} onclick="loadcontribprofile('{$activity.activity_by}');" data-target="#viewContribProfile" style="cursor:pointer;"{/if}>
												{if $activity.type=="bopublish"}
													Edit-place
												{else}
													{if $activity.first_name!=""}
														{$activity.first_name}
													{else}
														{$activity.email}
													{/if}
												{/if}
											</a>
											</h4>
												{if $activity.type=="download"}
													a t&eacute;l&eacute;charg&eacute; les articles de la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="invoice"}
													a g&eacute;n&eacute;r&eacute; une facture sur la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="validate"}
													a valid&eacute; la livraison de "{$activity.contribname}" sur la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="comment"}
													a comment&eacute; la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="extend"}
													a accord&eacute; plus de temps a "{$activity.contribname}" sur la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="resubmit"}
													a demand&eacute; une reprise a "{$activity.contribname}" sur la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="refuse"}
													a refus&eacute; la livraison de "{$activity.contribname}" sur la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="sentarticle"}
													a envoy&eacute; le ou les articles de la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="quote"}
													a propos&eacute; un tarif pour la mission {if $activity.premium_option=="0"}libert&eacute;{else}premium{/if} "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{elseif $activity.type=="pollquote"}
													a propos&eacute; un tarif pour le devis premium "<a class="btn-link" href="/client/devispremium?id={$activity.pollid}">{$activity.polltitle}</a>"
												{elseif $activity.type=="bopublish"} 
													a envoy&eacute; le ou les articles de la mission premium "<a class="btn-link" href="/client/quotes?id={$activity.article_id}">{$activity.atitle}</a>"
												{/if}
											<p class="muted">{$activity.time}</p>
											{if $activity.type=="comment"}
											<div class="media comment">
												<i class="icon-comment"></i>
													{$activity.comments}
												<p><a class="btn-link" href="/client/quotes?id={$activity.article_id}">Tout lire</a></p>
											</div>
											{/if} 
										</div>
									</li>
									{/if}
								{/foreach}
							</ul>
							{if $activitiescount>10}	
								<p class="btn btn-block btn-mini" id="more">Charger plus d'historiques</p>
							{/if}
							<form id="myForm"> 
								<input type="hidden" name="now_showing" id="now_showing" value="{$now_showing}" />
								<input type="hidden" name="show_more" id="show_more" value="{$show_more}" />
								<input type="hidden" name="total_activities" id="total_activities" value="{$total_activities}" />
								<input type="hidden" name="quotetype" id="quotetype" value="all" />
							</form>
						</section>
					</div>
					
					<!-- -------------------------------------------- My devis ------------------------------------- -->
					<div class="tab-pane fade {if $smarty.get.type=='new'}in active{/if}" id="hometab2">
						<section>
							<h4>Mes devis</h4>
								<table class="table table-hover">
									<thead>
										<tr>
											<td class="span2">Décompte</td>
											<td>Projet</td>
										</tr>
									</thead>
									<tbody id="myquotes">
										{if $myquotes|@count>0}
											{foreach from=$myquotes item=quote}
												<tr>
													{if $quote.participation_expires==0}
														<td>En attente</td>
													{else}
														<td class="countdown" id="participationtimer_{$quote.id}"></td>
													{/if}
													<td><a href="/client/quotes?id={$quote.id}">{$quote.title}</a></td> 
												</tr>
												<input type="hidden" name="participationtime_{$quote.id}" id="participationtime_{$quote.id}" value="{$quote.participation_expires}" />
											{/foreach}
										{/if}	
									</tbody>
								</table>
								{if $myquotescount>10}	
									<p class="btn btn-block btn-mini" id="moremyquotes">Charger plus devis</p>
								{/if}
								<form id="myQuotesForm"> 
									<input type="hidden" name="myquotes_showing" id="myquotes_showing" value="{$myquotes_showing}" />
									<input type="hidden" name="myquotes_more" id="myquotes_more" value="{$myquotes_more}" />
									<input type="hidden" name="total_myquotes" id="total_myquotes" value="{$total_myquotes}" />
									<input type="hidden" name="quotetype" id="quotetype" value="new" />
									<input type="hidden" name="now" id="now" value="{$smarty.now}" />
								</form>
						</section>
					</div>
					
					<!-- -------------------------------------------- Ongoing devis ------------------------------------- -->
				   <div class="tab-pane fade" id="hometab3">
						<section id="ongoing-mission">
							<h4>Missions en cours</h4>
							<table class="table table-hover">
								<thead>
									<tr>
										<td class="span2">Livraison</td>
										<td>Mission</td>
									</tr>
								</thead>
								<tbody id="ongoingquotes">
									{if $ongoingquotes|@count>0}
										{foreach from=$ongoingquotes item=quote}
											<tr>
												<td class="countdown" id="submittimer_{$quote.id}"></td>
												<td><a href="/client/quotes?id={$quote.id}">{$quote.title}</a></td> 
											</tr>
											<input type="hidden" name="submittime_{$quote.id}" id="submittime_{$quote.id}" value="{$quote.article_submit_expires}" />
										{/foreach}
									{/if}	
								</tbody>
							</table>
							{if $ongoingquotescount>10}	
								<p class="btn btn-block btn-mini" id="moreongoingquotes">Charger plus devis</p>
							{/if}
							<form id="ongoingQuotesForm"> 
								<input type="hidden" name="ongoingquotes_showing" id="ongoingquotes_showing" value="{$ongoingquotes_showing}" />
								<input type="hidden" name="ongoingquotes_more" id="ongoingquotes_more" value="{$ongoingquotes_more}" />
								<input type="hidden" name="total_ongoingquotes" id="total_ongoingquotes" value="{$total_ongoingquotes}" />
								<input type="hidden" name="quotetype" id="quotetype" value="ongoing" />
							</form>
					 </section>
					</div>    

					<!-- -------------------------------------------- Published devis ------------------------------------- -->
					<div class="tab-pane fade" id="hometab4">
						<section id="ok-mission">
							<h4>Missions validées</h4>
							<table class="table table-hover">
								<tbody id="publishedquotes">
									{if $publishedquotes|@count>0}
										{foreach from=$publishedquotes item=pquote}
											<tr>
												<td><a href="/client/quotes?id={$pquote.id}">{$pquote.title}</a></td>
												<td><a class="btn btn-small" href="/client/downloadarticlezip?id={$pquote.id}">Télécharger</a></td>
											</tr>
										{/foreach}
									{/if}
								</tbody>
							</table>
							{if $publishedquotescount>10}	
								<p class="btn btn-block btn-mini" id="morepublishedquotes">Charger plus devis</p>
							{/if}
							<form id="publishedQuotesForm"> 
								<input type="hidden" name="publishedquotes_showing" id="publishedquotes_showing" value="{$publishedquotes_showing}" />
								<input type="hidden" name="publishedquotes_more" id="publishedquotes_more" value="{$publishedquotes_more}" />
								<input type="hidden" name="total_publishedquotes" id="total_publishedquotes" value="{$total_publishedquotes}" />
								<input type="hidden" name="quotetype" id="quotetype" value="published" />
							</form>
						 </section>
					</div>   
					
					<!-- -------------------------------------------- Closed devis ------------------------------------- -->
					<div class="tab-pane fade" id="hometab5">
						<section id="closed-mission">
							<h4>Missions fermées</h4>
							<table class="table table-hover">
								<tbody id="closedquotes">
									{if $closedquotes|@count>0}
										{foreach from=$closedquotes item=cquote}
											<tr>
												<td><a href="/client/quotes?id={$cquote.id}">{$cquote.title}</a></td>
											</tr>
										{/foreach}
									{/if}	
								</tbody>
							</table>
							{if $closeddquotescount>10}	
								<p class="btn btn-block btn-mini" id="moreclosedquotes">Charger plus devis</p>
							{/if}
							<form id="closedQuotesForm"> 
								<input type="hidden" name="closedquotes_showing" id="closedquotes_showing" value="{$closedquotes_showing}" />
								<input type="hidden" name="closedquotes_more" id="closedquotes_more" value="{$closedquotes_more}" />
								<input type="hidden" name="total_closedquotes" id="total_closedquotes" value="{$total_closedquotes}" />
								<input type="hidden" name="quotetype" id="quotetype" value="closed" />
							</form>
						</section>
					</div>       
    
    </div>
    </div>
</div>
    
    <div class="span3">
		<!--  right column  -->
		<aside>
			<div class="aside-bg">
				<div id="garantee" class="mod">
					<h4>Vos garanties</h4>
					<dl>
						<dt><span class="umbrella"></span>edit-place est votre médiateur</dt>
						<dd>En cas de contestation (délai de livraison, reprise d’articles, remboursement...)</dd>
						<dt><span class="locked"></span>Paiement sécurisé</dt>
						<dd>Notre solution de paiement en ligne vous garantit une transaction en toute tranquillité</dd>
					</dl>
				</div>
			</div>
			
			{if $polllist|@count>0}
				<div class="aside-bg">
				<div id="quote-ongoing" class="aside-block"> 
					<h4>Devis premium en cours</h4>
					<ul class="nav nav-tabs nav-stacked {if $polllist|@count>6}pre-scrollable{/if}">
						
							{foreach from=$polllist item=poll}
								<li>
									{if $poll.title|@strlen > 30}
										<a href="/client/devispremium?id={$poll.id}" rel="tooltip" data-original-title="{$poll.title}" data-placement="left">
											<span class="badge pull-right">{$poll.participation}</span>
										{$poll.title|truncate:30:"...":true}
										</a>
									{else}
										<a href="/client/devispremium?id={$poll.id}" >
											<span class="badge pull-right">{$poll.participation}</span>
										{$poll.title}</a>
									{/if}	
									
								</li>
							{/foreach}
						<!--<li><b>Pas de devis en cours</b></li>-->
					</ul>	
					</div>
				</div>
			{/if}
		</aside>  
    </div>
    </div>
    </div>

	{if $writerscount>0}
	<section id="known-users">
		<div class="container">
			<div class="row">
				<h3 class="sectiondivider pull-center"><span>Ils ont d&eacute;j&agrave; collabor&eacute; avec vous !</span></h3>
				
				{foreach from=$writers item=writer}
					<div class="span3">
						<div class="editor-container">
							<a  class="imgframe-large" onclick="loadcontribprofile('{$writer.user_id}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">
								<img src="{$writer.profileimage}">
							</a>
							<p class="editor-name"><a onclick="loadcontribprofile('{$writer.user_id}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">{$writer.name|ucfirst}</a></p>
						</div>
					</div>
				{/foreach}
			</div>
		</div>
	</section>
	{/if}	
	
<!-- ***** Modal collections -->

<!-- contrib profile -->
<div id="viewContribProfile" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">Profil du r&eacute;dacteur</h3>
	</div>
	<div class="modal-body">
		<div id="userprofile">
	
		</div>
	</div>
</div>
   



