{literal}
<script type="text/javascript">
function validate_form()
{
	document.pay_form.submit();
}
</script>
{/literal}
		<body onLoad="validate_form()" >
			<form action=https://epage.payandshop.com/epage.cgi method=post onSubmit="return validate_payments()" name="pay_form" id="pay_form">
					<input type=hidden name="MERCHANT_ID" value="{$merchantid}">
					<input type=hidden name="ORDER_ID" value="{$orderid}">
					<input type=hidden name="CURRENCY" value="{$curr}">
					<input type=hidden name="AMOUNT" value="{$amount}">
					<input type=hidden name="TIMESTAMP" value="{$timestamp}">
					<input type=hidden name="MD5HASH" value="{$md5hash}">
					<input type="hidden" name="SHA1HASH" value="{$sha_hash}">
					<input type=hidden name="AUTO_SETTLE_FLAG" value="1">
					<input type=hidden value="Proceed to secure server">
					
					<!-- vars for Article payment----->
					<input type=hidden name="client" value="{$client}">
					<input type=hidden name="article" value="{$article}">
					<input type=hidden name="art_amount" value="{$art_amount}">
					<input type=hidden name="delivery" value="{$delivery}">
					
					<div align="center" style="padding-bottom:250px;"> 
					<br>
					<img src="/FO/images/loading-b.gif" />
					<br>
					<br>
						<strong>Vous allez &ecirc;tre redirig&eacute; vers notre prestataire de paiement s&eacute;curis&eacute;.</strong>
					</div>
			</form>
		</body>