{literal}
	<script language="javascript">

	(function($,W,D)
	{ 
		var JQUERY4U = {};

		JQUERY4U.UTIL =
		{
			setupFormValidation: function()
			{
				//form validation rules1
				$("#quotes1form").validate({
					//onkeyup: true,
					//onfocusout: false,
					highlight: function(element) {
						$(element).closest('span').addClass("f_error");
					},
					unhighlight: function(element) {
						$(element).closest('span').removeClass("f_error");
					},
				
					rules: {
						con_type:  "required",
						'quotetype[]': "required", 
						textforother:{
							required: function(element){
									return $("input[id='quotetype-other']:checked").val()=="other";
								}
							},
						objectives: "required", 	
						
					},
					messages: {
						con_type: "Merci d'effectuer un choix",
						'quotetype[]': "Choisissez le type de devis",
						textforother:"Merci de pr&eacute;ciser",
						objectives:"Merci de pr&eacute;ciser"
					},
					debug:true,
					submitHandler: function(form) { 
					var errornum=0;
					var langerr=0;
					
						if($("input[name='dontknowcheck']:checked").val()!="1")
						{
							$("[id^=articlenum_]" ).each(function(z) {
							var idname="#"+this.id;
							var idtype=this.id.split("_");
								if($(idname).val()=="" || $(idname).val()<0)
									errornum++;
							});
						}
						//Translation language
						if($("input[name='con_type']:checked").val()=="translation")	
						{
							if($("#translation_from").val()==$("#translation_to").val())
								langerr++;
						}
						
						if(errornum>0 || langerr>0)
						{
							if(errornum>0)
								$("#quotenum").html("Ins&eacute;rer le nombre d'articles");  
							else
								$("#quotenum").html("");  
								
							if(langerr>0)
								$("#translang").html("Les langues source et de destination doivent &ecirc;tre diff&eacute;rentes");  
							else
								$("#translang").html("");  
						}
						else
						{
							$("#quotenum").html("");
							$("#translang").html("");
							//if($("#profilecomplete").val()=="yes")
							//{
								var formData = $('#quotes1form').serialize();
								$.ajax({
									type : 'POST', 
									url : '/client/confirmpremium', 
									data : formData,
									   
									success : function(r)
								   {
										$("#confirm-premium").addClass("in");
										$("#confirm-premium").show();
										$("#fadeblock").addClass("modal-backdrop fade in");
										$("#fadeblock").show();
										$('#confirmcontent').html(r);
										$('body').addClass("modal-open");
										$('html,body').animate({scrollTop:100}, 500);
								   }
								});
							//}
							//else
								//form.submit();
						}
					}
				});
			} 
		}

		//when the dom has loaded setup form validation rules
		$(D).ready(function($) {
			JQUERY4U.UTIL.setupFormValidation(); 
		});

	})(jQuery, window, document);
			
		function addarticleblock(typ)
		{ 
			var values = $('input:checkbox:checked.group1').map(function () {
				  return this.value;
				}).get(); 
			var num=values.length;	
				var placehtext="";
				if(typ=="seo")
					placehtext="Nombre d'articles SEO souhaités";
				else if(typ=="desc")
					placehtext="Nombre de descriptifs produit souhaités";
				else if(typ=="blog")
					placehtext="Nombre d'articles de blog souhaités";
				else if(typ=="news")
					placehtext="Nombre de news souhaitées";
				else if(typ=="guide")
					placehtext="Nombre de guides souhaités";
				else if(typ=="other")
					placehtext="Nombre d'articles souhaités";
					
				var clonedqu=$("#checkblock");
				$("#articleblock_0").clone().attr('id', 'articleblock_'+(typ) ).insertBefore(clonedqu);	
				$('#articleblock_'+typ).show();	
				
					$('#articleblock_'+typ+' input[id="articlenum"]').attr('name','articlenum['+(typ)+']');	
					$('#articleblock_'+typ+' input[id="articlenum"]').attr('placeholder',placehtext);	
				$('#articleblock_'+typ+' input[id="articlenum"]').attr('id','articlenum_'+typ);	
					$('#articleblock_'+typ+' select[id="frequency"]').attr('name','frequency['+(typ)+']');	
				$('#articleblock_'+typ+' select[id="frequency"]').attr('id','frequency_'+typ);	
				if($("input[name='dontknowcheck']:checked").val()=="1")
				{
					$('#articleblock_'+typ+' input[id=articlenum_'+typ+']').attr('disabled',true);	
					$('#articleblock_'+typ+' select[id=frequency_'+typ+']').attr('disabled',true);	  
				}
		}
		
		function removearticleblock(typ)
		{
			var values = $('input:checkbox:checked.group1').map(function () {
				  return this.value;
				}).get(); 
			var num=values.length;	  
			$('#articleblock_'+typ).remove();	
		}
				
		function switchcontenttype(wlang)
		{
			if($("input[name='con_type']:checked").val()=="writing")
			{
			if(wlang=="fr")
				$('form#quotes1form').get(0).setAttribute('action','/client/quotes2liberte'); 
			else
				$('form#quotes1form').get(0).setAttribute('action','/client/quotes-2'); 
			}
		}
		
		function dismissmodal()
		{
			$("#confirm-premium").removeClass("in");
			$("#confirm-premium").hide();
			$("#fadeblock").removeClass("modal-backdrop fade in");
			$("#fadeblock").hide();
			$('body').removeClass("modal-open");
		}
		
		$(window).load(function(){		
			var articleid=$("#article").val();
			
			if(articleid!="")
			{
				$('#duplicatemission').modal({
					show: true
				});
			}
		});	
	</script>
	
	<style>
		.error { color: red !important; font-size:16px !important;font-weight:bold !important;}
		.f_error {  border-color: rgb(185, 74, 72); color: rgb(185, 74, 72);}
	</style>
{/literal}


<section class="quoteform" id="step1">

	<form action="/client/quotes-2" method="POST" id="quotes1form" name="quotes1form" novalidate>
		<input type="hidden" name="article" id="article" value="{$smarty.get.article}" />
		<div class="container padding">  
			{if $usertype neq 'contributor'}
			<div class="center-block">
				<h2>Définissez vos besoins  pour obtenir le meilleur tarif</h2>
			</div>

			<div class="row wanted-product">
				<div class="col-xs-6 col-md-6 dashit">   
					<div class="center-block">
						<input type="radio" name="con_type" id="writing" value="writing" {if $con_type=="writing"}checked{/if}/> 
						<label for="writing">Je veux du <strong>contenu</strong></label>
						<select class="selectpicker" name="writing_lang" id="writing_lang">
							{foreach from=$lang_array item=lang_item key=lang_key}
								<option value="{$lang_key}" {if $writing_lang==$lang_key}selected{/if}>{$lang_item}</option>
							{/foreach}
						</select>
					</div>
				</div>
				<div class="col-xs-6 col-md-6">
					<div class="center-block">
						<input type="radio" name="con_type" id="translation" value="translation" {if $con_type=="translation"}checked{/if}/> 
						<label for="translation"> Je veux qu'on <strong>traduise</strong> mon contenu</label>
						<select class="selectpicker" name="translation_from" id="translation_from">
							{foreach from=$lang_array item=lang_item key=lang_key}
								<option value="{$lang_key}" {if $translation_from==$lang_key}selected{/if}>{$lang_item}</option>
							{/foreach}
						</select>
						<span class="glyphicon glyphicon-arrow-right"></span>
						<select class="selectpicker" name="translation_to" id="translation_to">
							{foreach from=$lang_array item=lang_item key=lang_key}
								<option value="{$lang_key}" {if $translation_to==$lang_key}selected{/if}>{$lang_item}</option>
							{/foreach}
						</select>
					</div>
					<div class="error" id="translang"></div> 
				</div>
				<label class="error" for="con_type" style="padding-left:182px" generated="true"></label>
			</div>     

			<div id="ctype" class="formfocus">   
				<fieldset class="dashit">  
					<legend class="form-group">Mon type de contenu <small>Cochez parmi ces types, ceux à créer ou traduire</small></legend>
						<div class="ctype"> 
							<div class="col-xs-6 col-md-4">
								<div class="center-block">
									<label for="ctype-seo">
										<div class="ctype-block">
											<img src="/FO/images/imageB3/ctype-seo.png" width="50" height="50"><br>Article seo
											<span class="wcount">130 mots</span>
											<input type="checkbox" name="quotetype[]" id="quotetype-seo" value="seo" class="group1" {if in_array('seo',$quotetype)}checked{/if}/>
										</div>
									</label>
								</div>
							</div>  

							<div class="col-xs-6 col-md-4">
								<div class="center-block">
									<label for="ctype-desc">
										<div class="ctype-block">
											<img src="/FO/images/imageB3/ctype-desc.png" width="50" height="50"><br>
											Descriptifs produit
											<span class="wcount">80 mots</span>
											<input type="checkbox" name="quotetype[]" id="quotetype-desc" value="desc" class="group1" {if in_array('desc',$quotetype)}checked{/if}/>
										</div>
									</label>
								</div>
							</div>

							<div class="col-xs-6 col-md-4">
								<div class="center-block">
									<label for="ctype-blog">
										<div class="ctype-block">
											<img src="/FO/images/imageB3/ctype-blog.png" width="50" height="50"><br>
											Article de blog
											<span class="wcount">500 mots</span>
											<input type="checkbox" name="quotetype[]" id="quotetype-blog" value="blog" class="group1" {if in_array('blog',$quotetype)}checked{/if}/>
										</div>
									</label>
								</div>
							</div>

							<div class="col-xs-6 col-md-4">
								<div class="center-block">
									<label for="ctype-news">
										<div class="ctype-block">
											<img src="/FO/images/imageB3/ctype-news.png" width="50" height="50"><br>
											News
											<span class="wcount">200 mots</span>
											<input type="checkbox" name="quotetype[]" id="quotetype-news" value="news" class="group1" {if in_array('news',$quotetype)}checked{/if} />
										</div>
									</label>
								</div>
							</div>

							<div class="col-xs-6 col-md-4">
								<div class="center-block">
									<label for="ctype-guide">
										<div class="ctype-block">
											<img src="/FO/images/imageB3/ctype-guide.png" width="50" height="50"><br>
											Guide
											<span class="wcount">1000 mots</span>
											<input type="checkbox" name="quotetype[]" id="quotetype-guide" value="guide" class="group1" {if in_array('guide',$quotetype)}checked{/if}/>
										</div>
									</label>
								</div>
							</div>

							<div class="col-xs-6 col-md-4">
								<div class="center-block">
									<label for="ctype-other">
										<div class="ctype-block">
											<img src="/FO/images/imageB3/ctype-other.png" width="50" height="50"><br>
											Autre
											<span class="wcount">-</span>
											<input type="checkbox" name="quotetype[]" id="quotetype-other" value="other" class="group1" {if in_array('other',$quotetype)}checked{/if}/>
										</div>
									</label>
									<div id="textforother-block" {if in_array('other',$quotetype)}class="in showcollapse"{else}class="collapse"{/if}>
										<input type="text" class="form-control" id="textforother" name="textforother" placeholder="Veuillez préciser..." value="{$textforother}">
									</div>
								</div>
							</div>
							<label class="error" for="quotetype[]" generated="true"></label>
						</div>   
				</fieldset>

				<fieldset class="dashit">
					<legend class="form-group">Nombre d'articles souhaités</legend>
					<div class="form-group" id="articleblock_0" style="display:none;"> 
						<div class="row"> 
							<div class="col-md-5">  
								<input name="articlenum" id="articlenum" placeholder="Entrer un nombre d'articles" min="1" class="form-control input-md" type="number">
							</div>
							<div class="col-md-4">
								<select id="frequency" name="frequency" class="form-control">
									<option value="once">En 1 seule fois</option>
									<option value="day">Par jour</option>
									<option value="week">Par semaine</option>
									<option value="month">Par mois</option>
								</select>
							</div>
						</div>
					</div>
					{if $quotetype|@count gt 0}
						{section name=art_loop loop=$quotetype|@count} 
							{assign var=sc_index value=$quotetype[$smarty.section.art_loop.index]}
							<div class="form-group" id="articleblock_{$quotetype[$smarty.section.art_loop.index]}">   
								<div class="row">  
									<div class="col-md-5">  
										<input name="articlenum[{$quotetype[$smarty.section.art_loop.index]}]" min="1" id="articlenum_{$quotetype[$smarty.section.art_loop.index]}" placeholder="Entrer un nombre d'articles" class="form-control input-md" type="number" value="{$articlenum[$sc_index]}" {if $dontknowcheck==1}disabled{/if}>
									</div>
									<div class="col-md-4">
										<select id="frequency_{$quotetype[$smarty.section.art_loop.index]}" name="frequency[{$quotetype[$smarty.section.art_loop.index]}]" class="form-control" {if $dontknowcheck==1}disabled{/if}>
											<option value="once" {if $frequency[$sc_index]=="once"}selected{/if}>En une seule fois</option>
											<option value="day" {if $frequency[$sc_index]=="day"}selected{/if}>Par jour</option>
											<option value="week" {if $frequency[$sc_index]=="week"}selected{/if}>Par semaine</option>
											<option value="month" {if $frequency[$sc_index]=="month"}selected{/if}>Par mois</option>
										</select>
									</div>
								</div>
							</div>
							
						{/section}
					{/if}
					<div class="form-group" id="checkblock">
						<div class="checkbox">
							<label for="checkboxes-0">
								<input name="dontknowcheck" id="dontknowcheck" value="1" type="checkbox" {if $dontknowcheck==1}checked{/if}>
								Je ne sais pas, je cherche juste un bon rédacteur pour mon site
							</label>
						</div>
					</div>
					<div class="error" id="quotenum"></div>
				</fieldset>

				<fieldset class="dashit">
					<legend class="form-group">Mes attentes</legend>

					<div class="form-group">
						<div class="radio">
							<label for="objectives_1">
								<input name="objectives" id="objectives_1" value="premium" type="radio" {if $objectives=="premium"}checked{/if}/>
								Je veux &ecirc;tre recontact&eacute; par Edit-place pour parler de mon projet avant publication
							</label>
						</div>
						<div class="radio">
							<label for="objectives_2">
								<input name="objectives" id="objectives_2" value="liberte" type="radio" {if $objectives=="liberte"}checked{/if}/>
								Je veux directement entrer en contact avec les r&eacute;dacteurs/traducteurs d'Edit-place
							</label>
						</div>
						{if $clientidentifier!=""}
						<div class="radio">
							<label for="objectives_3">
								<input name="objectives" id="objectives_3" value="liberteprivate" type="radio" {if $objectives=="liberteprivate"}checked{/if}/>
								Je veux proposer un projet &agrave; un de mes r&eacute;dacteurs/traducteurs favoris
							</label>
						</div>
						{/if}
						<div class="radio">
							<label for="objectives_4">
								<input name="objectives" id="objectives_4" value="dontknow" type="radio" {if $objectives=="dontknow"}checked{/if}/>
								Je ne sais pas
							</label> 
						</div>
						<label class="error" for="objectives" generated="true"></label>
					</div>
				</fieldset>  
			</div>
			
			<hr>    

			<div class="center-block">
				<button class="btn btn-lg" type="button" onClick="window.location.href='/client/quotes-1?new=1';" aria-hidden="true"><strong>Annuler</strong></button>
				<button name="submitform" class="btn btn-primary btn-lg">Valider <span class="glyphicon glyphicon-chevron-right"></span></button>
			</div>
			<input type="hidden" name="clientid" id="clientid" value="{$clientidentifier}"/>
			<!--<input type="hidden" name="profilecomplete" id="profilecomplete" value="{$profilecomplete}"/>-->
			<input type="hidden" name="clientcategory" id="clientcategory" value="{$clientcategory}"/>
			{else}
				<div align="center"><strong>This page is available only for Clients.</strong></div>
			{/if}
		</div>
	</form>    
</section>


<div id="confirm-premium" class="modal fade ep-quote-price" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content" id="confirmcontent">
		</div>
	</div>	
</div>
<div id="fadeblock"></div>

<!--- Relancer une mission--->
<div id="duplicatemission" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 id="myModalLabel">Relancer une mission</h3>
			</div>
			<form method="POST" class="form-horizontal" name="duplicatemissionform" id="duplicatemissionform" action="/client/quotes-1" style="margin:0px 0px;" >
				<div class="modal-body">
					<div>
						Nous avons pr&eacute;-rempli votre formulaire de demande de devis avec les informations de votre pr&eacute;c&eacute;dente mission.<br><br>
						Vous pouvez modifier chaque champs
						<br><br>
					</div>
					<input type="hidden" name="editliberte" id="editliberte" value="{$smarty.get.article}"/>
					<input type="hidden" name="createprivate" id="createprivate" value="{$smarty.get.private}"/>
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true"><strong>Annuler</strong></button>
					<button class="btn btn-primary" type="submit" name="duplicate_mission" id="duplicate_mission" value="duplicate_mission">Valider</button>  
				</div>
			</form>
		</div>
	</div>
</div>


