<section id="status">
	<div class="row-fluid">
		<!-- col 1 -->
		<div class="profilehead-mod">
			<div class="span2">
				<div class="editor-container">
					<a class="imgframe-large" href="#">
						<img src="{$contribprofile[0].profilepic}" alt="{$contribprofile[0].first_name|ucfirst} {$contribprofile[0].last_name|ucfirst}">
					</a>
				</div>
			</div>
			<div class="span9 profile-name" style="">
				<h3>{$contribprofile[0].name}</h3>
				<p class="" style="">{$contribprofile[0].age} ans  <span class="muted"> &bull; </span>  {$contribprofile[0].catstr}  <span class="muted"> &bull; </span>  {$contribprofile[0].langstr}</p>
				<blockquote>
					<i class="icon-leaf"></i> {$contribprofile[0].self_details|stripslashes}
				</blockquote>
			</div>
			<!--<div class="span3 stat contact-info" style="border:none;padding-left:0px;">
				<h4><i class="icon-user"></i> Coordonn&eacute;es</h4>
				<address>
					+{$contribprofile[0].phone_number}<br>
					<a href="mailto:{$contribprofile[0].email}">{$contribprofile[0].email}</a>
				</address>
				<a href="/client/compose-mail?clientid={$contribprofile[0].identifier}" class="btn btn-small">contacter {$contribprofile[0].first_name|ucfirst}</a>
			</div>-->
		</div>
	</div>
</section>
<!-- end, contributor status --> 

<div class="row-fluid"> 
	<div class="span8">
		<section id="skills">
			<div class="mod">
				<h4>Langues</h4>
				{assign var="language" value=$contribprofile[0].language}
				<strong>{$language_array.$language}</strong> (langue maternelle)
				{foreach from=$langpercent item=more key=lang}
					<div class="skillstat row-fluid">	
						<div class="span6">
							<p><strong>{$language_array.$lang}</strong>  {$more}%</p>
							<div class="progress">
								<div class="bar" style="width: {$more}%"></div>
							</div>
							<span class="pull-left legend muted">D&eacute;butant</span> <span class="pull-right legend muted">Bilingue</span>
						</div>
					</div>
				{/foreach}	
			</div>

			<div class="mod">
				<h4>Domaines de comp&eacute;tences</h4>
				{foreach from=$contribprofile[0].cats item=cat}
					{if $catpercent.$cat!=""}
					<div class="skillstat row-fluid">
						<div class="span6">
							<p><strong data-original-title="Seo / marketing internet" rel="tooltip">{$category_array.$cat}</strong>  {$catpercent.$cat}%</p>
							<div class="progress">
							<div class="bar" style="width: {$catpercent.$cat}%"></div>
							</div>
							<span class="pull-left legend muted">D&eacute;butant</span> <span class="pull-right legend muted">Expert</span>
						</div>
					</div>
					{/if}
				{/foreach}	
			</div>
			
			{if $exp_details|@count>0}
			<div class="mod">
				<h4>Exp&egrave;riences professionnelles</h4>
				<dl>
					{foreach from=$exp_details item=exp}
						<dt>{$exp.title}</dt>
						<dd class="company">{$exp.institute}</dd>
						<dd class="muted">
							Type de contrat : {$exp.contract}
						</dd>
						<dd class="muted">
							<time> {$exp.from_month|ucfirst} {$exp.from_year}</time> - <time>{if $exp.to_year!="0"}{$exp.to_month|ucfirst} {$exp.to_year}{else}Actuel{/if}</time>
						</dd>
					{/foreach}
				</dl>
			</div>
			{/if}
			
			{if $education_details|@count>0}
			<div class="mod">
				<h4>Formations</h4>
				<dl>
					{foreach from=$education_details item=edu}
						<dt>{$edu.title}</dt>
						<dd class="company">{$edu.institute}</dd>
						<dd class="muted">
							<time> {$edu.from_month|ucfirst} {$edu.from_year}</time> - <time>{if $edu.to_year!="0"}{$edu.to_month|ucfirst} {$edu.to_year}{else}Actuel{/if}</time>
						</dd>
					{/foreach}
				</dl>
			</div>
			{/if}
		</section>
	</div>

	
	{if $contribprofile[0].clientlogo|@count>0}
	<div class="span4">
		<!--  right column  -->
		<aside>
			<div class="aside-bg">
				<div class="aside-block" id="we-trust">
					<h4>Publications</h4>
					<ul class="unstyled">
						{foreach from=$contribprofile[0].clientlogo item=clogo key=keylogo}
							<li><img src="{$clogo}" rel="tooltip" data-original-title="{$keylogo|utf8_decode}" data-placement="left"></li>
						{/foreach}
					</ul>
				</div>
			</div>
		</aside>  
	</div>
	{/if}
	
</div>

<a class="pull-right btn btn-small disabled anchor-top scroll" href="#brand"><i class="icon-arrow-up"></i></a> 
       
{literal}
<script>
	$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
		return false;		
	}); 
	$("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();
</script>
{/literal}
