{literal}
<script type="text/javascript">

 $(document).ready(function() {	
	
	$("#menu_mailbox").addClass("active");
	$("#menu_compose").addClass("disabled");
	
	// call write email function
	$('#mail_message').wysihtml5({locale: "fr-FR"});
	//compose email validation
		$("#send_message").click(function(){
			var error=0,top=200;
			var sendto=$("#sendto");
			var mail_object=$("#mail_object");
			var object=mail_object.val();
			var	mail_message=$("#mail_message");
			var message=mail_message.val();
				message = message.replace(/(<([^>]+)>)/ig,"");
				message = message.replace(/&nbsp;/gi,"");
			if(sendto.length)
			{
				if(sendto.val())
				{
					sendto.removeClass("error");
					$("#sendto_error").html('');
				}	
				else
				{
					sendto.addClass("error");
					$("#sendto_error").html('send to obligator');
					error+=1;
				}
			}
			if(mail_object.length)
			{	
				if($.trim(object).length <1 || object=='')
				{
					mail_object.addClass("error");
					$("#mail_object_error").html('Objet obligatoire');
					error+=1;
				}	
				else
				{
					$("#mail_object_error").html('');
					mail_object.removeClass("error");
				}
			}	
			if($.trim(message).length <1 || message=="")
			{
				mail_message.addClass("error");
				$("#mail_message_error").html('Votre message obligatoire ');
				error++;
			}
			else
			{
				mail_message.removeClass("error");
				$("#mail_message_error").html('');
			}	
			if(error>0)
			{
				if(sendto.length)
				{
					$('html, body').animate( { scrollTop: top }, 'slow' );
				}	
				return false;
			}	
			else
				return true;

		});	
	
});
</script>
{/literal}	
	
<div class="container">
	<section id="maibox">
		<form  method="post" action="/client/send-reply" enctype="multipart/form-data">
			<div class="row">    
				<div class="span12">
					<h1>Messagerie priv&eacute;e</h1>
					<hr>
				</div>

				{include file="Client/pattern/mail_leftmenu.phtml"}

				<div class="span9">
					<section id="emailView">
						<div class="mod">
							{foreach item=message from=$viewMessage}
								<div class="btn-toolbar">
									<div class="btn-group">
										<a href="#goback" class="backnow btn btn-small"><i class="icon-arrow-left"></i></a>
									</div>
									<div class="btn-group pull-right">
										<a href="#print" class="btn btn-small printnow"><i class="icon-print"></i> Imprimer</a>
										<a href="/client/classify?ticket={$message.ticket_id}" onclick="return confirm('Voulez-vous classer ce message ?');" class="btn btn-small"><i class="icon-folder-close"></i> Classer</a>
									</div>
								</div>
								<div class="row-fluid">
									<div id="print_mail">
										<h3>{$message.Subject}</h3>
										<div class="status clearfix">
											<div class="span10"><strong>De: {$message.sendername}</strong> <span class="date">, 
											{if $smarty.now|date_format:"%d/%m/%Y" eq $message.receivedDate|date_format:"%d/%m/%Y"}
												{$message.receivedDate|date_format:"%Hh%M"}
											{elseif $smarty.now|date_format:"%Y" eq $message.receivedDate|date_format:"%Y"}
												{$message.receivedDate|date_format:"%d %b %R"}
											{else}
												{$message.receivedDate|date_format:"%d/%m/%y %R"}
											{/if}
											</span>
											</div>
											{if $smarty.get.type == 'inbox' && $message.auto_mail!='yes'}
											<div class="span2">
												<a href="#replybox" class="btn btn-small scroll"><i class="icon-share-alt"></i> R&eacute;pondre</a>
											</div>
											{/if}
										</div>

										<div class="mailcontent">
											{$message.text_message}
											{if $message.attachment_name!=''}
												
												<div ><strong>Pi&egrave;ce jointe : </strong></div>
												{foreach item=attachment_file from=$attachments name=files}
											
													<div>
														{$attachment_file} 		
														<a href="/client/download-file?type=viewattachment&index={$smarty.foreach.files.index}&attachment={$message.id}">T&eacute;l&eacute;charger</a>
													</div>
												{/foreach}

											{/if}
										</div>
									</div>	
									<hr>
									{if $smarty.get.type == 'inbox' && $message.auto_mail!='yes'}
									<div class="well clearfix" id="replybox">
										<div class="span1">
											<a href="/client/profile"><img src="{$profile_picture}" title="{$client_email}"></a>
										</div>
										<div class="span11">
											<div class="muted">A : <strong>Service client</strong>
											<!--, <a href="#" class="muted">Ajouter</a>-->
											</div>
											<hr>
											<textarea id="mail_message" name="mail_message" class="textarea" placeholder="Votre message..."></textarea>
											<label for="mail_message" class="error" id="mail_message_error"></label>
											<button class="btn btn-small btn-primary" id="send_message">Envoyer</button>
										</div>
									</div>
									<input type="hidden" name="ticket_id" value="{$message.ticket_id}"/>
									{/if}
								</div>
								
							{/foreach}	
						</div>
					</section>
				</div>
			</div>
		</form>
	</section>
</div>