<section class="dashit wow fadeInLeft" id="clientwelove">
	<div class="container padding">
		<div class="center-block">
			<h4>Nos clients</h4>
			<ul>
				<li class="partnerslogo cosmo"></li>
				<li class="partnerslogo yahoo"></li>
				<li class="partnerslogo expedia"></li>
				<li class="partnerslogo ft"></li>
			</ul>
		</div>
	</div>
</section>

<section class="dashit" id="seosem">
	<div class="container padding">
		<div class="row">
			<div class="col-xs-12 col-md-6">   
				<div class="center-block">
					<img src="/FO/images/imageB3/svg/seo.svg" id="seo" class="img-center img-responsive wow bounceIn" data-wow-delay="100ms" data-wow-offset="300" width="500">
				</div>
			</div>
			<div class="col-xs-12 col-md-6">
				<h2>Nous rédigeons du contenu optimisé SEO
				<small>Augmenter le trafic et le temps passé sur votre site</small>
				</h2>
				<p>
					Rédaction de contenu sur les mots clés populaires dans Google tout en évitant les pénalités.
				</p>
				<ul>
					<li>Ranking des URL</li>
					<li>Détection de plagiat</li>
					<li>Proposition de sujets à fort potentiel de trafic</li>
					<li>Densité des mots clés et longue traine. </li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-md-4 col-md-offset-1">
				<h2 class="sem">Contenu pour les réseaux sociaux
					<small>Fidéliser vos clients</small>
				</h2>
				<ul>
					<li>Animation de home pages</li>
					<li>Animation de blogs</li>
					<li>Curation de contenu</li>
					<li>Alimentation réseaux sociaux</li>
					<li>Author rank - Iconographie </li>
				</ul>
			</div>
			<div class="col-xs-12 col-md-7">  
				<div class="center-block">
					<img src="/FO/images/imageB3/svg/sem.svg" class="img-center img-responsive wow rotateInUpLeft" width="600"  data-wow-offset="200" data-wow-delay="100ms">
				</div> 
			</div>
		</div>
	</div>  
</section>

<section class="dashit" id="translation"> 
	<div class="container padding">
		<div class="center-block">
			<h2>Traductions
				<small>Augmentez votre trafic sur l’ensemble de votre réseau</small>
			</h2>
			<div id="flag-list">
				<ul class=" wow fadeInLeft">
					<li><img src="/FO/images/imageB3/flag/france.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/uk.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/us.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/germany.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/spain.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/brasil.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/china.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/denmark.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/finland.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/italy.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/japan.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/norway.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/poland.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/portugal.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/russia.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/sweden.png" width="512" height="295" class="img-responsive"></li>
				</ul>
			</div>
			<h4 class="world">Adaptez et localisez votre contenu dans plus de 30 langues.</h4>
			<p>Des rédacteurs natifs en affinité avec votre sujet.<br />Localisation des mots clés de longue traine dans chaque langue.</p>
			<hr>
			<p><a href="#" class="btn btn-primary btn-lg" role="button">Obtenez le meilleur tarif maintenant</a></p>
		</div>
	</div>
</section>

<section class="dashit"  id="desc">
	<div class="container padding">
		<div class="row">
			<div class="col-xs-12 col-md-6 wow fadeInLeft">   
				<h2>Descriptif produit
				<small>Augmenter les ventes et améliorer la SEO</small> 
				</h2>
				<p>Livraison de descriptifs produits uniques en 72h.<br>
				Du contenu sur mesure pour votre marque.<br>
				Collaboration étroite avec votre studio photo.</p>
			</div>
			<div class="col-xs-12 col-md-6">
				<div class="center-block">
					<img src="/FO/images/imageB3/svg/note.svg" class="img-center img-responsive">
				</div>
			</div>
		</div>
	</div>    
</section>

<section class="dashit" id="strategy">
	<div class="container padding">
		<div class="row">
			<div class="col-xs-12 col-md-7"> 
				<div class="center-block">  
					<h2>Stratégie éditoriale</h2>
					<img src="/FO/images/imageB3/svg/strategy.svg" class="img-center img-responsive" width="230">
					<p><strong>Proposition de sujets, audit et recommandations de contenus.</strong><br>
					Création d'une ligne éditoriale, benchmark de la concurrence, ranking des articles, développements techniques...
					</p>
					<a href="#" class="btn btn-default btn-lg" role="button">En savoir plus</a>
				</div>
			</div>
			<div class="col-xs-12 col-md-4 col-md-offset-1">
				<div class="center-block">
					<div class="news-block">
						<h2>News <small>Augmenter votre trafic sur Google News</small></h2>
						<img src="/FO/images/imageB3/svg/news.svg" class="img-center img-responsive" width="90" height="90">
						<p>Sélection quotidienne des sujets sur la base d’outils de veille et rédaction en moins de 40mn. Disponibilité des rédacteurs sur tous les fuseaux horaires. </p>
					</div>
				</div>
			</div>
		</div>
	</div>    
</section> 

<section class="dashit" id="interview">
	<div class="container padding">
		<div class="row">
			<div class="col-xs-6 col-md-4"> <h2>Vos questions <small>Nos réponses</small></h2> </div>
			<div class="col-xs-6 col-md-4">
				<a href="display-video.html" class="wow flipInY" data-wow-offset="200" data-wow-delay="100ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/kasia.jpg" width="300" height="167" class="img-responsive"></div>Choisir les bons sujets <span class="who">Kasia, chef de projet Pologne</span></a>
			</div>
			<div class="col-xs-6 col-md-4">
				<a href="display-video.html" class="wow flipInY" data-wow-offset="200" data-wow-delay="300ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/alix.jpg" width="300" height="167" class="img-responsive"></div>
				Collaborer avec votre agence <span class="who">Alix, Rédactrice en chef FR</span></a>
			</div>
			<div class="col-xs-6 col-md-4">
				<a href="display-video.html" class="wow flipInY" data-wow-offset="100" data-wow-delay="500ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/santiago.jpg" width="300" height="167" class="img-responsive"></div>
				Lancer votre site à l’international<span class="who">Santiago, Chef de projet Espagne</span></a>
			</div>
			<div class="col-xs-6 col-md-4">
				<a href="display-video.html" class="wow flipInY" data-wow-offset="100" data-wow-delay="700ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/alex.jpg" width="300" height="167" class="img-responsive"></div>
				Améliorer votre ranking SEO <span class="who">Alex, Chef de projet UK</span></a>
			</div>
			<div class="col-xs-6 col-md-4">
				<a href="display-video.html" class="wow flipInY" data-wow-offset="100" data-wow-delay="900ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/emilie.jpg" width="300" height="167" class="img-responsive"></div>
				Publier vos descriptifs plus vite <span class="who">Emilie, Chef de projet Mode &amp; Voyages</span></a>
			</div>
		</div>
	</div>
</section>  

<section class="dashit" id="morecontent">
	<div class="container padding">
		<div class="center-block"><h2>Bien plus qu'un contenu</h2></div>
		<div class="row">
			<div class="col-xs-12 col-md-7">
				<div class="row">
					<div class="col-xs-12 col-md-4 wow fadeInLeft" data-wow-delay="0.1s">
						<div class="center-block">
							<img src="/FO/images/imageB3/svg/bo.svg" class="img-center img-responsive" width="90">
							<p class="title">Intégration des articles dans votre backoffice</p>
						</div>
					</div>
					<div class="col-xs-12 col-md-4 wow fadeInLeft" data-wow-delay="0.2s">
						<div class="center-block">
							<img src="/FO/images/imageB3/svg/pencil.svg" class="img-center img-responsive" width="90">
							<p class="title"> Correction orthographique et grammaticale</p>
						</div>
					</div>
					<div class="center-block">
						<div class="col-xs-12 col-md-4 wow fadeInLeft" data-wow-delay="0.3s">
							<img src="/FO/images/imageB3/svg/countdown.svg" class="img-center img-responsive" width="90">
							<p class="title">Délai de livraison garanti</p>
						</div>
					</div>
				</div>
				<hr> 
				<h4>Et aussi </h4>
				<ul>
					<li>Chef de projet éditorial et interlocuteur technique dédiés</li>
					<li>Rédacteurs spécialisés avec des références dans votre secteur d'activité</li>
					<li>Cession de tous les droits sur tous supports</li>
				</ul>
			</div>
			<div class="col-xs-12 col-md-4 col-md-offset-1">
				<div class="news-block">
					<a href="blog.html">
						<img src="/FO/images/imageB3/author-rank.jpg" width="370" height="211" alt="Author Rank" class="img-responsive">
						<h3>Author rank</h3>
					</a>
					<p>Personnaliser  les résultats de recherche en y introduisant l'author box, grâce à nos rédacteurs connectés sur Google+</p>
					<a href="#">En savoir plus</a>
				</div>
			</div>
		</div>
	</div>    
</section>

<section class="dashit" id="callus">
	<div class="container padding">
		<div class="center-block">
			<h4>Parlons de votre projet</h4>
			<h2>01 77 68 64 61</h2>
			<p>Prix d’un appel local. Lundi au vendredi de 10h à 18h</p>
			<a href="/index/contact" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-envelope"></span> Contactez nous</a>
		</div>
	</div>
</section>
