{literal}
<script language="javascript">
	$("#menu_home").removeClass("active"); 
	$("#menu_profile").removeClass("active");
	$("#menu_mailbox").removeClass("active");
	$("#menu_billing").removeClass("active");
</script>

<style>
	.error { padding-bottom:6px; color:red; margin:0; }
</style>
{/literal}	
	
	<header>
		<div class="container navbar navbar-inverse">
		  <div class="navbar-inner">
			<div class="container">
			  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </a>
			  <a id="brand" class="brand" title="Accueil edit-place" href="/"><img id="logo" src="/FO/images/shim.gif"></a>
			  <div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="/client/premium">Solution PREMIUM</a></li>
					<li><a href="/index/nos-references">Nos références</a></li>
					<li><a href="http://www.edit-place.com/blog/">Blog <span class="badge badge-warning">New</span></a></li>	
					<li><a href="/client/
					-1" role="button" class="btn btn-mini btn-primary"><i class="icon-edit icon-white"></i>Demander un devis</a></li>
				</ul>
				<ul class="nav pull-right">  
					{if $clientidentifier==""}	
						<li><a  href="" data-target="#create-user" data-toggle="modal"><i class="icon-user icon-white"></i> Espace contributeur</a></li>    
					{/if}
					<li>
						{if $clientidentifier!=""}	
						 <a data-toggle="dropdown" class="btn btn-mini btn-login dropdown-toggle">
							<i class="icon-user icon-white"></i> {$clientname} <span class="caret"></span>
						  </a>
							<!-- Link or button to toggle dropdown -->
						  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li><a tabindex="-1" href="/client/home">Mon espace client</a></li>
							<li><a tabindex="-1" href="/client/profile">G&eacute;rer mon compte</a></li>
							<li><a tabindex="-1" href="/client/billing">Mes factures</a></li>
							<li class="divider"></li>
							<li><a tabindex="-1" href="/client/inbox">Ma messagerie</a></li>
							<li><a tabindex="-1" href="/client/logout">D&eacute;connexion</a></li>
						  </ul>
						{else}
							<a href="" data-target="#login" data-toggle="modal"><i class="icon-briefcase icon-white"></i> Connexion</a>
						{/if}	
				  </li>             
                </ul>    
			  </div><!--/.nav-collapse -->
			  </div>
			   {if $clientidentifier!=""}
			   <!-- secondary nav -->
				<div class="container" id="secondary-nav">
					<div class="nav-collapse collapse">
						<ul class="nav">
							<li><a href="/client/home" id="menu_home">Mon espace client</a></li> 
							<li><a href="/client/profile" id="menu_profile">Mon compte</a></li>
							<li><a href="/client/inbox" id="menu_mailbox">Messagerie {if $unreadmessage>0}<span class="badge badge-warning">{$unreadmessage}</span>{/if}</a> </li>
							<li><a href="/client/billing" id="menu_billing">Factures</a></li>
						</ul>
					</div><!--/.nav-collapse -->
				</div>
				{/if}
		  </div>
		</div>
    </header>
	
	<!-- ***** Modal collections -->

	<div id="login" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		{include file="common/libertelogin.phtml"}
	</div>	
	<div id="create-user" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		{include file="common/create_contrib.phtml"}
	</div>
	
	<div id="lost-password" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> 
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="myModalLabel"><i class="icon-user"></i> Mot de passe oubli&eacute; ?</h3>
		</div>
		<div class="modal-body">
			<div class="alert alert-info" id="alert">Pour recevoir &agrave; nouveau votre mot de passe, veuillez saisir votre e-mail.</div>
			<form class="form-horizontal">
				<div class="control-group"> 
				<label class="control-label" for="inputEmail" style="margin:0px">Votre Email</label>
					<div class="controls">
						<input type="text" name="forgotpwdemail" id="forgotpwdemail" placeholder="Email" class="input-xlarge" />
						<div class="error" id="forgotpwdemailerr"></div>
						<br><br>
						<button type="button" class="btn btn-primary" onClick="return forgotpasswordmailindex();">Valider</button>
						<button class="btn" data-dismiss="modal" aria-hidden="true" type="button">Annuler</button>
					</div>
				</div>
			</form>
		</div>
	</div>