<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>{$page_title}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="{$meta_desc}">
		<meta name="author" content=""> 
		<link rel="shortcut icon" type="image/x-icon" href="/FO/favicon.ico" />
		{foreach from=$javascriptList item=javascript}
			<script language="JavaScript" type="text/javascript" src="http://ep-test.edit-place.com/FO/script/{$javascript}"></script>
		{/foreach}

		{foreach from=$cssList item=css}
			<link href="http://ep-test.edit-place.com/FO/css/{$css}" type="text/css" rel="stylesheet" />
		{/foreach}
		<!-- Le styles -->

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		<!--[if IE]>
			<link rel="stylesheet" type="text/css" href="/FO/css/common/ep_ie.css" />
		<![endif]-->
		
		<link href="/FO/css/common/ep.css" rel="stylesheet" type="text/css" />
		<link href='/FO/css/common/googleapi_fonts.css' rel='stylesheet' type='text/css'>
		<link href="/FO/css/common/custom.css" rel="stylesheet" type="text/css" />
		<script src="/FO/script/common/jquery.min.js"></script>
<link href="/FO/css/common/jquery-ui-1.9.2.custom.css" rel="stylesheet" type="text/css" />
<script src="/FO/script/common/jquery-ui-1.9.2.custom.min.js"></script>
		<script src="/FO/script/common/bootstrap.min.js"></script>
		<script src="/FO/script/common/jquery.slimscroll.js"></script>
		<script src="/FO/script/common/login_validation.js"></script>
		<script src="/FO/script/common/jquery.validate.min.js"></script>
				 
	</head>

	<body>
		{foreach from=$headerList item=frame}
			{include file="$frame"}
		{/foreach}
		
		{foreach from=$mainList item=frame}
			{include file="$frame"}
		{/foreach} 	
		
		{foreach from=$footerList item=frame}
			{include file="$frame"}
		{/foreach}	
	{literal}
	<script> 
		// tooltip activation
		$("[rel=tooltip]").tooltip();
		$("[rel=popover]").popover();
	</script>
	<style>
		.dropdown-menu {top:30px; right:50px !important}
	</style>
	{/literal}
  </body>
</html>

