<footer>
	<div id="map">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 col-md-4">
					<div class="center-block">
						<h3>Paris</h3>
					</div>
				</div>
				<div class="col-xs-12 col-md-4">
					<div class="center-block">
						<h3>London</h3>
					</div>
				</div>
				<div class="col-xs-12 col-md-4">
					<div class="center-block">
						<h3>Bangalore</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<ul class="links">
			<li><a href="#">Nos tarifs</a></li>
			<li><a href="/index/jobs">Jobs</a></li>
			<li><a href="/index/nos-partenaires">Nos partenaires</a></li>
			<li><a href="/index/qui-sommes-nous">L'équipe</a></li>
			<li><a href="/index/contact">Contactez-nous</a></li>
			<li><a href="/index/nos-references">Nos références</a></li>
			<li><a href="/index/cgu">CGU</a> </li>
		</ul>
	</div>
</footer>  
