<!DOCTYPE html>

<html lang="fr">

	<head>

		<meta charset="utf-8">

		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{$page_title}</title>

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<meta name="description" content="{$meta_desc}">

		<meta name="author" content=""> 



		<!-- Le styles -->

	      	

		<link href="/FO/css/bootstrap3/bootstrap.min.css" rel="stylesheet">

		<link href='/FO/css/bootstrap3/googleapi_fonts.css' rel='stylesheet' type='text/css'>

		<link href="/FO/css/bootstrap3/ep-theme.css" rel="stylesheet">

		<link rel="stylesheet" href="/FO/css/bootstrap3/animate.min.css">

		 <link href="/FO/plugins/skins/square/blue.css" rel="stylesheet"> 

		

		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

		<script src="/FO/script/bootstrap3/bootstrap.min.js"></script>
<script src="/FO/script/bootstrap3/wow.min.js"></script> 
<script src="/FO/script/bootstrap3/ep.js"></script>
		

		<script src="/FO/script/common/login_validation.js"></script> 

		<script src="/FO/script/common/jquery.validate.min.js"></script>

		

		

		

		<!--[if lt IE 9]>

		  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>

		  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

		<![endif]-->

	</head>



	<body class="home">

		{foreach from=$headerList item=frame}

			{include file="$frame"}

		{/foreach}

		

		{foreach from=$mainList item=frame}

			{include file="$frame"}

		{/foreach} 	

		

		{foreach from=$footerList item=frame}

			{include file="$frame"}

		{/foreach}	

		


		<!--<script src="/FO/script/bootstrap3/icheck.min.js"></script>

		<script src="/FO/script/bootstrap3/bootstrap-select.min.js"></script>-->

		

  </body>

</html>



