{literal}
<script type="text/javascript">
var cur_date=0,js_date=0,diff_date=0;
cur_date={/literal}{$smarty.now}{literal};
js_date=(new Date().getTime())/ 1000;
diff_date=Math.floor(js_date-cur_date);
$("#menu_aosearch").addClass("active");	
</script>
{/literal}
<div class="container">
	<div class="row-fluid">
		<h1>Toutes les annonces</h1>
		<p> R&eacute;pondez vite aux annonces ci-dessous en  proposant votre tarif avant la fin du compte &agrave; rebours.</p>
	</div>

	<div class="row-fluid">
		<div class="span12">
			{if $recruitmentDetails |@count gt 0}
			<section id="recruitment">
				<div class="mod">					
					{foreach item=recruitment from=$recruitmentDetails name="recruitmentDetails"}
					<div class="row-fluid">
						<div class="span9">
							<span data-placement="right" rel="tooltip" data-original-title="Garanteed long-term Mission" class="label label-test-mission"><i class="icon-star icon-white"></i>  Staffing</span>
							<h3>
								{if $recruitment.recruitment_article_id}
									<a href="/recruitment/participation-challenge?recruitment_id={$recruitment.deliveryid}&article_id={$recruitment.recruitment_article_id}#sign-contract" {if $recruitment.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$recruitment.title|stripslashes}"{/if}>{$recruitment.title|truncate:55:"...":true|stripslashes}</a>
								{else}
									<a href="/recruitment/participation-challenge?recruitment_id={$recruitment.deliveryid}" {if $recruitment.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$recruitment.title|stripslashes}"{/if}>{$recruitment.title|truncate:55:"...":true|stripslashes}</a>
								{/if}	
							</h3>
							<div class="muted">{$recruitment.product_name} pour le client {$recruitment.client_name} {$recruitment.mission_volume} {$recruitment.product_type_name} Mission de {$recruitment.delivery_time_frame} {$recruitment.delivery_period_text}. {$recruitment.editorial_chief_review|truncate:80:"...":true|stripslashes}</div>
						</div>
						<div class="span3">
							<h3 style="text-align: center">jusqu'&agrave; {$recruitment.turnover} &euro;*</h3>
							<a class="btn btn-primary btn-block" href="/recruitment/participation-challenge?recruitment_id={$recruitment.deliveryid}">Participez</a>
						</div>
					</div>	
					{/foreach}
				</div>
			</section>
			{/if}
			<section id="classified">
				<!-- List of classifieds that contributor might like -->
				<div class="navbar" style="padding-bottom: 0">
					<div class="navbar-inner filter-container">
						<ul class="nav">
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#">
									{if $smarty.get.search_category}
										{$categoryFilter}
									{else}
										Toutes les cat&eacute;gories
									{/if}	
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									{if $smarty.get.search_category}
										<li><a class="active" href="/contrib/aosearch?search_category=&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}" class="active">{$categoryFilter}</a></li>
									{else}
										 <li><a href="#" class="">Toutes les cat&eacute;gories</a></li>
									{/if}	
								  <li class="divider"></li>
									{if $ep_categories_list|@count gt 0 }
										{foreach  key=key item=category from=$ep_categories_list}
											{if in_array($key,$filter_category) && $smarty.get.search_category neq $key }
												 <li><a href="/contrib/aosearch?search_category={$key}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}">{$category}</a></li>
											{/if}
										{/foreach}
									{/if}
								  
								</ul>
							 </li>
							<li class="divider-vertical"></li>
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#">
									{if $smarty.get.search_language}
										{$languageFilter}
									{else}
										Toutes les langues
									{/if}	
									 <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									{if $smarty.get.search_language}
										<li><a  class="active" href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language=&search_ao_type={$smarty.get.search_ao_type}" class="active">{$languageFilter}
											
										</a>
										</li>
									{else}
										 <li><a href="#" class="">Toutes les langues</a></li>
									{/if}	
								  
								  <li class="divider"></li>
								  {if $ep_languages_list|@count gt 0 }
										{foreach  key=key item=language from=$ep_languages_list}
											{if in_array($key,$filter_language) && $smarty.get.search_language neq $key}
												 <li><a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$key}&search_ao_type={$smarty.get.search_ao_type}">{$language}</a></li>
											{/if}
										{/foreach}
									{/if}
								</ul>
							</li>
							<li class="divider-vertical"></li>
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#">
									{if $smarty.get.search_ao_type}
										{$aoTypeFilter}
									{else}
										Tous les types 
									{/if}	
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
								  {if $smarty.get.search_ao_type}
										<li><a  class="active" href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type=" class="active">{$aoTypeFilter}
											
										</a>
										</li>
									{else}
										 <li><a href="#" class="">Tous les types</a></li>
									{/if}
								  <li class="divider"></li>
									{if $ep_languages_list|@count gt 0 }
										{foreach  key=key item=ao_types from=$ep_aotype_list}
											{if $smarty.get.search_ao_type neq $key}
												 <li><a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$key}">{$ao_types}</a></li>
											{/if}
										{/foreach}
									{/if}
								  
								</ul>
							</li>
							 <li class="divider-vertical"></li>
						</ul>
						<ul class="nav  pull-right">                     
							<li>
								<form class="navbar-form" method="GET">
									<input type="text" {if !$searchgetText} placeholder="Mot-cl&eacute;"{/if} class="input-medium" name="search_article" value="{$searchgetText}">
									<button class="btn btn-small" type="submit">OK</button>
								</form>
							</li>
						</ul>
					</div>
				</div>
				<div class="mod">
					<!-- about sorting  add the following tags <i class="icon-circle-arrow-down"></i> only if a user has clicked on a title head !!!
					do not display the icon by default-->
					<table class="table table-hover">
					<thead>
						<tr>
							<th><a href="#orderByType">Type</a></i></th>
							<th>
								{if $smarty.get.orderByTitle eq 'desc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByTitle=asc">Titre</a>
									<i class="icon-circle-arrow-down"></i>
								{elseif $smarty.get.orderByTitle eq 'asc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByTitle=desc">Titre</a>
									<i class="icon-circle-arrow-up"></i>
								{else}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByTitle=asc">Titre</a>	
								{/if}	
							</th>
							<th class="pc">
								{if $smarty.get.orderByLang eq 'desc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByLang=asc">Langues</a>
									<i class="icon-circle-arrow-down"></i>
								{elseif $smarty.get.orderByLang eq 'asc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByLang=desc">Langues</a>
									<i class="icon-circle-arrow-up"></i>
								{else}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByLang=asc">Langues</a>	
								{/if}								
							</th>
							<th class="pc">
								{if $smarty.get.orderBytime eq 'desc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderBytime=asc">Fin d'envoi des devis</a>
									<i class="icon-circle-arrow-down"></i>
								{elseif $smarty.get.orderBytime eq 'asc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderBytime=desc">Fin d'envoi des devis</a>
									<i class="icon-circle-arrow-up"></i>
								{else}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderBytime=asc">Fin d'envoi des devis</a>	
								{/if}
								
							</th>
							<th class="pc">
								{if $smarty.get.orderByAttendee eq 'desc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByAttendee=asc">Participants</a>
									<i class="icon-circle-arrow-down"></i>
								{elseif $smarty.get.orderByAttendee eq 'asc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByAttendee=desc">Participants</a>
									<i class="icon-circle-arrow-up"></i>
								{else}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByAttendee=asc">Participants</a>	
								{/if}
								
							</th>
							{*<th class="pc">
								
								{if $smarty.get.orderByQuotePrice eq 'desc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByQuotePrice=asc">Dernier devis</a>
									<i class="icon-circle-arrow-down"></i>
								{elseif $smarty.get.orderByQuotePrice eq 'asc'}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByQuotePrice=desc">Dernier devis</a>
									<i class="icon-circle-arrow-up"></i>
								{else}
									<a href="/contrib/aosearch?search_category={$smarty.get.search_category}&search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&orderByQuotePrice=asc">Dernier devis</a>	
								{/if}						
								
							</th>*}
						</tr>
					</thead>
					<tbody>
						{if $articles |@count gt 0}
							{foreach item=article from=$articles name="articledetails"}
								<tr>
									{if $article.ao_type eq 'correction'}
										<td>
											{if $article.missiontest eq 'yes'}
												<span class="label label-test-mission" data-original-title="Garanteed long-term Mission" rel="tooltip" data-placement="right">Mission de correction test</span>
											{else}
												<span class="label label-correction" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Correction</span>
											{/if}	
											{if $article.view_to eq 'sc'}
												<span data-original-title="Accessible aux s&eacute;niors" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
											{elseif $article.view_to eq 'jc'}
												<span data-original-title="Accessible aux juniors" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
											{elseif $article.view_to eq 'jc0'}
												<span data-original-title="Accessible aux d&eacute;butants" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
											{/if}
										</td>
										<td class="title"><a href="/contrib/article-details?misson_type=correction&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}  {$article.picon} </span>
									{elseif $article.ao_type eq 'poll_premium'}
												<td><span class="label label-quote-premium" data-original-title="Cette annonce est susceptible de devenir une mission Premium" rel="tooltip" data-placement="right">Devis premium</span>
												{if $article.contributors eq '0'}
													<span data-original-title="Accessible aux s&eacute;niors" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
												{elseif $article.contributors eq '1'}
													<span data-original-title="Accessible aux juniors" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
												{elseif $article.contributors eq '3'}
													<span data-original-title="Accessible aux d&eacute;butants" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
												{/if}
												
												</td>
												<td class="title"><a href="/contrib/article-details?misson_type=poll_premium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>
									{elseif $article.ao_type eq 'poll_nopremium'}
												<td><span class="label label-quote" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Devis Libert&eacute;</span>
												{if $article.contributors eq '0'}
													<span data-original-title="Accessible aux s&eacute;niors" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
												{elseif $article.contributors eq '1'}
													<span data-original-title="Accessible aux juniors" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
												{elseif $article.contributors eq '3'}
													<span data-original-title="Accessible aux d&eacute;butants" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
												{/if}
												</td>
												<td class="title"><a href="/contrib/article-details?misson_type=poll_nopremium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>		
									{elseif $article.premium_option}
											<td>
												{if $article.missiontest eq 'yes'}
													<span class="label label-test-mission" data-original-title="Garanteed long-term Mission" rel="tooltip" data-placement="right"> Staffing</span>
												{else}
													<span class="label label-premium" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Premium</span>
												{/if}
											{if $article.view_to eq 'sc'}
												<span data-original-title="Accessible aux s&eacute;niors" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
											{elseif $article.view_to eq 'jc'}
												<span data-original-title="Accessible aux juniors" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
											{elseif $article.view_to eq 'jc0'}
												<span data-original-title="Accessible aux d&eacute;butants" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
											{/if}
											</td>
											<td class="title"><a href="/contrib/article-details?misson_type=premium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
									{elseif !$article.premium_option}
										<td>
											{if $article.missiontest eq 'yes'}
												<span class="label label-test-mission" data-original-title="Garanteed long-term Mission" rel="tooltip" data-placement="right"> Staffing</span>
											{else}
												<span class="label label-quote" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Mission Libert&eacute;</span>	
											{/if}
											{if $article.view_to eq 'sc'}
												<span data-original-title="Accessible aux s&eacute;niors" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
											{elseif $article.view_to eq 'jc'}
												<span data-original-title="Accessible aux juniors" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
											{elseif $article.view_to eq 'jc0'}
												<span data-original-title="Accessible aux d&eacute;butants" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
											{/if}
										</td>
										<td class="title"><a href="/contrib/article-details?misson_type=nopremium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
									{/if}									
									<p class="muted">{$article.category}  &bull;  Appel &agrave; r&eacute;daction  &bull;  {$article.num_min} - {$article.num_max} mots / article</p></a></td>
									<td class="pc"><img src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$article.language_name}" class="flag flag-{$article.language}"></td>
									<td class="countdown pc">
										{if $article.ao_type eq 'correction'}
											<span id="time_{$article.articleid}-correction_{$article.timestamp}">
												{if $article.participation_expires}
													<span id="text_{$article.articleid}-correction_{$article.timestamp}" ></span>
												{else}
													<span id="text_{$article.articleid}-correction_{$article.timestamp}"></span>	
												{/if}	
											</span>	
										{else}
											<span id="time_{$article.articleid}_{$article.timestamp}">
												{if $article.participation_expires}
													<span id="text_{$article.articleid}_{$article.timestamp}" ></span>
												{else}
													<span id="text_{$article.articleid}_{$article.timestamp}"></span>	
												{/if}	
											</span>
										{/if}	
											
									</td>
									<td class="countdown pc"><em>{$article.participants}</em></td>
									{*<td class="countdown pc">
										<em>
										{if $article.pricedisplay eq 'yes'}
											{if $article.latestPrice}
												{$article.latestPrice}
											{else}
												0 
											{/if}	
											 &euro;
										{else}
											/
										{/if}	 
										</em>
									</td>*}
								</tr>								
							{/foreach}
						{else}
							<tr>
								<td colspan="6">
									<span class="no-data">Aucun r&eacute;sultat</span>
								</td>
							</tr>
						{/if}
					</tbody>
					</table>
					<!---Pagination start-->
					<div class="pagination pull-right">
						{include file="Contrib/pagination.phtml"}
					</div>	
					<!---Pagination END-->
				</div>			
				<!-- Block to display coming soon articles -->
				{include file="Contrib/upcoming_ao.phtml"}				
				<!-- Block to finished articles -->
				{include file="Contrib/terminated_ao.phtml"}
				
				
				
			</section>
		</div>
	</div>
</div>
<!-- ajax use end --> 