{literal}
<script language="JavaScript" type="text/javascript" src="/FO/script/common/jquery.MultiFile.js"></script>
<script type="text/javascript">

 $(document).ready(function() {	
	
	$("#menu_mailbox").addClass("active");
	$("#menu_compose").addClass("disabled");
	
	// call write email function
	$('#mail_message').wysihtml5({locale: "fr-FR"});
	

	$("#filePJ").MultiFile ();
	//compose mail validation
	/* jQuery.validator.addMethod("htmltext", function(mail_message, element) {
				return false;
				//return mail_message.textContent||mail_message.innerText;
			}, "Message obligatoire");
			
			$("#composeMail").validate({
				rules:{
					sendto:"required",
					mail_object:"required",
					mail_message:{required:true,htmltext:true}	
				},
				messages:{
					sendto:"sendto obligatoire",
					mail_object:"Objet obligatoire",
					mail_message:"Message obligatoire"
				},
				//errorClass: "help-inline",
				errorClass: "error",
				errorElement: "label",
				
				highlight: function(label) {
					$(label).addClass('error');
					$(label).removeClass('success');
				},
				success: function(label) {
					label.addClass('success');
					label.removeClass('error');
				}			
			}); */
	});	

	
	
</script>
{/literal}	

<div class="container">
	{if $actionmessages[0]}
		<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">&times;</button>
			<i class="icon-ok icon-white"></i> {$actionmessages[0]}.
		</div>  
	{/if}
	<section id="maibox">
		<form name="compose_mail" id="composeMail" method="post" action="/contrib/send-mail" enctype="multipart/form-data">
			<div class="row">    
				<div class="span12">
					<h1>Messagerie priv&eacute;e</h1>
					<hr>
				</div>
				
				{include file="Contrib/pattern/mail_leftmenu.phtml"}

				<div class="span9">
					<div class="mod row-fluid">
						<h4><i class="icon-pencil"></i> Nouveau message</h4>
						<div class="well clearfix" id="replybox">
							<div class="span1">
								<a href="/contrib/modify-profile"><img src="{$profile_picture}" title="{$client_email}"></a>
							</div>
							<div class="span11">
								<div class="muted" id="to">
									<label>A :
									<select class="input-xxlarge" name="sendto" id="sendto">
										<option value="">S&eacute;lectionnez</option>
										<!--{html_options  options=$ongoingContacts selected=$touser}-->
										{if $ongoingContacts|@count gt 0}
											<optgroup label="Articles" name="service_contact">
												{foreach item=article from=$ongoingContacts}
													<option value="{$article.created_user}" {if $article.created_user eq $touser} selected{/if} >{$article.title}</option>
												{/foreach}			
											</optgroup>	
										{/if}										
										<optgroup label="Autre" name="Autre">
											<option value="110823103540627">Autre</option>
										</optgroup>
									</select>
									<label for="sendto" class="error" id="sendto_error"></label>
									<!--, <a href="#" class="muted">+ ajouter</a>-->
									</label> 
								</div>
								<hr>
								<input name="mail_object" id="mail_object" type="text" value="{$mail_object}" class="span12 inline input" placeholder="Votre objet...">
								<label for="mail_object" class="error" id="mail_object_error"></label>
								<textarea name="mail_message" id="mail_message" class="textarea" placeholder="Votre message..."></textarea>
								<label for="mail_message" class="error" id="mail_message_error"></label>
								
								
								<p class="btn-link disabled" data-target="#addfile" data-toggle="collapse">Ajouter un fichier</p>
								<div id="addfile" class="collapse out">
									<input type="file" name="attachment[]" id="filePJ">					
									<hr>
								</div>								
								<button class="btn btn-small btn-primary" id="send_message">Envoyer</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</section>
</div>