<div class="container">
	 <!-- start, status -->
	<div class="row-fluid">
		
		<div class="span12" id="state2">
			<ul class="unstyled">
				<li data-original-title="Je propose un devis pour chaque annonce s&eacute;lectionn&eacute;e" rel="tooltip" class="span4"><span class="bid-selection">Ma s&eacute;lection d'annonces</span></li>
				<li data-original-title="Signature du contrat d'engagement Edit-place" rel="tooltip" class="hightlight span4"><span class="contract">Contrat Edit-place</span></li>
				<li data-original-title="Mes devis sont maintenant visibles par Edit-place et ses clients" rel="tooltip" class="span4"><span class="participant-ok">Validation</span></li>
			</ul>
		</div>
	 </div>
 
	<!-- end, status -->
   <h1>Contrat edit-place<div class="pull-right" id="link-print"><a href="#print-contractForm" class="btn btn-small" ><i class="icon-print"></i> Imprimer le contrat</a></div></h1>
   
  
	<div class="mod">
		<div class="contractform well well-large" id="contract">
		Entre les soussignés :
		<address>
			<strong>{$FirstName} {$LastName}</strong><br>
			Date  de naissance : {$dob}<br>
			Adresse : {$address}<br>
			Pays : {$pays}
		 </address>
		<p>  Ci-dessous  d&eacute;nomm&eacute; &laquo;le R&eacute;dacteur&raquo;,</p>  
<p>D'une  part,</p>
<p>et </p>
<p>La  soci&eacute;t&eacute; Edit-place.com, Soci&eacute;t&eacute; au capital de 20140 Euros<br>
  Immatricul&eacute;e  au RCS de Bobigny sous le num&eacute;ro B 521 287 193, <br>
  Dont  le si&egrave;ge social est situ&eacute; 16 Rue Jesse Owens 93200 ST DENIS,<br>
  Prise  en la personne de son repr&eacute;sentant l&eacute;gal domicili&eacute; audit si&egrave;ge en cette  qualit&eacute;,</p>
<p>&nbsp;</p>
<p>Ci-dessous  &nbsp;d&eacute;nomm&eacute;e &laquo;&nbsp;la Soci&eacute;t&eacute;&raquo;, </p>
<p>D'autre  part,</p>
<p>&Eacute;TANT  PR&Eacute;ALABLEMENT RAPPEL&Eacute; QUE : </p>
<p>La  Soci&eacute;t&eacute; a pour principale activit&eacute; de mettre en relation des &eacute;diteurs  recherchant du Contenu &eacute;crit (ci-apr&egrave;s le &laquo;&nbsp;Client&nbsp;&raquo;), le cas &eacute;ch&eacute;ant  optimis&eacute; pour le r&eacute;f&eacute;rencement naturel, et des R&eacute;dacteurs susceptibles de leur  fournir ce Contenu (ci-apr&egrave;s le &laquo;&nbsp;Service&nbsp;&raquo;).<br>
  Ce  Service est propos&eacute; sur le site&nbsp;: <a href="http://www.edit-place.com">www.edit-place.com</a><u> </u><br>
  La  Soci&eacute;t&eacute; contracte aux termes des pr&eacute;sentes, dans le cadre du Service, au nom et  pour le compte du Client souhaitant acqu&eacute;rir les droits d'exploitation sur le Contenu  transmis par le R&eacute;dacteur, sous condition de s&eacute;lection de ce dernier par le  comit&eacute; de lecture conform&eacute;ment aux conditions g&eacute;n&eacute;rales d'utilisation, et dans  les conditions ci-apr&egrave;s d&eacute;finies.</p>
<p>IL  A ETE CONVENU CE QUI SUIT :</p>
<p>Article  1 &ndash; Objet</p>
<p>Le  R&eacute;dacteur, qui d&eacute;clare b&eacute;n&eacute;ficier de sa pleine capacit&eacute; juridique et / ou des  pouvoirs n&eacute;cessaires &agrave; signer le pr&eacute;sent contrat de cession de droit, et pour  autant que le(s) Contenu(s) pr&eacute;sente(nt) l'originalit&eacute; requise, c&egrave;de &agrave; titre  exclusif &agrave; la Soci&eacute;t&eacute;, qui accepte pour lui-m&ecirc;me et ses ayants droit, les  droits d'exploitation ci-apr&egrave;s d&eacute;finis, aff&eacute;rents au(x) Contenu(s) (ci-apr&egrave;s  d&eacute;nomm&eacute; &laquo;Contenu&raquo;) qui ont pour nom de fichier et/ou pour titre :</p>
<p>&nbsp;</p>
<!--Article Details-->
{$ArticlesDetails}
<!--Ended-->
<p>&nbsp;</p>
<p>La  pr&eacute;sente cession comporte, ainsi, pour la Soci&eacute;t&eacute;, le droit d'exploiter directement  ou indirectement le Contenu&nbsp; ci-dessus  d&eacute;crit, ou de c&eacute;der les droits suivants:</p>
<p>Pour  les droits d'adaptation et de reproduction :</p>
<p>-  Le droit de num&eacute;riser, enregistrer et reproduire le Contenu sur tout r&eacute;seau  num&eacute;rique, c'est-&agrave;-dire tout r&eacute;seau informatique, internet, WAP, mobile,  intranet ;</p>
<p>-  Le droit de reproduire le Contenu et de l'adapter sous forme d'&eacute;dition  &eacute;lectronique, en particulier en c&eacute;d&eacute;rom, CD-photo, CD-I, ou tout autre proc&eacute;d&eacute;  analogue ou &agrave; venir ;</p>
<p>-  Le droit de reproduire tout ou partie du Contenu et de l'adapter et sur les  terminaux de lecture et les r&eacute;seaux num&eacute;riques, &eacute;lectroniques ou optom&eacute;triques,  en particulier sur les r&eacute;seaux internet et les serveurs d'information Web, WAP,  disques dur d'ordinateurs, serveurs, &nbsp;tablettes,  les assistants &eacute;lectroniques , t&eacute;l&eacute;phones portables et smartphone ou tout autre  appareil permettant de stocker des donn&eacute;es num&eacute;ris&eacute;es existant et &agrave; venir ; </p>
<ol>
  <li>Le droit d'adapter le Contenu aux r&egrave;gles d'optimisation du  r&eacute;f&eacute;rencement naturel sur Internet, de mani&egrave;re &agrave; permettre une apparition du Contenu  dans les principaux moteurs de recherche en fonction des requ&ecirc;tes des  internautes.</li>
</ol>
<p>&nbsp;</p>
<p>Pour  le droit de repr&eacute;sentation :</p>
<p>-  le droit de communiquer et de mettre &agrave; la disposition du public le Contenu ou  ses adaptations, de traduire en toutes langues et en tous pays, par tous  proc&eacute;d&eacute;s de diffusion des paroles, des sons et des images, notamment par les  r&eacute;seaux num&eacute;riques, &eacute;lectroniques ou optom&eacute;triques, en particulier sur les  r&eacute;seaux internet et les serveurs d'information Web, WAP, r&eacute;seaux mobiles, applications  iPhone ou iPad ou par tout autre proc&eacute;d&eacute; analogue ou &agrave; venir.</p>
<p>- Toute diffusion par tout moyen de  t&eacute;l&eacute;communication, notamment par voie hertzienne, par satellite, par  t&eacute;l&eacute;diffusion et par tout moyen de cablo-distribution.</p>
<p>- La repr&eacute;sentation du Contenu en tout ou partie, dans toute  manifestation publique, festival, salon, manifestation &agrave; vocation culturelle,  d'information, professionnelle ou commerciale.</p>
<p>La  pr&eacute;sente cession est consentie dans le dessein principal de permettre l'acc&egrave;s  du public au Contenu sur Internet, et ce, notamment sur les sites et/ou  applications du Client et de ses partenaires actuels ou futurs.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  Article  2 - Dur&eacute;e de la cession et renouvellement</p>
<p>La  pr&eacute;sente cession est consentie pour avoir effet en tous lieux, pour tous les  pays et toutes les langues, et pour une dur&eacute;e de quinze (15) ann&eacute;es  cons&eacute;cutives &agrave; compter de l'acceptation de la contribution de l'auteur. </p>
<p>Sauf  manifestation expresse des parties en sens contraire, le pr&eacute;sent contrat fera  l'objet d'une tacite reconduction &agrave; l'expiration de la p&eacute;riode de quinze (15)  ann&eacute;es mentionn&eacute;e &agrave;&nbsp; l'alin&eacute;a pr&eacute;c&eacute;dent. <br>
  Ce  renouvellement tacite se fera par p&eacute;riodes de quinze (15) ann&eacute;es, dans la  limite de la dur&eacute;e l&eacute;gale des droits d'auteur.</p>
<p>Il  est express&eacute;ment convenu que le Client aura rempli ses obligations lorsque le Contenu  s&eacute;lectionn&eacute; aura &eacute;t&eacute; accessible pendant une dur&eacute;e de 3 mois cons&eacute;cutifs sur les  r&eacute;seaux num&eacute;riques, sauf en cas d'information obsol&egrave;te permettant au Client de  proc&eacute;der &agrave; son retrait pr&eacute;alablement.</p>
<p>Article  3 &ndash; Exclusivit&eacute; et notification de cessions ult&eacute;rieures</p>
<p>Le  R&eacute;dacteur s'engage &agrave; ne pas c&eacute;der&nbsp; &agrave;&nbsp; nouveau les droits d'exploitation aff&eacute;rents &agrave;  ce Contenu.<br>
  Le  R&eacute;dacteur s'engage par ailleurs &agrave; informer pr&eacute;alablement le Client cessionnaire  et la Soci&eacute;t&eacute; de tout projet de cession d'autres droits d'exploitation sur  ledit Contenu &agrave; quelque tiers que ce soit.<br>
  Cette  notification pr&eacute;alable du r&eacute;dacteur &agrave; la Soci&eacute;t&eacute; d'un projet de cession de  droits s'effectuera par l'envoi d'un message via l'espace de discussion mis &agrave;  disposition des r&eacute;dacteurs et &eacute;diteurs sur le Service, doubl&eacute; d'un message  adress&eacute; directement &agrave; Edit-Place.<br>
  Le  Client, &agrave; compter de la r&eacute;ception de cette notification, disposera d'un d&eacute;lai  de 10 jours ouvr&eacute;s pour formuler ses observations, et le cas &eacute;ch&eacute;ant s'opposer  au projet s'il estime que les droits lui ont d&eacute;j&agrave; &eacute;t&eacute; c&eacute;d&eacute; en exclusivit&eacute;, ou  solliciter la cession des droits d'exploitation envisag&eacute;e moyennant paiement.</p>
<p>A  d&eacute;faut de r&eacute;ponse dans le d&eacute;lai imparti, le Client sera r&eacute;put&eacute;e avoir valid&eacute; le  projet de cession soumis par le R&eacute;dacteur.</p>
<p>Le client pour lequel le r&eacute;dacteur r&eacute;dige ne  peut signer l'article &agrave; la place du r&eacute;dacteur. Il peut par contre en faire la  demande au r&eacute;dacteur par l'interm&eacute;diaire d'Edit-Place. Un accord &eacute;crit devra  &ecirc;tre sign&eacute; dans ce cas-l&agrave; entre les parties. Si le client contrevenait &agrave; cette  r&egrave;gle li&eacute;e au droit moral de l'auteur, il s'exposerait &agrave; des dommages et  int&eacute;r&ecirc;ts vis &agrave; vis du r&eacute;dacteur concern&eacute; </p>

<p>Article  4 - R&eacute;mun&eacute;ration du R&eacute;dacteur</p>
<p>Conform&eacute;ment  aux dispositions de l'article L.131-4 alin&eacute;a 1&deg;,2&deg;,3&deg; et 4&deg;, des articles &nbsp;L. 132-5, L132-6 et suivants du Code de la  Propri&eacute;t&eacute; Intellectuelle, les parties conviennent que l'Auteur, en contrepartie  de l'acceptation de sa(ses) contribution(s), percevra pour les documents intitul&eacute;s  :</p>
<p>&nbsp;</p>
<!--Article Details with AO-->
{$ArticlesDetailsWithAO}
<!--Ended-->
<p>&nbsp;</p>
<p>la  r&eacute;mun&eacute;ration suivante :</p>
<!--Article Details with Price-->
{$ArticlesDetailsWithPrice}
<!--Ended-->
<p>Cette  somme sera cr&eacute;dit&eacute;e sur le compte du R&eacute;dacteur dans les 30 jours suivants la  s&eacute;lection du Contenu.</p>
<p>Le  r&eacute;dacteur pourra ensuite la retirer &agrave; sa convenance d&egrave;s lors que son encours de  compte aura atteint le seuil minimal de retrait fix&eacute; ci-avant, soit la somme de  vingt (20) euros. Si le R&eacute;dacteur ne r&eacute;digeait plus de  Contenu s&eacute;lectionn&eacute; pendant un an sur le Service, le prix sera vers&eacute; quel que  soit son montant, dans un d&eacute;lai maximum de 30 jours, sur demande adress&eacute;e par  mail &agrave; Edit-Place. </p>
<p>Ces  reversements ne s'appliqueront qu'&agrave; compter de la s&eacute;lection dudit document,  dont le produit aura d&eacute;finitivement &eacute;t&eacute; encaiss&eacute; par la Soci&eacute;t&eacute;. Toute remise  en cause ou d&eacute;faut de paiement du Client relatives aux cessions de Contenu sur  le Service entra&icirc;neront le non versement du prix au R&eacute;dacteur par la Soci&eacute;t&eacute;. De convention expresse avec le Client, la Soci&eacute;t&eacute;  s'engage&nbsp; &agrave; transmettre au r&eacute;dacteur les  coordonn&eacute;es du Client d&eacute;faillant, de nature &agrave; permet<a name="_GoBack"></a>tre  au r&eacute;dacteur d'exercer ses voies de recours. </p>
<p>&nbsp;</p>
<p>Article  5 - Garanties donn&eacute;es par le R&eacute;dacteur</p>
<p>L'Auteur  garantit &agrave; la Soci&eacute;t&eacute; et au Client l'exercice paisible des droits c&eacute;d&eacute;s au  titre du pr&eacute;sent contrat.</p>
<p>Il  garantit &eacute;galement &agrave; la Soci&eacute;t&eacute; et au Client sa qualit&eacute; d'auteur de l'&oelig;uvre c&eacute;d&eacute;e  et il garantit que celle-ci ne fait &agrave; ce jour l'objet d'aucune contestation.</p>
<p>Au  cas o&ugrave; une contestation concernant les droits sur l'&oelig;uvre serait &eacute;mise par un  tiers, le R&eacute;dacteur s'engage &agrave; apporter &agrave; la Soci&eacute;t&eacute; et au Client, &agrave; sa  premi&egrave;re demande, tout son appui judiciaire.</p>
<p>Le  R&eacute;dacteur garantit &agrave; ce titre &agrave; la Soci&eacute;t&eacute; et au Client, la jouissance enti&egrave;re  et libre des droits c&eacute;d&eacute;s, contre tous troubles, revendications et &eacute;victions  quelconques.</p>
<p>Il  d&eacute;clare express&eacute;ment disposer des droits c&eacute;d&eacute;s par le pr&eacute;sent contrat, et que  l'&oelig;uvre n'a fait l'objet d'aucun contrat de cession exclusif ou non encore  valable.</p>
<p>Il  d&eacute;clare express&eacute;ment que l'&oelig;uvre n'entre pas dans le cadre d'un droit de  pr&eacute;f&eacute;rence, tel qu'il est d&eacute;sign&eacute; &agrave; l'article L. 132-4 du Code de la propri&eacute;t&eacute;  intellectuelle que l'auteur d&eacute;clare parfaitement conna&icirc;tre, accord&eacute;  ant&eacute;rieurement par lui &agrave; un &eacute;diteur.</p>
<p>Le  R&eacute;dacteur est &eacute;galement inform&eacute; que la d&eacute;couverte par la Soci&eacute;t&eacute; d'une  publication identique du pr&eacute;sent document par contrat de cession aupr&egrave;s d'une  autre soci&eacute;t&eacute; pourra donner lieu &agrave; r&eacute;siliation de plein droit du pr&eacute;sent  contrat, sur simple notification par tout moyen &agrave; la discr&eacute;tion d'Edit-Place et  ou du Client, et sans pr&eacute;judice des dommages et int&eacute;r&ecirc;ts que Edit-Place se  r&eacute;serve le droit de solliciter devant les juridictions comp&eacute;tentes.</p>
<p>L'auteur  garantit la Soci&eacute;t&eacute; et le Client contre toute action en contrefa&ccedil;on qui  r&eacute;sulterait de l'existence de contrats de cession de droits sur le pr&eacute;sent  document, non r&eacute;v&eacute;l&eacute;s &agrave; la Soci&eacute;t&eacute; &agrave; la signature des pr&eacute;sentes.</p>
<p>L'auteur  garantit que son &oelig;uvre est conforme &agrave; la l&eacute;gislation fran&ccedil;aise et toute autre  l&eacute;gislation applicable, et notamment les dispositions relatives &agrave; la  diffamation et l'injure, &agrave; la vie priv&eacute;e et au droit &agrave; l'image, &agrave; l'autorit&eacute; de  la justice, &agrave; la protection morale de la jeunesse, au respect de la pr&eacute;somption  d'innocence, &agrave; l'atteinte aux bonnes m&oelig;urs ou &agrave; la contrefa&ccedil;on.</p>
<p>Il  garantit en particulier que son &oelig;uvre ne comporte aucun emprunt - m&ecirc;me partiel  - &agrave; une autre &oelig;uvre, emprunt qui serait de nature &agrave; engager la responsabilit&eacute;  de la Soci&eacute;t&eacute; et/ou du Client.</p>
<p>En  cas de cession d'une &oelig;uvre dite de collaboration, le R&eacute;dacteur garantit &agrave; la  Soci&eacute;t&eacute; et au Client qu'il lui c&egrave;de d'un commun accord avec les autres  coauteurs les droits d'exploitation de l'&oelig;uvre commune. Il garantit &agrave; ce titre  &agrave; la Soci&eacute;t&eacute; et au Client l'accord express des coauteurs sur la cession de  droits conc&eacute;d&eacute;e.</p>
<p>Les  garanties susmentionn&eacute;es sont - de la commune intention des parties - une  condition essentielle et d&eacute;terminante du contrat sans laquelle la pr&eacute;sente  convention n'aurait pas &eacute;t&eacute; conclue.</p>
<p>En  cons&eacute;quence de cette garantie, l'auteur s'engage express&eacute;ment, en cas de  condamnations prononc&eacute;es &agrave; l'encontre de la Soci&eacute;t&eacute; et du Client par toutes  juridictions - notamment civiles ou p&eacute;nales - de r&eacute;gler ou rembourser  l'int&eacute;gralit&eacute; des sommes qui pourraient &ecirc;tre r&eacute;clam&eacute;es &agrave; la Soci&eacute;t&eacute; et/ou au  Client, quelles que soient leur nature (dommages et int&eacute;r&ecirc;ts, frais de  publication, d&eacute;pens, indemnit&eacute; due sur le fondement de l'article 700 du Nouveau  Code de Proc&eacute;dure Civile, etc.).</p>
<p>Les  obligations, abstentions, garanties ou tout autre fait cr&eacute;ateur de droits au  b&eacute;n&eacute;fice de la Soci&eacute;t&eacute; par le pr&eacute;sent contrat, tant implicites qu'explicites,  sont express&eacute;ment conf&eacute;r&eacute;es par le R&eacute;dacteur tant &agrave; la Soci&eacute;t&eacute; qu'au Client, &agrave;  l'exclusion de la cession des droits d'exploitation, c&eacute;d&eacute;e &agrave; titre exclusif au  Client.<br>
  La  Soci&eacute;t&eacute; quant &agrave; elle ne souscrit aucune obligation de quelque nature que ce  soit &agrave; l&rsquo;&eacute;gard de l'Auteur, le Client &eacute;tant seul responsable de l'exploitation  des droits c&eacute;d&eacute;s conform&eacute;ment au pr&eacute;sent Contrat, et selon les modalit&eacute;s  financi&egrave;res d&eacute;finies. </p>
<p>Article  6 - Clause r&eacute;solutoire</p>
<p>Faute  d'ex&eacute;cution de l'une quelconque des stipulations des pr&eacute;sentes, et quinze jours  apr&egrave;s l'envoi d'une lettre recommand&eacute;e avec accus&eacute; de r&eacute;ception rest&eacute;e sans  effet, la pr&eacute;sente convention sera r&eacute;solue de plein droit sans qu'il soit  besoin d'une formalit&eacute; judiciaire quelconque, aux torts et griefs de la partie  d&eacute;faillante, si bon semble &agrave; l'autre partie, sous r&eacute;serve de tous dommages et  int&eacute;r&ecirc;ts &eacute;ventuels.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>Article  7 - Ayants droit</p>
<p>Le  pr&eacute;sent contrat, dans son int&eacute;gralit&eacute;, engage les h&eacute;ritiers et tous ayants  droit du R&eacute;dacteur, qui devront, dans la mesure du possible, se faire  repr&eacute;senter aupr&egrave;s de la Soci&eacute;t&eacute; et/ou du Client par un mandataire commun.</p>
<p>&nbsp;</p>
<p>Article  8 - Responsabilit&eacute;<br>
  De  convention expresse entre les parties, l&rsquo;&eacute;ventuelle responsabilit&eacute; de la  Soci&eacute;t&eacute; au titre du contrat ne pourra &ecirc;tre engag&eacute;e que sur faute prouv&eacute;e, et  dans un d&eacute;lai de 12 (douze) mois suivant l'entr&eacute;e en vigueur du pr&eacute;sent  contrat. Les &eacute;ventuels dommages et int&eacute;r&ecirc;ts dus par la Soci&eacute;t&eacute; ne sauraient  exc&eacute;der la somme re&ccedil;ue par le R&eacute;dacteur au titre du contrat.<br>
  &nbsp;<br>
  Article  9 - Entr&eacute;e en vigueur du contrat</p>
<p>Ce  contrat de cession est valid&eacute; par le R&eacute;dacteur &agrave; la date de soumission du Contenu  sur le Service, mais son entr&eacute;e en vigueur est conditionn&eacute;e par la s&eacute;lection du  document par le Comit&eacute; de lecture, conform&eacute;ment aux Conditions G&eacute;n&eacute;rales  d'Utilisation, que le R&eacute;dacteur a express&eacute;ment accept&eacute;es lors de la cr&eacute;ation de  son compte pour acc&eacute;der au Service.</p>
<p>La  notification de la s&eacute;lection du Contenu du R&eacute;dacteur est promptement effectu&eacute;e  par la Soci&eacute;t&eacute; par courrier &eacute;lectronique et constitue la date d'entr&eacute;e en  vigueur du pr&eacute;sent contrat.</p>
<p>De  convention expresse entre les Parties, le R&eacute;dacteur reconnait que les donn&eacute;es  figurant sur les syst&egrave;mes informatiques de la Soci&eacute;t&eacute;, ainsi que les contrats  et courriers &eacute;lectroniques conserv&eacute;s sur les syst&egrave;mes informatiques de la  Soci&eacute;t&eacute; font foi entre les parties, sauf preuve contraire constat&eacute;e par  huissier.</p>
<p>Article  10 - Droit applicable - Attribution de comp&eacute;tence</p>
<p>Le  pr&eacute;sent contrat est soumis au droit fran&ccedil;ais.</p>
<p>Pour  tout litige n&eacute; de l'interpr&eacute;tation ou de l'ex&eacute;cution du pr&eacute;sent contrat, il est  fait attribution expresse de juridiction aux tribunaux comp&eacute;tents de Paris.</p>
<p>&nbsp;</p>
<p>Fait  &agrave; Paris,&nbsp; le {$startDate|date_format:"%d/%m/%Y"}</p>
<!--
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>Signature  du R&eacute;dacteur</p>-->
<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
		</div>
		<div class="row-fluid">
			<div id = "alert_placeholder"></div>
			<form class="form-horizontal" method="POST" action="/cart/save-participation">
				<div class="control-group">
					<label class="control-label span6 offset1" for="contract">j'accepte les termes du pr&eacute;sent  contrat</label>
					<div class="controls span5">
						<label class="radio inline">
							<input type="radio" name="contract" value="yes">
							Oui
						</label>
						<label class="radio inline">
							<input type="radio" name="contract" value="no">
							Non
						</label>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label span6 offset1" for="contract">Je ne d&eacute;marre pas la r&eacute;daction/correction de l'article tant qu'Edit-place ou le client ne me confirme pas que j'ai bien &eacute;t&eacute; s&eacute;lectionn&eacute;</label>
					<div class="controls span5">
						<label class="radio inline">
							<input type="radio" name="contract1" value="yes">
							Oui
						</label>
						<label class="radio inline">
							<input type="radio" name="contract1" value="no">
							Non
						</label>
						<br><br><br><a class="btn" href="/cart/cart-selection">Retour</a> <button class="btn btn-primary" id="contract-submit" name="submit">Valider</button>
					</div>
				</div>
				<input type="hidden" name="maxpage" value="2"/>
			</form>
			<div id = "confirmDiv"></div>
			
			
		</div>
	</div>
</div>