{literal}
<script>
    $('#starval1').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
      //  score     : {/literal}{$s1marks[0]}{literal},
        target     : '#precision-target1',
        targetKeep : true,
        targetType : 'number'
    });
    $('#starval2').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
      //  score     : {/literal}{$s1marks[1]}{literal},
        target     : '#precision-target2',
        targetKeep : true,
        targetType : 'number'
    });
    $('#starval3').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
      //  score     : {/literal}{$s1marks[2]}{literal},
        target     : '#precision-target3',
        targetKeep : true,
        targetType : 'number'
    });
    $('#starval4').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
      //  score     : {/literal}{$s1marks[3]}{literal},
        target     : '#precision-target4',
        targetKeep : true,
        targetType : 'number'
    });
    $('#starval5').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
      //  score     : {/literal}{$s1marks[4]}{literal},
        target     : '#precision-target5',
        targetKeep : true,
        targetType : 'number'
    });

    $('#starclose1').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
        //  score     : {/literal}{$s1marks[0]}{literal},
        target     : '#precision-target-close1',
        targetKeep : true,
        targetType : 'number'
    });
    $('#starclose2').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
        //  score     : {/literal}{$s1marks[1]}{literal},
        target     : '#precision-target-close2',
        targetKeep : true,
        targetType : 'number'
    });
    $('#starclose3').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
        //  score     : {/literal}{$s1marks[2]}{literal},
        target     : '#precision-target-close3',
        targetKeep : true,
        targetType : 'number'
    });
    $('#starclose4').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
        //  score     : {/literal}{$s1marks[3]}{literal},
        target     : '#precision-target-close4',
        targetKeep : true,
        targetType : 'number'
    });

    $('#starclose5').raty({
        scoreName : 'entity_score',
        number    : 5,
        path: '/FO/images/',
        //  score     : {/literal}{$s1marks[4]}{literal},
        target     : '#precision-target-close5',
        targetKeep : true,
        targetType : 'number'
    });
</script>
{/literal}

{if $missionDetails | @count gt 0}
	{foreach from=$missionDetails item=article name=details}
		<ul id="correctTab" class="nav nav-tabs">
			<li class="active"><a href="#upload"><i class="icon-upload"></i> Valider</a></li>
			{if $article.missiontest eq 'no'}
				<li class=""><a href="#ask4update"><i class="icon-refresh"></i> Demander une reprise</a></li>
				<li class=""><a href="#refuse"><i class="icon-thumbs-down"></i> Refus d&eacute;finitif</a></li>
			{/if}
		</ul>

		<div class="tab-content"  style="height:600px;">
			<!--  Validate -->
			<div id="upload" class="tab-pane active">
				<div class="row-fluid" style="padding:0px 0px 0px 0px;">
				<form name="sendarticle" action="/contrib/send-corrector-article" enctype="multipart/form-data" method="POST" id="v_corrector_form">
                    <div class="alert alert-warning span12">
					<!--<i class="icon-info-sign"></i>-->
					<img src="/FO/images/info_24.png" style="float:left"/>
							<p class="span11">Vous souhaitez valider l'article de <strong>{$article.writer_name}</strong>. Tout d'abord, merci d'<b>envoyer l'article corrig&eacute;</b> en cliquant sur le bouton ci-dessous.<br/>
                        Ensuite, merci de le <b>noter</b> sur chaque crit&egrave;re et de lui <b>laisser un commentaire</b>. Votre commentaire sera relu par nos &eacute;quipes.</p></div>
                    <div class="span12">
						<div id="file-management" class="file-management-cont clearfix">
							<table class="table mod span11 offset1" style="margin-left: 4%">
								<thead>
									<tr>
										<th class="span7">Article &agrave; corriger</th>
										<th class="span1">R&eacute;dacteur</th>
										<th class="span2">Modification</th>
										<th class="span1">Poids</th>
										<th class="span2"></th>

									</tr>
								</thead>
								<tbody>
								{foreach item=varticle from=$AllVersionArticles name=articledetails}
									<tr>
										<td class="span7"><i class="icon-file"></i> <a href="/contrib/download-version-article?processid={$varticle.id}">{$varticle.article_name}</a></td>
										<td class="span2">{$varticle.first_name}</td>
										<td class="span2">{$varticle.article_sent_at|date_format:"%d/%m/%Y"}</td>
										<td class="span1 muted">{$varticle.file_size}</td>
										<td class="span2"><a href="/contrib/download-version-article?processid={$varticle.id}" data-original-title="T&eacute;l&eacute;charger" rel="tooltip" class="btn btn-small"><i class="icon-download"></i></a></td>
									</tr>
								{/foreach}
								</tbody>
							</table>

							<div class="span12 pull-center">
								<div class="empty-box"></div>
								<h4>Cette box est vide</h4>
								<p>Ajoutez ci-dessous les articles que vous avez corrig&eacute;s pour cette mission</p>
                                <input type="hidden" id="client_id" name="client_id" value="{$clientId}" />

                                <span class="btn btn-primary fileinput-button">
                                    <i class="icon-plus icon-white"></i>
                                    <span id="filename">Ajouter un fichier...</span>
                                <input type="file" name="file_{$article.participationId}" id="file_{$article.participationId}">

                                </span>

							</div>
						</div>
						<hr>
                            <div class="span3">
                                <div class="mod">
                                    <div class="editor-container">
                                        <h4><i class="icon-star"></i> Noter le r&eacute;dacteur</h4>
                                        <img alt="{$article.writer_name}" src="{$article.writer_pic_profile}">
                                        <p class="editor-name">{$article.writer_name}.</p>
                                    </div>

                                    <div style="outline: thin dotted ;  "></div>
                                {if $refreasons neq 'NO'}
                                    {foreach from=$refreasons key=reasons_key item=reasons_item name=reasons_loop}
                                    <div class="span12 form-inline"><span class="span6" style="word-wrap:break-word">{if $reasons_item neq 'N'}{$reasons_item}{else}Note globale{/if}</span>
                                        <div class="span7 starmarksvalid pull-right" id="starval{$smarty.foreach.reasons_loop.index+1}" ></div>
                                        <input type="hidden" id="reasonId{$smarty.foreach.reasons_loop.index+1}" value="{$reasons_key}" />
                                        <span id="precision-target{$smarty.foreach.reasons_loop.index+1}" class="precision_valid hide"></span>
                                    </div>
                                    {/foreach}
                                {else}
                                    <div class="span12 form-inline"><span class="span6" style="word-wrap:break-word">Note globale</span>
                                        <div class="span7 starmarksvalid pull-right" id="starval1" ></div>
                                        <input type="hidden" id="reasonId1" value="{$reasons_key}" />
                                        <span id="precision-target1" class="precision_valid hide"></span>
                                    </div>
                                {/if}
                                    <input type="hidden" id="marksvald" name="marksvald" vlaue="" />
                                    <input type="hidden" id="marksvaldwithreason" name="marksvaldwithreason"  />
                                </div>
                            </div>
							<div class="well span8" id='message_box_corr'>
								<div class="icon_corrector pull-right"></div>
								<p>Bonjour, {$article.writer_name}</p>

								<textarea name="corrector-comment" id="valid_comments" class="textarea-validate input-block-level" rows="12" placeholder="Ex : Votre article correspondait tout &agrave; fait &agrave; notre demande. N'h&eacute;sitez pas &agrave; postuler &agrave; d'autres annonces."></textarea>
								<p class="clearfix"><i class="icon-asterisk"></i> <strong>Commentaire ajout&eacute; automatiquement</strong><br>
                                    L'&eacute;quipe d'Edit-place vous remercie de votre confiance.</p>
							</div>
                            <div id="alert_approve_placeholder" class="span11"></div>
							<div class="clearfix pull-right span3">
								<button aria-hidden="true" data-dismiss="modal" class="btn" type="button">Annuler</button>
                                <button class="btn btn-primary" id="approve" name="approve" type="button">Envoyer</button>
							</div>
					</div>
					<input type="hidden" id="article_id" name="article_id" value="{$article_id}" />
					<input type="hidden" id="cparticipation_id" name="cparticipation_id" value="{$article.participationId}" />
					<input type="hidden" id="a_corrector_reparticipation" name="corrector_reparticipation" value="" />
					<input type="hidden" name="function" value="approve" id="function">
				</form>
				</div>
			</div>
			<!--  Stop, validate -->

			{if $article.missiontest eq 'no'}
			<!-- update -->
			<div id="ask4update" class="tab-pane">
				<div class="row-fluid">
				<form name="sendarticle" action="/contrib/send-corrector-article" enctype="multipart/form-data" method="POST" id="r_corrector_form">
					<div class="span12" style="padding:0px 10px 0px 10px;">
                        <div class="alert alert-warning span12">
                            <!--<i class="icon-info-sign"></i>-->
							<img src="/FO/images/info_24.png" style="float:left"/>
							<p class="span11">Vous souhaitez demander une reprise &agrave; <strong>{$article.writer_name}</strong>.<br/>
                            Merci de <b>s&eacute;lectionner les raisons de votre refus </b>parmi la liste ci-dessous et de <b>compl&eacute;ter</b> si n&eacute;cessaire. Votre commentaire sera relu par nos &eacute;quipes.</p>
                        </div>
                            <div class="span3" style="margin-left:0px">
                                <div class="mod">
                                    <p style="font-size:20px;text-align:center"><b>Raisons du refus</b></p>
									<hr style="border-top: dotted 1px;" />
                                    <div class="editor-container" style="text-align:left;padding-top:0px">
                                        {foreach item=template from=$refuseTemplates name=refuseTemplates}
                                        <label class="checkbox">
                                            <input type="checkbox" name="refuse_template[]" id="refuse_template_{$template.identifier}" value="{$template.identifier}">{$template.title}
                                        </label>
                                        {/foreach}
                                    </div>
                                </div>
                            </div>
							<div class="well span8">

								<div class="icon_corrector pull-right"></div>
								<p>Bonjour, {$article.writer_name}</p>

								<textarea name="corrector-comment" id="refuse_comments" class="textarea-ask4update input-block-level" rows="12" placeholder="Ex : Vous avez oubli&eacute; de mettre les mots-cl&eacute; correspondant &agrave; votre lot. Merci de reprendre vos articles."></textarea>
								<p class="clearfix"><i class="icon-asterisk"></i> <strong>Commentaire ajout&eacute; automatiquement &agrave; la demande de reprise</strong><br> Vous avez 24 heures pour nous faire parvenir vos articles modifi&eacute;s. Nous vous rappelons que si les consignes ne sont pas respect&eacute;es, nous pouvons vous demander de modifier  votre article de nouveau. Nous faisons jusqu'&agrave; 2 aller/retour. Au troisi&egrave;me refus l'article sera automatiquement remis en ligne sur la plateforme et l'article ne pourra &ecirc;tre r&eacute;tribu&eacute;.</p>
							</div>
							<div id="alert_disapprove_placeholder" class="span11"></div>
							<div class="clearfix pull-right">
								<button aria-hidden="true" data-dismiss="modal" class="btn" type="button">Annuler</button>
								<button class="btn btn-primary" name="disapprove" id="disapprove" type="button">Envoyer</button>
							</div>
							<input type="hidden" id="article_id" name="article_id" value="{$article_id}" />
							<input type="hidden" id="cparticipation_id" name="cparticipation_id" value="{$article.participationId}" />
							<input type="hidden" id="d_corrector_reparticipation" name="corrector_reparticipation" value="" />
							<input type="hidden" name="function" value="disapprove" id="function">
					</div>
				</form>
				</div>
			</div>
			<!-- stop, update -->

			<!--  Refus -->
			<div id="refuse" class="tab-pane">
				<div class="row-fluid">
				<form name="sendarticle" action="/contrib/send-corrector-article" enctype="multipart/form-data" method="POST" id="c_corrector_form">
					<div class="span12" style="padding:0px 10px 0px 10px;">
                        <div class="alert alert-warning span12"><!--<i class="icon-info-sign"></i>-->
							<img src="/FO/images/info_24.png" style="float:left"/>
							<p class="span11">Vous souhaitez refuser d&eacute;finitivement l'article de <strong>{$article.writer_name}</strong>.<br/>Merci de le <b>noter</b> sur chaque crit&egrave;re ci-dessous. Merci de lui <b>laisser un commentaire</b> ci-contre. Votre commentaire sera relu par nos &eacute;quipes.</p></div>
                        <div class="span3" style="margin-left:0px">
                            <div class="mod">
                                <div class="editor-container">
                                    <h4><i class="icon-star"></i> Noter le r&eacute;dacteur</h4>
                                    <img alt="{$article.writer_name}" src="{$article.writer_pic_profile}">
                                    <p class="editor-name">{$article.writer_name}.</p>
                                </div>
                                <div style="outline: thin dotted ;  "></div>
                                <!--<span class="badge"><span id="precision-target_c"></span>/10</span>
                                <div id="star"></div>-->
                        {if $refreasons neq 'NO'}
                                {foreach from=$refreasons key=reasons_key item=reasons_item name=reasons_loop}
                                <div class="span12 form-inline" ><span class="span6" style="word-wrap:break-word">{if $reasons_item neq 'N'}{$reasons_item}{else}Note globale{/if}</span>
                                    <div class="span7 starmarksclose pull-right" id="starclose{$smarty.foreach.reasons_loop.index+1}" ></div>
                                    <input type="hidden" id="reasonId-close{$smarty.foreach.reasons_loop.index+1}" value="{$reasons_key}" />
                                    <span id="precision-target-close{$smarty.foreach.reasons_loop.index+1}" class="precision_close hide"></span>
                                </div>
                                {/foreach}
                        {else}
                        <div class="span12 form-inline" ><span class="span6" style="word-wrap:break-word">Note globale</span>
                            <div class="span7 starmarksclose pull-right" id="starclose1" ></div>
                            <input type="hidden" id="reasonId-close1" value="{$reasons_key}" />
                            <span id="precision-target-close1" class="precision_close hide"></span>
                        </div>
                        {/if}
                                <input type="hidden" id="marksclose" name="marksclose" vlaue="" />
                                <input type="hidden" id="marksclosevaldwithreason" name="marksclosevaldwithreason"  />
                            </div>
                            <!--<div class="mod">
                                <div class="editor-container" style="text-align:left;">
                                    {foreach item=template from=$refuseTemplates name=refuseTemplates}
                                    <label class="checkbox">
                                        <input type="checkbox" name="close_template[]" id="close_template_{$template.identifier}" value="{$template.identifier}">{$template.title}
                                    </label>
                                    {/foreach}
                                </div>
                            </div>-->
                        </div>
                        <div class="well span8">
                            <div class="icon_corrector pull-right"></div>
                            <p>Bonjour, {$article.writer_name}</p>

                            <textarea name="corrector-comment" id="close_comments" class="textarea-refuse input-block-level" rows="12" placeholder="Ex : Vous avez oubli&eacute; de mettre les mots-cl&eacute; correspondant &agrave; votre lot. Merci de reprendre vos articles."></textarea>
                            <p class="clearfix"><i class="icon-asterisk"></i> <strong>Commentaire ajout&eacute; automatiquement</strong><br>
                                L'&eacute;quipe d'Edit-place vous remercie d'avoir fait confiance. Malheureusement la nouvelle version de l'article n'est toujours pas satisfaisante.<br>
                                L'article est remis en ligne sur la plateforme. La pr&eacute;sente production ne vous sera donc pas r&eacute;mun&eacute;r&eacute;e.<br>Cordialement</p>
                        </div>
                        <div id="alert_closed_placeholder" class="span11"></div>
                        <div class="clearfix pull-right">
                            <button aria-hidden="true" data-dismiss="modal" class="btn" type="button">Annuler</button>
                            <button class="btn btn-primary" name="closed" id="closed" type="button">Envoyer</button>
                        </div>
					</div>
					<input type="hidden" id="article_id" name="article_id" value="{$article_id}" />
					<input type="hidden" id="cparticipation_id" name="cparticipation_id" value="{$article.participationId}" />
					<input type="hidden" id="c_corrector_reparticipation" name="corrector_reparticipation" value="" />
					<input type="hidden" name="function" value="closed" id="function">
				</form>
				</div>

			</div>
			<!-- stop, refus -->
			{/if}
			<div id = "confirmDiv"></div>
		</div>

		<a class="pull-right btn btn-small disabled anchor-top scroll" href="#brand"><i class="icon-arrow-up"></i></a>
	{/foreach}
{/if}
<!--///show loading time for file uploading ///-->
<div id="loading" class="modal hide fade" tabindex="-1" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 >Analyse du fichier en cours</h3>
    </div>
    <div class="modal-body">
        <h3>Transfert en cours...
            <img src="/FO/images/progressbar.gif"></h3>
    </div>
</div>
<!--///show loading time for file uploading ///-->
<div id="wlblresult" class="modal container hide fade" tabindex="-1" >
</div>
<div id="wlblalert" class="modal hide fade" tabindex="-1" >
    <div class="modal-header">
        <button type="button" id="reload" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Alerte</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="form-group pull-center">

    </div>
    <div class="span1" style="height:5px;"></div>
</div>
{literal}
<script>

// active tab
$('#correctTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    })

	$('#correctTab a:first').tab('show');


 // call write email function
	$('.textarea-ask4update').wysihtml5({locale: "fr-FR"});
	$('.textarea-refuse').wysihtml5({locale: "fr-FR"});
	$('.textarea-validate').wysihtml5({locale: "fr-FR"});

	$(".scroll").click(function(event){
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});

 // placeholder mgt for old browsers
    $('input, textarea').placeholder();

$('#star').raty({
  scoreName : 'entity_score',
  number    : 10,
  path: '/FO/images/',
  target     : '#precision-target_c',
  targetKeep : true,
  targetType : 'number'
});

$('#star-2').raty({
  scoreName : 'entity_score',
  number    : 10,
  path: '/FO/images/',
  target     : '#precision-target',
  targetKeep : true,
  targetType : 'number'
});


$(function(){

    $('input[type=file]').change(function(e){
        $in=$(this);
        $("#filename").html($in.val());
        $('html,body').animate({scrollTop:200}, 500);
        $('.tab-content').animate({scrollTop:550}, 500);
    });

    bootstrap_alert = function() {}
	bootstrap_alert.error = function(div,message) {
		$('#'+div).html('<div class="alert  alert-error"><button data-dismiss="alert" class="close" type="button">&times;</button><span><ul>'+message+'</ul></span></div>')
	}

    $("#approve,#disapprove,#closed").click(function(){
		var error=0;
        var reasons_count = 0;
		var msg='';
		var id_name=$(this).attr("id");
		if(id_name=='approve')
		{
			var	valid_comments=$("#valid_comments");
			var comments=valid_comments.val();
				comments = comments.replace(/(<([^>]+)>)/ig,"");
				comments = comments.replace(/&nbsp;/gi,"");

            $("[id^=file_]").each(function(i) {
				var attachment=$(this).val();
                var clientId = $('#client_id').val();

                if(attachment=='' || $.trim(attachment).length==0)
                {
                    msg+="Merci d'uploader votre article ou vos articles <br>";
                    error++;
                }
             });
			if($.trim(comments).length <1 || comments=="")
			{
				msg+="Merci d'ins&eacute;rer un commentaire<br>";
				error++;
			}
            var score = [];
            $(".precision_valid").each(function(i){
                reasons_count++;
                if($(this).text() != '')
                    score.push($(this).text());

            });
			/*var score = $.map($('#v_corrector_form input:hidden[name^="entity_score"]'),function(i) {
				return (i.value);
			});
			if(!score || score=='')
			{
				msg+='Merci de donner une note au r&eacute;dacteur (sous sa fiche profil en haut &agrave; droite)<br>';
				error++;
			}*/
            if(score.length != reasons_count)
            {
                msg+="N'oubliez pas de renseigner toutes les notes que vous souhaitez donner au r&eacute;dacteur<br>";
                error++;
            }
			if(error==0){
                $("#v_corrector_form").submit();
            }
            else
                bootstrap_alert.error('alert_approve_placeholder',msg);
        }
		else if(id_name=='disapprove')
		{
			var artId = $('#article_id').val();
			var partId = $('#cparticipation_id').val();
			var	refuse_comments=$("#refuse_comments");
			var comments=refuse_comments.val();
				comments = comments.replace(/(<([^>]+)>)/ig,"");
				comments = comments.replace(/&nbsp;/gi,"");

			if($.trim(comments).length <1 || comments=="")
			{
				msg+="Merci d'ins&eacute;rer un commentaire<br>";
				error++;
			}

			var $b =$("[id^=refuse_template_]");// $('input[name=refuse_template[]]');
			var countselected = $b.filter(':checked').length;
			if(countselected == 0)
			{
				msg+='Merci de s&eacute;lectionner au moins une raison pour laquelle vous demandez la reprise  ou le refus dans la colonne de droite';
				bootbox.alert("Merci de s&eacute;lectionner au moins une raison pour laquelle vous demandez la reprise  ou le refus dans la colonne de droite");
				error++;
			}
			if(error==0)
			{
				var target_page = "/Contrib/getconfirmbox?artId="+artId+"&crtpartiId="+partId+"&button=disapprove";
				 $.post(target_page, function(data){   //alert(data);
					//var r=confirm(data);
					$("#confirmDiv").confirmModal({
						heading: 'Alerte',
						body: data,
						callback: function () {
							$("#d_corrector_reparticipation").val('yes');
							$("#r_corrector_form").submit();
						}
					});
				});
			}
			else
				bootstrap_alert.error('alert_disapprove_placeholder',msg);

		}
		else if(id_name=='closed')
		{
			var artId = $('#article_id').val();
			var partId = $('#cparticipation_id').val();

			var	close_comments=$("#close_comments");
			var comments=close_comments.val();
				comments = comments.replace(/(<([^>]+)>)/ig,"");
				comments = comments.replace(/&nbsp;/gi,"");

			if($.trim(comments).length <1 || comments=="")
			{
				msg+="Merci d'ins&eacute;rer un commentaire<br>";
				error++;
			}
            var score = [];
            $(".precision_close").each(function(i){
                reasons_count++;
                if($(this).text() != '')
                    score.push($(this).text());
            });
			/*var score = $.map($('#c_corrector_form input:hidden[name^="entity_score"]'),function(i) {
				return (i.value);
			});
			if(!score || score=='')
			{
				msg+='Merci de donner une note au r&eacute;dacteur (sous sa fiche profil &agrave; droite)<br>';
				error++;
			}*/
            if(score.length != reasons_count)
            {
                msg+="N'oubliez pas de renseigner toutes les notes que vous souhaitez donner au r&eacute;dacteur<br>";
                error++;
            }
			/*var $b =$("[id^=close_template_]");// $('input[name=close_template]');
			var countselected = $b.filter(':checked').length;
			if(countselected == 0)
			{
				msg+='Merci de s&eacute;lectionner au moins une raison pour laquelle vous demandez la reprise  ou le refus dans la colonne de droite';
				bootbox.alert("Merci de s&eacute;lectionner au moins une raison pour laquelle vous demandez la reprise  ou le refus dans la colonne de droite");
				error++;
			}*/

			if(error==0)
			{
				 var target_page = "/Contrib/getconfirmbox?artId="+artId+"&crtpartiId="+partId+"&button=closed";
				 $.post(target_page, function(data){   //alert(data);
					//var r=confirm(data);
						$("#confirmDiv").confirmModal({
						heading: 'Alerte',
						body: data,
						callback: function () {
							$("#c_corrector_reparticipation").val('yes');
							$("#c_corrector_form").submit();
						}
					});

				});
			}
			else
				bootstrap_alert.error('alert_closed_placeholder',msg);

		}

	});

	//refuse template content
	$("[id^=refuse_template_]").die('click').live('click', function() {

		var template=$(this).attr('id').split("_");
		var template_id=template[2];

		if($(this).is(":checked"))
		{
			//alert(template_id);
			var target_page = "/contrib/get-template-content?template_id="+template_id;
			$.get(target_page, function(data){   //alert(data);
				if(data)
				{
					var	refuse_comments=$("#refuse_comments").val();
					//$("#refuse_comments").html(refuse_comments + data);
					$('.textarea-ask4update').data("wysihtml5").editor.setValue(refuse_comments + data);
				}
			});
		}
		else
		{
			var $currentHtml = $('<div>').append($("#refuse_comments").val());
			$currentHtml.find('.template_content_'+template_id).remove();
			$('.textarea-ask4update').data("wysihtml5").editor.setValue($currentHtml.html());
		}

	});
	//close template content
	$("[id^=close_template_]").die('click').live('click', function() {

		var template=$(this).attr('id').split("_");
		var template_id=template[2];

		if($(this).is(":checked"))
		{
			//alert(template_id);
			var target_page = "/contrib/get-template-content?template_id="+template_id;
			$.get(target_page, function(data){   //alert(data);
				if(data)
				{
					var	close_comments=$("#close_comments").val();
					//$("#close_comments").html(close_comments + data);
					$('.textarea-refuse').data("wysihtml5").editor.setValue(close_comments + data);
				}
			});
		}
		else
		{
			var $currentHtml = $('<div>').append($("#close_comments").val());
			$currentHtml.find('.template_content_'+template_id).remove();
			$('.textarea-refuse').data("wysihtml5").editor.setValue($currentHtml.html());
		}

	});


});
$(".starmarksvalid").click(function(){
    // var marks = [];
    var marks = 0;
    var marksparreason = [];
    var total = 0;
    $(".starmarksvalid").each(function(i) {
        i = i+1;
        // marks.push($("#precision-target"+i).text());
        var selmarks = Number($("#precision-target"+i).text());
        marks += selmarks;
        marksparreason.push($("#reasonId"+i).val() + "|" +selmarks);

        //marksparreason = $("#reasonId"+i).val() + "|" +selmarks + "," + marksparreason;
        total = i ;
    });
    var avgmarks =((marks/total)*2);
    $("#givenmarks").html(avgmarks);
    $("#totalmarks").html("/"+(total*5));
    $("#marksvald").val(avgmarks);
    $("#marksvaldwithreason").val(marksparreason.join(', '));

});
$(".starmarksclose").click(function(){
    // var marks = [];
    var marks = 0;
    var marksparreason = [];
    var total = 0;
    $(".starmarksclose").each(function(i) {
        i = i+1;
        // marks.push($("#precision-target"+i).text());
        var selmarks = Number($("#precision-target-close"+i).text());
        marks += selmarks;
        marksparreason.push($("#reasonId-close"+i).val() + "|" +selmarks);

        //marksparreason = $("#reasonId"+i).val() + "|" +selmarks + "," + marksparreason;
        total = i ;
    });
     var avgmarks = ((marks/total)*2);
    $("#givenmarks").html(avgmarks);
    $("#totalmarks").html("/"+(total*5));
    $("#marksclose").val(avgmarks);
    $("#marksclosevaldwithreason").val(marksparreason.join(', '));
});


</script>
{/literal}
