{literal}
<script type="text/javascript">
$("#menu_ongoing").addClass("active");
$('body').removeClass('homepage');
$('body').addClass('mission');
</script>
{/literal}
<div class="container">
<br>
{if $missionDetails | @count gt 0}
	{foreach from=$missionDetails item=article name=details}
	<ul class="breadcrumb">
		<li><a href="/contrib/home">Accueil</a> <span class="divider">/</span></li>
		<li><a href="/contrib/ongoing">Mes participations</a> <span class="divider">/</span></li>
		<li class="active">{$article.title}</li>
	</ul> 
	
	<!-- start, Summary -->
	<section id="summary">
		<div class="row-fluid">
			<div class="span7">
				{if $article.price_corrector OR $article.crt_participate_id }
					{if $article.missiontest eq 'yes'}
						<span class="label label-mission-test">Mission de correction test</span>
					{else}
						<span class="label label-correction">Mission Correction</span>
					{/if}
				{elseif $article.ao_type eq 'premium'}
					{if $article.missiontest eq 'yes'}
						<span class="label label-mission-test">Mission Test</span>
					{else}
						<span class="label label-premium">Mission Premium</span>
					{/if}
				{else}	
					{if $article.missiontest eq 'yes'}
						<span class="label label-mission-test">Mission Test</span>
					{else}
						<span class="label label-quote">Mission Libert&eacute;</span>
					{/if}
				{/if}	
				<h1>{$article.title}</h1>
			</div>
			<div class="span2 stat">
				<p>Date de livraison</p>
				<!-- add classname "less24" if time is < 24h  -->
				<!-- p class="num-large less24">Livrée</p-->
				<p class="num-large less24">
					Valid&eacute;e
				</p>
			</div>
			<div class="span2 stat">
				<p>Tarif</p>
				{if $article.price_user!=''}
					<p class="num-large">{$article.price_user|zero_cut:2} &euro;</p>
				{elseif $article.price_corrector!=''}
					<p class="num-large">{$article.price_corrector|zero_cut:2} &euro;</p>
				{/if}	
			</div>
			<div class="span1 stat">
				<div class="icon-comment-large new" id="comment_count"><a href="#comment" class="scroll">{$commentDetails|@count}</a></div>
			<!--  to active if new comment, add classname "new" -->
			<!--div class="icon-comment-large new"><a href="#comment">3</a></div-->
			</div>
		</div>
	</section>
	<!-- end, summary --> 
 
	<div class="row-fluid"> 
		<div class="span9">
			<section id="file-management">
				<div class="row-fluid">
					<div class="span5">
						<h3><i class="outbox pull-left">
							{if $AllVersionArticles | @count gt 0}	
								<span class="badge badge-warning">{$AllVersionArticles|@count}</span>
							{else}
								<span class="badge">0</span>
							{/if}	
						</i>Edit-place box</h3>
					</div>
					<div class="span7">
						<!-- call to action set -->
						<div class="btn-group pull-right">
							<!--<button data-original-title="Demander un d&eacute;lai suppl&eacute;mentaire" rel="tooltip" class="btn"><i class="icon-time"></i><sup>+</sup></button>-->
							<button data-original-title="Aide" rel="tooltip" class="btn"><i class="icon-question-sign"></i></button>
						</div>
					</div>
				</div>
				<div class="row-fluid file-management-cont">                           
					<table style="margin-left: 4%" class="table mod span11 offset1">
						<thead>
						<tr>
							<th class="span6">Fichier</th>
							<th class="span4" style="text-align:center">Date</th>
							<th class="span2">Poids</th>
						</tr>
						</thead>
						<tbody>
							{if $AllVersionArticles | @count gt 0}
								{foreach item=versionarticle from=$AllVersionArticles name=articledetails}
									<tr><td class="span6"><i class="icon-file"></i>
									<a href="{if $versionarticle.file_exists eq 'yes'}/contrib/download-version-article?processid={$versionarticle.id}{else}#{/if}">{$versionarticle.article_name}</a></td>
									<td class="span4 muted" style="text-align:center">{$versionarticle.article_sent_at|date_format:"%d/%m/%Y %H:%M"}</td>
									<td class="span2 muted">{$versionarticle.file_size}</td></tr>
								{/foreach}
							
							{else}
								<tr><td colspan="4"></td></tr>
							{/if}	
						</tbody>
					</table>					
				</div>
			</section>
			<section id="a_o">
				<div class="mod">
					<div class="summary clearfix">
						<h4>D&eacute;tails du projet</h4>
						<ul class="unstyled">
							<li><strong>Appel &agrave; r&eacute;daction</strong> <span class="bullet">&#9679;</span></li>
							<li> Langue : <img class="flag flag-{$article.language}" src="/FO/images/shim.gif"> <span class="bullet">&#9679;</span></li>
							<li>Cat&eacute;gorie : {$article.category} <span class="bullet">&#9679;</span></li>
							<li>Nb. mots : {$article.num_min} - {$article.num_max}
							<!--<span class="bullet">&#9679;</span></li>
							<li><a href="#comment" class="scroll" id="comment_count_1"><i class="icon-comment"></i> {$commentDetails|@count}</a></li>-->
							{if $article.spec_exists eq 'yes'}
								<li class="pull-right"><a href="/contrib/download-file?type=clientbrief&article_id={$article.article_id}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> T&eacute;l&eacute;charger le brief client</a></li>
							{/if}	
						</ul>
					</div>
				</div>
			</section>
			{include file="Contrib/article-comments.phtml"}
		</div>
		<div class="span3">
		<!--  right column  -->
			<aside>
				<div class="aside-bg">
					<div id="selected-editor" class="aside-block">
						<div class="editor-container">
							<h4>Votre client</h4>
							<img src="{$article.client_pic}" title="{$article.company_name}">
							<p class="editor-name">{$article.company_name}</p>
							{if $article.ao_type eq 'premium'}
								<a href="/contrib/compose-mail?senduser=110923143523902" class="btn btn-small">Contactez-nous</a>
							{else}
								<a href="/contrib/compose-mail?senduser={$article.clientId}" class="btn btn-small">Contacter</a>
							{/if}
							
						</div>
					</div>
					<div class="aside-block" id="garantee">
						<h4>Vos garanties</h4>
						<dl>
							<dt><span class="umbrella"></span>edit-place est votre m&eacute;diateur</dt>
							<dd>En cas de contestation (d&eacute;lai de livraison, reprise d&rsquo;articles, remboursement...)</dd>
							<dt><span class="locked"></span>Paiement s&eacute;curis&eacute;</dt>
							<dd>Notre solution de paiement en ligne vous garantit une transaction en toute tranquillit&eacute;</dd>
						</dl>
					</div>
				</div>
			</aside>  
		</div>
	</div>
{/foreach}
{/if}	
</div>