<!--$finished to display finshed Ao style
$upcmoing to check upcoming ao block styles--> 
{literal}
<script type="text/javascript">
	var cur_date={/literal}{$smarty.now}{literal};
	var js_date=(new Date().getTime())/ 1000;
	var diff_date=Math.floor(js_date-cur_date);
// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();	
	startTimer('time1','text1'); //timer ids starting with
	startTimer('time2','text2');//timer ids starting with
</script>
{/literal}
{if $articleDetails | @count gt 0}
	{foreach from=$articleDetails item=article name=details}
		<section id="a_o">
			{if $mission_type eq 'premium'}
				<div class="mp">
					{if $article.missiontest eq 'yes'}
						<span class="label label-test-mission" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Staffing</span>
					{else}
						<span class="label label-premium" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Premium</span>
					{/if}
			{elseif $mission_type eq 'nopremium'}	
				<div class="dl">
					{if $article.missiontest eq 'yes'}
						<span class="label label-test-mission" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Staffing</span>
					{else}
						<span class="label label-quote" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Mission Libert&eacute;</span>
					{/if}
			{/if}
			{if $article.view_to eq 'sc'}
				<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S&eacute;nior</span>
			{elseif $article.view_to eq 'jc'}
				<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Junior</span>
			{elseif $article.view_to eq 'jc0'}
				<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D&eacute;butant</span>	
			{/if}			
			{if $article.link_quiz eq 'yes' && $article.quiz}
				<span class="label label-inverse" data-original-title="Participation soumis &agrave; un Quizz" rel="tooltip" data-placement="right">Quizz</span>
			{/if}
				<h2>{$article.title} {$article.picon}</h2>				

				<div class="summary clearfix">
					<ul class="unstyled">
						<li><strong>Appel &agrave; r&eacute;daction</strong> <span class="bullet">&#9679;</span></li>
						<li> Langue : <img class="flag flag-{$article.language}" src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$article.language_name}"> <span class="bullet">&#9679;</span></li>
						<li>Cat&eacute;gorie : {$article.category} <span class="bullet">&#9679;</span></li>
						<li>Nb. de mots : {$article.num_min} - {$article.num_max} / article<span class="bullet">&#9679;</span></li>
						<li><a href="#comment" class="scroll" id="comment_count_1"><i class="icon-comment"></i> {$commentCount}</a></li>
						{if $article.spec_exists eq 'yes'}
							<li class="pull-right"><a href="/contrib/download-file?type=clientbrief&article_id={$article.articleid}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> T&eacute;l&eacute;charger le brief client</a></li>
						{/if}	
					</ul>
				</div>

				<div class="a_o-details">
					<!-- start, colonne generale -->
					<div class="row-fluid">
						<div class="span7">
							<!-- start, colonne stat -->
							<div class="row-fluid stat-block">
								<div class="span4 section">Temps restant
								<p>
									{if $upcoming eq 'yes'}
										&#9679;&#9679;&#9679;
										
									{elseif $finished  eq 'yes'}
										Termin&eacute;
									{else}	
										<span id="time1_{$article.articleid}_{$article.timestamp}">
											<span id="text1_{$article.articleid}_{$article.timestamp}">{$article.timestamp}</span>
										</span>
									{/if}	
								</p>
								</div>
								<div class="span4 section">Temps estim&eacute; de production
								  <p>
								    {if $upcoming eq 'yes'}
								    &#9679;&#9679;&#9679;
								    {else}
								    {$article.article_submit_time_text}
								    {/if}	
							      </p>
							  </div><div class="span4 section">Client<p><img src="{$article.client_pic}"  class="logo"/></p></div>
							</div>
							<div class="row-fluid note">
								<div class="span12">
									{if $mission_type eq 'premium'}
										{if $article.estimated_worktime gt 0}
											<div class="section">
												<span data-placement="right" data-trigger="hover" rel="popover" data-content="Estimation r&eacute;alis&eacute;e par votre chef de projet." data-original-title="Temps de travail estim&eacute;">Temps de travail estim&eacute; <i class="icon-info-sign icon-white"></i></span>
												<p>{$article.estimated_worktime_text}</p>
											</div>
										{else}
											<p><i class="icon-info-sign icon-white"></i>Cette commande est garantie par edit-place. Si vous &ecirc;tes s&eacute;lectionn&eacute;, vous &ecirc;tes s&ucirc;r de r&eacute;diger imm&eacute;diatement</p>
										{/if}	
									{elseif $mission_type eq 'nopremium'}																			
										<p><i class="icon-info-sign icon-white"></i> <strong>Tentez votre chance !</strong> Attention, Il peut s'agir d'une simple demande d'information ou d'une vraie mission de r&eacute;daction.</p>
									{/if}		
								</div>
							</div>
							<!-- end, colonne stat -->
						</div>
						<div class="span5">
							<table class="table table-hover">
							{if $upcoming eq 'yes'}
								{if $mission_type eq 'premium' OR ($article.AOtype eq 'private' && $article.price_max)}
									<tr><td class="title">Fourchette de prix</td><td class="countdown"><em>{$article.price_min|zero_cut:2} - {$article.price_max|zero_cut:2} &euro;</em></td></tr>
								{/if}
								<tr><td class="title">Ouverture de l'annonce</td><td class="countdown">{$article.publishtime_format}</td></tr>
								<tr>
									<td colspan="2" class="cta" >
										<span id="alert_{$article.deliveryid}">											
											{if $article.alert_subscribe eq 'no'}
												<button class="btn" onclick="subscribeAOAlert('{$article.deliveryid}','yes','article');"><i class="icon-bell"></i> Etre alert&eacute;</button>
											{elseif $article.alert_subscribe eq 'yes'}
												<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$article.deliveryid}','no','article');"><i class="icon-remove icon-white"></i> Alerte programm&eacute;e</a>
											{/if}
										</span>
										
									</td>
								</tr>
							{else}
							
								{if $article.pricedisplay=='yes'}
									<tr>
										<td class="title">Participants {$article.picon}</td>
										<td class="countdown">{$article.participants_pic}
										{if $article.participants > 2}
											<span class="more-contrib">+{math equation="(x-2)" x=$article.participants}</span>
										{elseif  $article.participants eq 0}	
											<span class="more-contrib">0</span>
										{/if}	
										</td>
									</tr>							
								{else}
									<tr>
										<td class="countdown contrib-list">
											<div class="title">Participants {$article.picon}</div>
											{$article.participants_pic}
											{if $article.participants > 5}
												<span class="more-contrib">+{math equation="(x-5)" x=$article.participants}</span>
											{elseif  $article.participants eq 0}	
												<span class="more-contrib">0</span>
											{/if}
										</td>
									</tr>									
								{/if}	
							
								{if ($mission_type eq 'premium' OR ($article.AOtype eq 'private' && $article.price_max)) && $article.pricedisplay=='yes'}
									{if $article.price_max eq 0 && $article.price_min eq 0}
										<tr><td class="title">Mission test</td><td class="countdown" style="text-transform:none"><em>0 &euro;</em></td></tr>
									{else}
										<tr><td class="title">Fourchette de prix</td><td class="countdown" style="text-transform:none"><em>{$article.price_min|zero_cut:2} - {$article.price_max|zero_cut:2} &euro;</em></td></tr>
									{/if}	
								{/if}
								
								{*{if $article.pricedisplay=="yes"}
									<tr><td class="title">Dernier prix propos&eacute;</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="Tous les prix propos&eacute;s" data-placement="left" data-html="true" {if $article.participants_price} data-content="{$article.participants_price}" data-trigger="hover"{/if}>
									{if $article.latestPrice} 
										{$article.latestPrice} &euro;
									{else}
										NA
									{/if}	
									</a></em></td></tr>
								{/if}*}
								{if $finished  eq 'yes'}
									<tr class="warning">
										<td colspan="2" class="cta"><strong><i class="icon-warning-sign"></i> D&eacute;lai de participation d&eacute;pass&eacute;</strong></td>
									</tr>
								{elseif $no_permission eq 'yes'}
									<tr class="warning">
											<td colspan="2" class="cta"><strong><i class="icon-warning-sign"></i> D&eacute;sol&eacute; ! L'annonce est r&eacute;serv&eacute;e exclusivement au 
											{if $article.view_to eq 'sc'}
												<span class="label label-level"><i class="icon-bookmark"></i>S&eacute;nior</span>
											{elseif $article.view_to eq 'jc'}
												<span class="label label-level"><i class="icon-bookmark"></i>Junior</span>
											{elseif $article.view_to eq 'jc0'}
												<span class="label label-level"><i class="icon-bookmark"></i>D&eacute;butant</span>												
											{elseif $article.view_to eq 'sc,jc' OR $article.view_to eq 'jc,sc' }
												<span class="label label-level"><i class="icon-bookmark"></i>S&eacute;nior</span><span class="label label-level"><i class="icon-bookmark"></i>Junior</span>
											{/if}
											</strong></td>
									</tr>
								{elseif !$request_from}
									<tr><td colspan="2" class="cta" id="tender_select_{$article.articleid}">
									
									{if $article.display eq 'no' || $disabled eq 'yes'}
										<button class="btn btn-large btn-primary disabled">Annonce ajout&eacute;e</button>
                                    {elseif $article.attended eq 'YES'}
                                            <button  onClick="fnCartModifiers('remove','{$article.articleid}','','{$article.deliveryid}');" class="btn btn-large btn-danger">Annonce ajout&eacute;e</button>
									{elseif $article.attended eq 'NO'}
										<button  onClick="fnCartModifiers('add','{$article.articleid}','','{$article.deliveryid}');" class="btn btn-large btn-primary">Je participe ! </button>
									{/if}	
									</td></tr>
								{/if}	
							{/if}	
							</table>
						</div>
					</div>
					<!-- end, colonne generale -->
				</div>
				{if $no_permission eq 'yes'}
					{include file="Contrib/mission-badStatus.phtml"}
				{/if}
				{if !$finished && !$no_permission}
					{include file="Contrib/article-comments.phtml"}
				{/if}	
			</div>
		</section>
		<a href="#brand" class="pull-right btn btn-small disabled anchor-top scroll"><i class="icon-arrow-up"></i></a>
		<div id = "confirmDiv"></div>
		{include file="Contrib/popup_confirm_selection.phtml"}
		
		<!--Quiz Confirmation modal-->
		<div id="gotoQuizz" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 id="myModalLabel">Quizz de pr&eacute;s&eacute;lection</h3>
			</div>
			<div class="modal-body">
				<p> Pour ajouter cette annonce &agrave; votre s&eacute;lection, vous devez r&eacute;pondre &agrave; un quizz sur la th&eacute;matique.</p>
				<p><i class="icon-time"></i>  Vous disposerez de <strong>{$article.quiz_duration} minutes</strong> pour r&eacute;pondre aux questions. Ready ?</p> 
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
				<a class="btn btn-primary" data-target="#playQuizz-ajax" data-toggle="modal" role="button" href="/quiz/participate-quiz?article_id={$article.articleid}&quiz_identifier={$article.quiz}" id="btnPlayQuizz">D&eacute;marrer le quizz</a>
				
			</div>
		</div>
		
	{/foreach}
{else}
<section>
	<div class="row-fluid">
		<div class="pull-center span10 offset1">
			<p class="text-error lead">Vous ne pouvez pas participer &agrave; cette mission.</p>
		</div>
	</div>
</section>
{/if}
{literal}
<script>
 	$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});
	$('#btnPlayQuizz').click(function () {
		
		/* $('#playQuizz-ajax').modal(
		{
				remote: 'quizz.html'
		}
    	);	
		$('#playQuizz-ajax').modal('show'); */
		$('#gotoQuizz').modal('hide');
		$('#viewOffer-ajax').modal('hide');
		
		
		});	
</script>	
{/literal}