{literal}
<script type="text/javascript">
var cur_date=0,js_date=0,diff_date=0;
cur_date={/literal}{$smarty.now}{literal};
js_date=(new Date().getTime())/ 1000;
diff_date=Math.floor(js_date-cur_date);
$("#menu_ongoing").addClass("active");
starQuizTimer('question','question');

bootstrap_alert = function() {}
bootstrap_alert.error = function(div,message) {
	$('#'+div).html('<div class="alert  alert-error"><button data-dismiss="alert" class="close" type="button">&times;</button><span><ul>'+message+'</ul></span></div>')
}

//save each option selected and load next question if available
$("#loadQuestion").click(function(e) {
	e.preventDefault();
	
	if($("input:radio[name='qoptions']").is(":checked")) {	
	
		$.get("/quiz/add-option",$("#quiz").serialize(),function(data){            
			var href = $("#loadQuestion").attr('href');						
			$("#playQuizz-ajax").removeData('modal');		
			$('#playQuizz-ajax .modal-body').load(href);
			$("#playQuizz-ajax").modal();
			$(".modal-backdrop:gt(0)").remove();
        });			
	}
	else
	{	
		var msg='Merci de cocher une r&eacute;ponse';
		bootstrap_alert.error('alert_quiz_placeholder',msg);	
	}	
});

//save final question option and submit the results
$("#validateQuiz").click(function(e) {
	e.preventDefault();
	var insert=false;
	
	if($("input:radio[name='qoptions']").is(":checked")) {	
	
			insert=true;		
	}
	else
	{	
		var msg='Merci de cocher une r&eacute;ponse';
		bootstrap_alert.error('alert_quiz_placeholder',msg);	
	}
	
	if(insert)
	{
		$.get("/quiz/add-option",$("#quiz").serialize(),function(data){ 
			$.post("/quiz/save-quiz",$("#quiz").serialize(),function(message){							
					$("#playQuizz-ajax").removeData('modal');		
					//$('#playQuizz-ajax .modal-body').html(message);
					//$("#playQuizz-ajax").modal();
					$(".modal-backdrop:gt(0)").remove();
					$( "#recruitment-challenge1" ).submit();
				});	
		});		
	}		
});

//Cancle Quiz default insert fail
$("#cancleQuiz,#exitQuiz").click(function(e) {
	e.preventDefault();		
	 var message="En  cliquant sur annuler, nous consid&eacute;rerons que vous n'avez pas r&eacute;ussi le quizz";
	 var heading='Confirm';
	if ($("#quiz").length) { 
		bootbox.confirm(message, function(result) {
			if(result)
			{
				$.post("/quiz/cancle-quiz",$("#quiz").serialize(),function(message){										
					$("#playQuizz-ajax").removeData('modal');					
					$(".modal-backdrop:gt(0)").remove();
					$("#recruitment-challenge1" ).submit();					
				});
			}
		});
	}
	else
	{	
		window.location.reload();	
	}	
	

});
$(document).keyup(function(e) {
	
	if (e.keyCode == 27 && $("#quiz").length){
		
		$('#playQuizz-ajax').on('hidden', function () {
			if($("#quiz").serialize())
			{
				$.post("/quiz/cancle-quiz",$("#quiz").serialize(),function(message){										
					$("#playQuizz-ajax").removeData('modal');		
					//$('#playQuizz-ajax .modal-body').html(message);
					//$("#playQuizz-ajax").modal();
					$(".modal-backdrop:gt(0)").remove();
					$("#recruitment-challenge1" ).submit();						
				});	
			}
			else
				window.location.reload();
		});
	}
});




</script>
{/literal}
{if $current_question | @count gt 0}
	{foreach from=$current_question item=question name=quiz}
	<section id="quizz">
	<div class="pull-center">
		<div class="downtime"><span class="licon licon-timing"></span>
			<span id="question_{$question.id}_{$question.timestamp}">{$question.quiz_duration}</span>
		</div>
		<!-- Add class "less1" when countdown < 50s -->
		<!-- div class="downtime less1"><span class="licon licon-timing"></span> 00:59</div-->
	</div>
	<div class="row-fluid">
		<div class="well well-large span10 offset1">
			<h1>{$question.question} <div class="pull-right number">{$current}<span class="on">/{$totalQuestions}</span></div></h1>
			<hr>
			<form method="" action="" id="quiz">
				
				{foreach from=$question.options item=options name=option}
				{assign var='qindex' value=$smarty.foreach.option.index+1}
					<label class="radio">
						<input type="radio" name="qoptions"  value="{$options.id}">
						<!--<input type="radio" name="qoptions"  value="{$qindex}">-->
						{$options.text|escape}
					</label>
				{/foreach}			
				<div id = "alert_quiz_placeholder"></div>
				<div class="pull-right">
					<a class="btn" id="cancleQuiz">Annuler</a>
					{if $next_id}
						<a class="btn btn-primary" id="loadQuestion" href="/quiz/participate-recruitment-quiz?recruitment_id={$question.recruitment_id}&quiz_identifier={$question.quizz_id}&question_id={$next_id}">Valider ma r&eacute;ponse</a>
					{else}
						<a class="btn btn-primary" id="validateQuiz">Valider ma r&eacute;ponse <i class="icon-white icon-chevron-right"></i></a>
					{/if}	
				</div>
				<input type="hidden" name="quiz" value="{$question.quizz_id}">
				<input type="hidden" name="question" value="{$question.id}">
				<input type="hidden" name="recruitment" value="yes">
				<input type="hidden" name="article_id" value="{$question.recruitment_id}">
				
			</form>
		</div>
	</div>
</section>
{/foreach}
<div id = "confirmCancle"></div>
<a href="#brand" class="pull-right btn btn-small disabled anchor-top scroll"><i class="icon-arrow-up"></i></a>
{/if}
{literal}
<script>

$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});

// tooltip activation
    $("[rel=tooltip]").tooltip();
	 $("[rel=popover]").popover();
	
</script>
{/literal}