{literal}
<script type="text/javascript">
$(function(){
		bootstrap_alert = function() {}
		bootstrap_alert.error = function(message) {
            $('#alert_placeholder1').html('<div class="alert  alert-error"><button data-dismiss="alert" class="close" type="button">&times;</button><span><ul>'+message+'</ul></span></div>')
        }
		//Recruitment Contract Validation
		$("#recruitment-contract-submit").click(function(){
		
			var errorcount=0;
			var checkedcount=0;
			
			var contract_text=$("#contract").html();
			$("#contract_text").html(contract_text);
			
			
			if($('input:radio[name=contract]:checked').val()=='yes')
				$(this).parents("label:first").removeClass("error");
			else if($('input:radio[name=contract]:checked').val()=='no')
			{
				checkedcount+=1;
			}
			else
			{
				bootstrap_alert.error('Merci de cocher une case');
					errorcount+=1;
			}			
			
			//alert(errorcount + '--'+checkedcount);
			if (checkedcount > 0 && errorcount==0)
			{
				var confirm_message='Etes-vous certain(e) de refuser les termes du contrat et de renoncer &agrave; votre participation ?';
				var heading='Confirm';
				openRecConfirmModal(heading,confirm_message);
				//return false;
			}
			else if(errorcount > 0 && checkedcount<1)
			{
				return false;
			}
			else
			{			
				$("#recruitment-contract").submit();
				return true;
			}
		
		});		
});	
(function ($) {
    $.fn.extend({
        //pass the options variable to the function
        confirmRecModal: function (options) {
            var html = '<div class="modal" id="confirmContainer"><div class="modal-header"><a class="close" data-dismiss="modal">×</a>' +
            '<h3>#Heading#</h3></div><div class="modal-body">' +
            '#Body#</div><div class="modal-footer">' +
            '<a class="btn btn-primary" id="confirmYesBtn">Confirmer</a>' +
            '<a class="btn" id="confirmCancelBtn">Annuler</a></div></div>';

            var defaults = {
                heading: 'Please confirm',
                body:'Body contents',
                callback : null
            };
            
            var options = $.extend(defaults, options);
            html = html.replace('#Heading#',options.heading).replace('#Body#',options.body);
            $(this).html(html);
            $(this).modal('show');
            var context = $(this); 
            $('#confirmYesBtn',this).click(function(){
                
                $("#recruitment-contract").submit();
				$(context).modal('hide');
            });
			$('#confirmCancelBtn',this).click(function(){
				$(context).modal('hide');
            });
        }
    });

})(jQuery);	
function openRecConfirmModal(heading,message) 
{
	$("#confirmDiv").confirmRecModal({	
		heading: heading,
		body: message		
	});	
}
</script>
{/literal}


<div class="span11">
	<!-- end, status -->
   <h1>Contrat edit-place<div class="pull-right" id="link-print"><a href="#print-contractForm" class="btn btn-small" ><i class="icon-print"></i> Imprimer le contrat</a></div></h1>
  

		<div class="contractform well well-large" id="contract">
		<p class="pull-center" style="text-align:center">CONTRAT DE CESSION DE DROITS</p>
		<p style="text-decoration:underline">ENTRE LES SOUSSIGNES:</p>
		<address>
			<strong>{$FirstName} {$LastName}</strong><br>
				{$user_info}
		 </address>
		<p><strong>Ci-dessous  d&eacute;nomm&eacute; &laquo;le R&eacute;dacteur&raquo;,</strong></p>  
<p>D'une  part,</p>
<p>et </p>
<p><strong>La soci&eacute;t&eacute; Edit-place UK Ltd,</strong> Soci&eacute;t&eacute; au capital de 1 Livre Sterling,<br>
  Immatricul&eacute;e en Angleterre et pays de Galles, sous le num&eacute;ro #08610398, <br>
  Dont le si&egrave;ge social est situ&eacute; 67-70 Charlotte Road, London EC2A3PE</p>
  <p>Num&eacute;ro de TVA intra-communautaire : GB 182 0572 18</p>
 <p>Prise en la personne de son repr&eacute;sentant l&eacute;gal domicili&eacute; audit si&egrave;ge en cette qualit&eacute;,</p>
<p><strong>Ci-dessous  &nbsp;d&eacute;nomm&eacute;e &laquo;&nbsp;la Soci&eacute;t&eacute;&raquo;,</strong> </p>
<p>D'autre  part,</p>
<p style="text-decoration:underline">&Eacute;TANT  PR&Eacute;ALABLEMENT RAPPEL&Eacute; QUE :</p>
<p>La Soci&eacute;t&eacute; a pour principale activit&eacute; de mettre en relation des &eacute;diteurs recherchant du Contenu &eacute;crit (ci-apr&egrave;s le &laquo; Client &raquo;), le cas &eacute;ch&eacute;ant optimis&eacute; pour le r&eacute;f&eacute;rencement naturel, et des R&eacute;dacteurs susceptibles de leur fournir ce Contenu (ci-apr&egrave;s le &laquo; Service &raquo;). Ce Service est notamment propos&eacute; sur le site :<a href="http://www.edit-place.com/" target="_blank"> www.edit-place.com</a></p>
<p>
Le R&eacute;dacteur est inscrit sur ce site, et a accept&eacute; les conditions g&eacute;n&eacute;rales d'utilisation figurant &agrave; l'adresse http://www.edit-place.fr/contrib/terms ou http://www.edit-place.co.uk/contrib/terms
</p>
<p>
La Soci&eacute;t&eacute; contracte aux termes des pr&eacute;sentes, dans le cadre du Service, pour le compte du Client souhaitant acqu&eacute;rir les droits d'exploitation sur le Contenu transmis par le R&eacute;dacteur, sous condition de conformit&eacute; des Contenus &agrave; la commande, conform&eacute;ment aux conditions g&eacute;n&eacute;rales d'utilisation, et dans les conditions ci-apr&egrave;s d&eacute;finies.
</p>
<p>IL  A ETE CONVENU CE QUI SUIT :</p>
<p>Article  1 - Objet</p>
<p>Le R&eacute;dacteur, qui d&eacute;clare b&eacute;n&eacute;ficier de sa pleine capacit&eacute; juridique et / ou des pouvoirs n&eacute;cessaires &agrave; signer le pr&eacute;sent contrat de cession de droit, et pour autant que le(s) Contenu(s) pr&eacute;sente(nt) l'originalit&eacute; requise, c&egrave;de &agrave; titre exclusif &agrave; la Soci&eacute;t&eacute;, qui accepte pour lui-m&ecirc;me et ses Clients, les droits d'exploitation ci-apr&egrave;s d&eacute;finis, aff&eacute;rents au(x) Contenu(s) (ci-apr&egrave;s d&eacute;nomm&eacute; &laquo;Contenu&raquo;) qui ont pour nom de fichier et/ou pour titre :</p>
<p>&nbsp;</p>
<!--Article Details-->
{$ArticlesDetails}
<!--Ended-->
<p>&nbsp;</p>
<p>Le r&eacute;capitulatif des Contenus objet de la pr&eacute;sente cession figurera dans le bon de commande r&eacute;capitulatif mis &agrave; disposition du R&eacute;dacteur sur son compte en ligne &agrave; l'issue de sa prestation de r&eacute;daction.</p>
<p>La pr&eacute;sente cession comporte ainsi pour la Soci&eacute;t&eacute;, le droit d'exploiter ou de c&eacute;der le Contenu ci-dessus d&eacute;crit &agrave; son Client, selon les modalit&eacute;s suivantes et/ou le droit de c&eacute;der les droits suivants :</p>
<p><ul><li>	Pour les droits de reproduction, d'adaptation et de traduction:</li></ul>-  Le droit de reproduire le Contenu, le num&eacute;riser, scanner, photocopier, enregistrer le Contenu par tout autre proc&eacute;d&eacute; analogue existant ou &agrave; venir qu'il soit &eacute;lectronique, analogique, magn&eacute;tique ou num&eacute;rique et sur tout support, notamment informatique et num&eacute;rique;</p>
<p>-  Le droit de reproduire le Contenu et de l'adapter sous forme d'&eacute;dition &eacute;lectronique, en particulier en c&eacute;d&eacute;rom, CD-photo, CD-I, DVD, serveur et/ou application mobile ou tout autre proc&eacute;d&eacute; analogue ou &agrave; venir ;</p>
<p>-  Le droit de reproduire tout ou partie du Contenu et de l'adapter et sur les terminaux de lecture (tablettes, PDA, t&eacute;l&eacute;phones portables, et/ou tout autre appareil permettant de stocker ou diffuser des donn&eacute;es num&eacute;ris&eacute;es existant et &agrave; venir) et via les r&eacute;seaux num&eacute;riques, &eacute;lectroniques ou optom&eacute;triques, en particulier sur les r&eacute;seaux internet et les serveurs d'information Web, les r&eacute;seaux mobiles et/ou par tout autre proc&eacute;d&eacute; analogue connu ou &agrave; venir ; </p>
<p>- le droit d'adapter le Contenu aux r&egrave;gles d'optimisation du r&eacute;f&eacute;rencement naturel sur Internet, le droit d'int&eacute;grer le Contenu au sein d'une &oelig;uvre multim&eacute;dia ;</p>
<p>- le droit de traduction en toutes langues du Contenu et &agrave; destination de tous pays</p>
<p><ul><li>Pour le droit de repr&eacute;sentation :</li></ul>-  le droit de communiquer ou de faire communiquer, de mettre &agrave; la disposition du public le Contenu reproduit, ses adaptations, ses traductions en toutes langues et en tous pays, par tous proc&eacute;d&eacute;s de diffusion, notamment par les r&eacute;seaux num&eacute;riques, &eacute;lectroniques ou optom&eacute;triques, en particulier sur les r&eacute;seaux internet et mobile, par tout moyen de t&eacute;l&eacute;communication, notamment par voie hertzienne, par satellite, par t&eacute;l&eacute;diffusion et par tout moyen de c&acirc;blodistribution, ou par tout autre proc&eacute;d&eacute; analogue ou &agrave; venir et sur tout support, applications mobile, tablette, PDA ou tout autre support analogue existant ou &agrave; venir.</p>
<p>- la repr&eacute;sentation du Contenu, en tout ou partie, &agrave; des fins publicitaires, promotionnelles, professionnelles, d'information ou artistique, et/ou dans toute manifestation publique, festival, salon et autres lieux publics ou accessibles au public.</p>
<p>La pr&eacute;sente cession est consentie dans le dessein principal de permettre l'acc&egrave;s du public au Contenu sur Internet, et ce, notamment sur les sites et/ou applications du Client et de ses partenaires actuels ou futurs.</p>
<p> Article  2 - Dur&eacute;e de la cession et renouvellement</p>
<p>La pr&eacute;sente cession est consentie pour avoir effet en tous lieux, pour tous les pays et toutes les langues, et pour une dur&eacute;e de quinze (15) ann&eacute;es cons&eacute;cutives &agrave; compter de l'acceptation de la contribution du R&eacute;dacteur. </p>
<p>Sauf manifestation expresse des parties en sens contraire, le pr&eacute;sent contrat fera l'objet d'une tacite reconduction &agrave; l'expiration de la p&eacute;riode de quinze (15) ann&eacute;es mentionn&eacute;e &agrave; l'alin&eacute;a pr&eacute;c&eacute;dent. <br>
  Ce renouvellement tacite se fera par p&eacute;riodes de quinze (15) ann&eacute;es, dans la limite de la dur&eacute;e l&eacute;gale des droits d'auteur.</p>
<p>Article 3 - Exclusivit&eacute;, confidentialit&eacute; et notification de cessions ult&eacute;rieures</p>
<p>Le R&eacute;dacteur s'engage &agrave; ne pas c&eacute;der &agrave; nouveau les droits d'exploitation aff&eacute;rents &agrave; ce Contenu. Le R&eacute;dacteur s'engage par ailleurs &agrave; informer pr&eacute;alablement le Client cessionnaire et la Soci&eacute;t&eacute; de tout projet de cession d'autres droits d'exploitation sur ledit Contenu &agrave; quelque tiers que ce soit.<br>
  Cette notification pr&eacute;alable du r&eacute;dacteur &agrave; la Soci&eacute;t&eacute; d'un projet de cession de droits s'effectuera par l'envoi d'un message via l'espace de discussion mis &agrave; disposition des r&eacute;dacteurs et &eacute;diteurs sur le Service, doubl&eacute; d'un message adress&eacute; directement &agrave; Edit-Place. Le Client, &agrave; compter de la r&eacute;ception de cette notification, disposera d'un d&eacute;lai de 10 jours ouvr&eacute;s pour formuler ses observations, et le cas &eacute;ch&eacute;ant s'opposer au projet s'il estime que les droits lui ont d&eacute;j&agrave; &eacute;t&eacute; c&eacute;d&eacute; en exclusivit&eacute;, ou solliciter la cession des droits d'exploitation envisag&eacute;e moyennant paiement.</p>
<p>A d&eacute;faut de r&eacute;ponse dans le d&eacute;lai imparti, le Client sera r&eacute;put&eacute;e avoir valid&eacute; le projet de cession soumis par le R&eacute;dacteur.</p>
<p>Le r&eacute;dacteur s'engage enfin &agrave; ne pas communiquer sauf accord express du Client, le nom des soci&eacute;t&eacute;s, ou des marques, et/ou du nom ou URL du site Internet ou de l'application mobile) du Client pour lesquelles il a &eacute;t&eacute; amen&eacute; &agrave; r&eacute;diger le Contenu. Le Client pour lequel le r&eacute;dacteur r&eacute;dige ne peut signer l'article &agrave; la place du r&eacute;dacteur, conform&eacute;ment au droit moral d&eacute;tenu par le R&eacute;dacteur sur le Contenu. Le Client peut en revanche en faire la demande au r&eacute;dacteur par l'interm&eacute;diaire d'Edit-Place. Un accord pr&eacute;alable devra &ecirc;tre sign&eacute; dans ce cas entre les parties. </p>

<p>Article  4 - R&eacute;mun&eacute;ration du R&eacute;dacteur</p>
<p>Conform&eacute;ment aux dispositions de l'article L.131-4 alin&eacute;a 1&deg;,2&deg;,3&deg; et 4&deg;, des articles L. 132-5, L132-6 et suivants du Code de la Propri&eacute;t&eacute; Intellectuelle, les parties conviennent que l'Auteur, en contrepartie de l'acceptation de sa(ses) contribution(s), percevra une somme forfaitaire et d&eacute;finitive pour les documents intitul&eacute;s, soit :</p>
<p>&nbsp;</p>
<!--Article Details with AO-->
{$ArticlesDetailsWithAO}
<!--Ended-->
<p>&nbsp;</p>
<p>la  r&eacute;mun&eacute;ration suivante :</p>
<!--Article Details with Price-->
{$ArticlesDetailsWithPrice}
<!--Ended-->
<p>Cette somme sera cr&eacute;dit&eacute;e sur le compte du R&eacute;dacteur dans les 30 jours suivants la r&eacute;ception du Contenu conforme.</p>
<p>Le r&eacute;dacteur pourra ensuite la retirer &agrave; sa convenance d&egrave;s lors que son encours de compte aura atteint le seuil minimal de retrait fix&eacute; ci-avant, soit la somme de vingt (20) euros. Si le R&eacute;dacteur ne r&eacute;digeait plus de Contenu s&eacute;lectionn&eacute; pendant un an sur le Service, le prix sera vers&eacute; quel que soit son montant, dans un d&eacute;lai maximum de 30 jours, sur demande adress&eacute;e par mail &agrave; Edit-Place.</p>
<p>Ces reversements ne s'appliqueront qu'&agrave; compter de la r&eacute;ception dudit document.
 </p>
<p>Article  5 - Garanties donn&eacute;es par le R&eacute;dacteur</p>
<p>L'Auteur  garantit &agrave; la Soci&eacute;t&eacute; et au Client l'exercice paisible des droits c&eacute;d&eacute;s au  titre du pr&eacute;sent contrat.</p>
<p>Il  garantit &eacute;galement &agrave; la Soci&eacute;t&eacute; et au Client sa qualit&eacute; d'auteur de l'&oelig;uvre c&eacute;d&eacute;e  et il garantit que celle-ci ne fait &agrave; ce jour l'objet d'aucune contestation.</p>
<p>Au  cas o&ugrave; une contestation concernant les droits sur l'&oelig;uvre serait &eacute;mise par un  tiers, le R&eacute;dacteur s'engage &agrave; apporter &agrave; la Soci&eacute;t&eacute; et au Client, &agrave; sa  premi&egrave;re demande, tout son appui judiciaire.</p>
<p>Le  R&eacute;dacteur garantit &agrave; ce titre &agrave; la Soci&eacute;t&eacute; et au Client, la jouissance enti&egrave;re  et libre des droits c&eacute;d&eacute;s, contre tous troubles, revendications et &eacute;victions  quelconques.</p>
<p>Il  d&eacute;clare express&eacute;ment disposer des droits c&eacute;d&eacute;s par le pr&eacute;sent contrat, et que  l'&oelig;uvre n'a fait l'objet d'aucun contrat de cession exclusif ou non encore  valable.</p>
<p>Il  d&eacute;clare express&eacute;ment que l'&oelig;uvre n'entre pas dans le cadre d'un droit de  pr&eacute;f&eacute;rence, tel qu'il est d&eacute;sign&eacute; &agrave; l'article L. 132-4 du Code de la propri&eacute;t&eacute;  intellectuelle que l'auteur d&eacute;clare parfaitement conna&icirc;tre, accord&eacute;  ant&eacute;rieurement par lui &agrave; un &eacute;diteur.</p>
<p>Le  R&eacute;dacteur est &eacute;galement inform&eacute; que la d&eacute;couverte par la Soci&eacute;t&eacute; d'une  publication identique du pr&eacute;sent document par contrat de cession aupr&egrave;s d'une  autre soci&eacute;t&eacute; pourra donner lieu &agrave; r&eacute;siliation de plein droit du pr&eacute;sent  contrat, sur simple notification par tout moyen &agrave; la discr&eacute;tion d'Edit-Place et  ou du Client, et sans pr&eacute;judice des dommages et int&eacute;r&ecirc;ts que Edit-Place se  r&eacute;serve le droit de solliciter devant les juridictions comp&eacute;tentes.</p>
<p>L'auteur  garantit la Soci&eacute;t&eacute; et le Client contre toute action en contrefa&ccedil;on qui  r&eacute;sulterait de l'existence de contrats de cession de droits sur le pr&eacute;sent  document, non r&eacute;v&eacute;l&eacute;s &agrave; la Soci&eacute;t&eacute; &agrave; la signature des pr&eacute;sentes.</p>
<p>L'auteur  garantit que son &oelig;uvre est conforme &agrave; la l&eacute;gislation fran&ccedil;aise et toute autre  l&eacute;gislation applicable, et notamment les dispositions relatives &agrave; la  diffamation et l'injure, &agrave; la vie priv&eacute;e et au droit &agrave; l'image, &agrave; l'autorit&eacute; de  la justice, &agrave; la protection morale de la jeunesse, au respect de la pr&eacute;somption  d'innocence, &agrave; l'atteinte aux bonnes m&oelig;urs ou &agrave; la contrefa&ccedil;on.</p>
<p>Il  garantit en particulier que son &oelig;uvre ne comporte aucun emprunt - m&ecirc;me partiel  - &agrave; une autre &oelig;uvre, emprunt qui serait de nature &agrave; engager la responsabilit&eacute;  de la Soci&eacute;t&eacute; et/ou du Client.</p>
<p>En cas de cession d'une &oelig;uvre dite de collaboration, le R&eacute;dacteur garantit &agrave; la Soci&eacute;t&eacute; et au Client qu'il lui c&egrave;de d'un commun accord avec les autres coauteurs les droits d'exploitation de l'&oelig;uvre commune. Il garantit &agrave; ce titre &agrave; la Soci&eacute;t&eacute; et au Client l'accord express des coauteurs sur la cession de droits conc&eacute;d&eacute;e.</p>
<p>Les garanties susmentionn&eacute;es sont - de la commune intention des parties - une condition essentielle et d&eacute;terminante du contrat sans laquelle la pr&eacute;sente convention n'aurait pas &eacute;t&eacute; conclue.</p>
<p>En cons&eacute;quence de cette garantie, l'auteur s'engage express&eacute;ment, en cas de condamnations prononc&eacute;es &agrave; l'encontre de la Soci&eacute;t&eacute; et du Client par toutes juridictions - notamment civiles ou p&eacute;nales - de r&eacute;gler ou rembourser l'int&eacute;gralit&eacute; des sommes qui pourraient &ecirc;tre r&eacute;clam&eacute;es &agrave; la Soci&eacute;t&eacute; et/ou au Client, quelles que soient leur nature (dommages et int&eacute;r&ecirc;ts, frais de publication, d&eacute;pens, indemnit&eacute; due sur le fondement de l'article 700 du Nouveau Code de Proc&eacute;dure Civile, etc.).</p>
<p>Les obligations, abstentions, garanties ou tout autre fait cr&eacute;ateur de droits au b&eacute;n&eacute;fice de la Soci&eacute;t&eacute; par le pr&eacute;sent contrat, tant implicites qu'explicites, sont express&eacute;ment conf&eacute;r&eacute;es par le R&eacute;dacteur tant &agrave; la Soci&eacute;t&eacute; qu'au Client. </p>  
<p>Article  6 - Clause r&eacute;solutoire</p>
<p>En cas de violation des obligations essentielles du pr&eacute;sent contrat, notamment de livraison et de qualit&eacute; des Contenus ainsi que celles relatives au paiement du R&eacute;dacteur,, et quinze jours apr&egrave;s l'envoi d'une lettre recommand&eacute;e avec accus&eacute; de r&eacute;ception rest&eacute;e sans effet, la pr&eacute;sente convention sera r&eacute;sili&eacute;e de plein droit sans qu'il soit besoin d'une formalit&eacute; judiciaire quelconque, aux torts et griefs de la partie d&eacute;faillante, si bon semble &agrave; l'autre partie, sous r&eacute;serve de tous dommages et int&eacute;r&ecirc;ts &eacute;ventuels. Les &eacute;ventuelles livraisons de Contenu ayant fait l'objet d'une r&eacute;ception conforme avant cette r&eacute;siliation demeureront valides, de nature &agrave; permettre leur effectivit&eacute; pleine et enti&egrave;re malgr&eacute; la r&eacute;siliation intervenue.</p>
<p>Article  7 - Ayants droit</p>
<p>Le pr&eacute;sent contrat, dans son int&eacute;gralit&eacute;, engage les h&eacute;ritiers et tous ayants droit du R&eacute;dacteur, qui devront, dans la mesure du possible, se faire repr&eacute;senter aupr&egrave;s de la Soci&eacute;t&eacute; et/ou du Client par un mandataire commun.</p>
<p>Article  8 - Responsabilit&eacute;</p>
 <p>De convention expresse entre les parties, l'&eacute;ventuelle responsabilit&eacute; de la Soci&eacute;t&eacute; au titre du contrat ne pourra &ecirc;tre engag&eacute;e que sur faute prouv&eacute;e, et dans un d&eacute;lai de 12 (douze) mois suivant l'entr&eacute;e en vigueur du pr&eacute;sent contrat. Les &eacute;ventuels dommages et int&eacute;r&ecirc;ts dus par la Soci&eacute;t&eacute; ne sauraient exc&eacute;der la somme re&ccedil;ue par le R&eacute;dacteur au titre du contrat.</p>
<p>  Article  9 - Entr&eacute;e en vigueur du contrat</p>
<p>Ce contrat de cession est valid&eacute; par le R&eacute;dacteur &agrave; la date de soumission du Contenu sur le Service, mais son entr&eacute;e en vigueur est conditionn&eacute;e par la r&eacute;ception du document, et sa conformit&eacute; &agrave; la commande, que le R&eacute;dacteur a express&eacute;ment accept&eacute;e, et la conformit&eacute; aux Conditions G&eacute;n&eacute;rales d'Utiliation, accept&eacute;es lors de la cr&eacute;ation de son compte pour acc&eacute;der au Service.</p>
<p>La r&eacute;ception du Contenu du R&eacute;dacteur par la Soci&eacute;t&eacute; est effectu&eacute; dans les meilleurs d&eacute;lais, et en lien avec le Client, et constitue la date d'entr&eacute;e en vigueur du pr&eacute;sent contrat.</p>
<p>De convention expresse entre les Parties, le R&eacute;dacteur reconnait que les donn&eacute;es figurant sur les syst&egrave;mes informatiques de la Soci&eacute;t&eacute;, ainsi que les contrats et courriers &eacute;lectroniques conserv&eacute;s sur les syst&egrave;mes informatiques de la Soci&eacute;t&eacute; font foi entre les parties, sauf preuve contraire.</p>
<p>Article  10 - Droit applicable</p>
<p>Le pr&eacute;sent contrat est soumis au droit fran&ccedil;ais.</p>
<p>Pour tout litige n&eacute; de l'interpr&eacute;tation ou de l'ex&eacute;cution du pr&eacute;sent contrat, il est fait attribution expresse de juridiction aux tribunaux comp&eacute;tents de Londres.</p>
<p>&nbsp;</p>
<p>Fait  &agrave; Londres,&nbsp; le {$startDate|date_format:"%d/%m/%Y"}</p>
<!--
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>Signature  du R&eacute;dacteur</p>-->
<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
		</div>
		<div class="row-fluid">
			<div id ="alert_placeholder1"></div>
			<form class="form-horizontal" method="POST" action="/recruitment/sign-contract" id="recruitment-contract">
				<div class="control-group">
					<label class="control-label span5 offset1" for="contract">j'accepte les termes du pr&eacute;sent  contrat</label>
					<div class="controls span4">
						<label class="radio inline">
							<input type="radio" name="contract" value="yes">
							Oui
						</label>
						<label class="radio inline">
							<input type="radio" name="contract" value="no">
							Non
						</label>
					</div>
				</div>
				<hr>
				<div class="control-group">
					<h3 style="text-align:center;line-height: 45px">
						Vous avez <b>{$recruit.article_submit_time_text}</b> pour r&eacute;diger votre article test et nous le renvoyer.<br>
						{if $recruit.free_article eq 'yes'}
						<br><b><i class="icon-information"></i> Cette article test est gratuit</b> <br>
						Si vous &ecirc;tes s&eacute;lectionn&eacute; pour cette mission, vous recevrez en royalties <b>{$recruit.proposed_cost} &euro;</b> par article
						{else}	
							Si vous &ecirc;tes s&eacute;lectionn&eacute;, vous gagnerez <b>{$recruit.proposed_cost} &euro;</b> de royalties
						{/if}
					</h3>
				</div>
				
				<div class="control-group">					
					<label class="control-label span4"></label>
					<div class="controls span6">
						<a class="btn btn-link" href="/contrib/download-file?type=clientbrief&article_id={$smarty.get.article_id}"><i class="icon-download"></i> T&eacute;l&eacute;charger le brief</a>	
						<a class="btn btn-primary" id="recruitment-contract-submit">D&eacute;marrer l'article test</a>
					</div>
				</div>
				<input type="hidden" name="participation_id" value="{$participation_id}">
				<input type="hidden" id="recruitment_id" name="recruitment_id" value="{$smarty.get.recruitment_id}">
				<textarea name="contract_text" id="contract_text" style="display:none"></textarea>				
			</form>
			<div id = "confirmDiv"></div>
		</div>
</div>