<div class="mod">
	<h3 id="soon">Prochainement...</h3>

	<table class="table table-hover">
		<thead>
			<tr>
				<th><a href="#orderByType">Type</a></th>
				<th>
					{if $smarty.get.uorderByTitle eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderByTitle=asc#soon">Titre</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.uorderByTitle eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderByTitle=desc#soon">Titre</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderByTitle=asc#soon">Titre</a>	
					{/if}	
				</th>
				<th class="pc">
					{if $smarty.get.uorderByLang eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderByLang=asc#soon">Langues</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.uorderByLang eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderByLang=desc#soon">Langues</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderByLang=asc#soon">Langues</a>	
					{/if}								
				</th>
				<th class="pc">
					{if $smarty.get.uorderBytime eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderBytime=asc#soon">Date de publication</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.uorderBytime eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderBytime=desc#soon">Date de publication</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&uorderBytime=asc#soon">Date de publication</a>	
					{/if}
					
				</th>								
				<th class="pc"></th>
			</tr>
		</thead>
		{if $upcomingArticles |@count gt 0}
			{foreach item=article from=$upcomingArticles name="articledetails"} 								
				<tr>
					{if $article.ao_type eq 'correction'}
								<td><span class="label label-correction" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Correction</span>
								{if $article.view_to eq 'sc'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.view_to eq 'jc'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.view_to eq 'jc0'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
								</td>
								<td class="title"><a href="/contrib/article-details?upcoming=yes&misson_type=correction&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}  {$article.picon} </span>
					{elseif $article.ao_type eq 'poll_premium'}
								<td><span class="label label-quote-premium" data-original-title="Cette annonce est susceptible de devenir une mission Premium" rel="tooltip" data-placement="right">Devis premium</span>
								{if $article.contributors eq '0'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.contributors eq '1'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.contributors eq '3'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
								</td>
								<td class="title"><a href="/contrib/article-details?upcoming=yes&misson_type=poll_premium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>
					{elseif $article.ao_type eq 'poll_nopremium'}
								<td><span class="label label-quote" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Devis Libert&eacute;</span>
								{if $article.contributors eq '0'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.contributors eq '1'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.contributors eq '3'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
								</td>
								<td class="title"><a href="/contrib/article-details?upcoming=yes&misson_type=poll_nopremium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>		
					{elseif $article.premium_option}
						<td><span class="label label-premium" data-original-title="Mission garantie par Edit-place" rel="tooltip" data-placement="right">Mission Premium</span>
						{if $article.view_to eq 'sc'}
									<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.view_to eq 'jc'}
										<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.view_to eq 'jc0'}
										<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
								{/if}
						</td>
						<td class="title"><a href="/contrib/article-details?upcoming=yes&misson_type=premium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
					{elseif !$article.premium_option}
						<td><span class="label label-quote" data-original-title="Vous travaillerez en direct avec le client" rel="tooltip" data-placement="right">Mission Libert&eacute;</span>
						{if $article.view_to eq 'sc'}
							<span data-original-title="Niveau Senior" data-content="Je suis un contributeur confirm&eacute; chez Edit-place." rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
						{elseif $article.view_to eq 'jc'}
							<span data-original-title="Accessible au Junior" data-content="Au moins 1 article valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
						{elseif $article.view_to eq 'jc0'}
							<span data-original-title="Accessible au D&eacute;butant" data-content="Aucun article encore valid&eacute; sur Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>D</span>	
						{/if}
						</td>
						<td class="title"><a href="/contrib/article-details?upcoming=yes&misson_type=nopremium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
					{/if}									
					<p class="muted">{$article.category}  &bull;  Appel &agrave; r&eacute;daction  &bull;  {$article.num_min} - {$article.num_max} mots /article</p></a></td>
					<td class="pc"><img src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$article.language_name}" class="flag flag-{$article.language}"></td>
					<td class="countdown pc">
						{$article.publishtime_format}											
					</td>
					<td class="">
						{if $article.deliveryid}
							<span class="alert_{if $article.ao_type eq 'correction'}correction_{/if}{$article.deliveryid}">
								{if $article.ao_type eq 'correction'}
									{if $article.alert_subscribe eq 'no'}
										<button class="btn" onclick="subscribeAOAlert('{$article.deliveryid}','yes','article-correction');"><i class="icon-bell"></i> Etre alert&eacute;</button>
									{elseif $article.alert_subscribe eq 'yes'}
										<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$article.deliveryid}','no','article-correction');"><i class="icon-remove icon-white"></i> Alerte programm&eacute;e</a>
									{/if}
								{else}
									{if $article.alert_subscribe eq 'no'}
										<button class="btn" onclick="subscribeAOAlert('{$article.deliveryid}','yes','article');"><i class="icon-bell"></i> Etre alert&eacute;</button>
									{elseif $article.alert_subscribe eq 'yes'}
										<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$article.deliveryid}','no','article');"><i class="icon-remove icon-white"></i> Alerte programm&eacute;e</a>
									{/if}
								{/if}	
							</span>	
						{elseif $article.pollId}
							<span class="alert_{$article.pollId}">
								{if $article.alert_subscribe eq 'no'}
									<button class="btn" onclick="subscribeAOAlert('{$article.pollId}','yes','poll');"><i class="icon-bell"></i> Etre alert&eacute;</button>
								{elseif $article.alert_subscribe eq 'yes'}
									<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$article.pollId}','no','poll');"><i class="icon-remove icon-white"></i> Alerte programm&eacute;e</a>
								{/if}	
							</span>		
						{/if}	
					</td>
				</tr>								
			{/foreach}
		{else}
			<tr>
				<td colspan="6">
					<span class="no-data">Aucun r&eacute;sultat</span>
				</td>
			</tr>
		{/if}
	</table>
</div>