<header>
	<div class="container navbar navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				  <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </a>
				<a href="/index" title="Accueil edit-place" class="brand" id="brand"><img src="/FO/images/shim.gif" id="logo-extranet"></a>
				   <div class="nav-collapse collapse">
						<ul class="nav">
						  <li><a href="http://www.edit-place.com"><i class="icon-globe icon-white"></i> Edit-place.com</a></li>
						</ul>
						<ul class="nav pull-right">
							<li id="cartmenu">
							{if $selected_ao_count}
								<a class="btn btn-mini" role="button" href="/cart/cart-selection"><i class="icon-list-alt"></i> Ma s&eacute;lection <span class="badge badge-warning">{$selected_ao_count}</span></a>
							{else}
								<a class="btn btn-mini" role="button"><i class="icon-list-alt"></i> Ma s&eacute;lection <span class="badge">0</span></a>
							{/if}
							</li>						
							
							<li>
								<a data-toggle="dropdown" class="btn btn-mini btn-login dropdown-toggle">
									<i class="icon-user icon-white"></i> {$client_email} <span class="caret"></span>
								</a>
								<!-- Link or button to toggle dropdown -->
								<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
									<li><a tabindex="-1" href="/contrib/modify-profile">Modifier mon profil</a></li>
									<li class="divider"></li>
									<li><a tabindex="-1" href="/contrib/logout"><i class="icon-remove-sign"></i> D&eacute;connexion</a></li>
								</ul>
								 
							</li>             
						</ul>   
					
				  </div><!--/.nav-collapse -->
			</div>
			<!-- secondary nav -->
			<div class="container" id="secondary-nav">
			  <div class="nav-collapse collapse">
				<ul class="nav">
				<li><a href="/contrib/home" id="menu_home">Accueil</a></li>
				  <li><a href="/contrib/aosearch" id="menu_aosearch" >Les annonces</a></li>
				  <li><a href="/contrib/ongoing" id="menu_ongoing">Mes participations</a></li>
				  <li><a href="/contrib/private-profile" id="menu_profile">Mon compte</a></li>
				  <li><a href="/contrib/inbox" id="menu_mailbox">Messagerie {*{if $unreadCount gt 0} <span class="badge badge-warning">{$unreadCount}</span>{/if}*}</a> </li>
				  <li><a href="/contrib/royalties" id="menu_royalties">Mes royalties</a></li>
			   
				</ul>
			  </div><!--/.nav-collapse -->
			</div>

		<!-- end -->
		</div>
	</div>
</header>
{literal}
<script>
    $(document).ready(function(){
       loadHeaderAjaxMessageCount();
    });
    function
    loadHeaderAjaxMessageCount(){
        console.log('initiated loadHeaderAjaxMessageCount');
        $.ajax({
            type: 'POST',
            url: '/contrib/load-header-ajax-message-count',
            success: function (data) {
                var msgCount = data.trim()
                if(msgCount !== '0')
                    msgCount = '<span class="badge badge-warning">'+msgCount+'</span>';
                else
                    msgCount = '';
                $("#menu_mailbox").html('Messagerie '+msgCount);
            }
        });
    }
</script>
{/literal}