<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>edit-place Extranet, {$meta_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	<link rel="shortcut icon" href="/FO/favicon.ico" type="image/x-icon">

    <!-- Le styles -->

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{$livesite}/FO/script/common/html5.js"></script>
    <![endif]-->
	{assign var='cssfiles' value=''}
	{foreach from=$cssList item=css}
		{assign var='cssfiles' value=$cssfiles$css,}
	{/foreach}
<link type="text/css" rel="stylesheet" href="/min/b=FO/css&f={$cssfiles|substr:-1}"/>

	<!--[if lt IE 9]>
		<link rel="stylesheet" type="text/css" href="{$livesite}/FO/css/common/jquery.ui.1.9.2.ie.css"/>
	<![endif]-->
	<!--[if IE]>
      <link rel="stylesheet" type="text/css" href="/FO/css/Contrib/custom_ie.css"/>
    <![endif]-->
	{foreach from=$javascriptList item=jsfiles}
		<script type="text/javascript" src="{$livesite}/FO/script/{$jsfiles}"></script>
	{/foreach}	
	<script type="text/javascript" src="{$livesite}/FO/script/common/respond.src.js"></script>
	

</head>

 <body id="contributor" class="profile secondnav-on">
		
 		<!--Header Holder-->
			{foreach from=$headerList item=frame}
				{include file="$frame"}
			{/foreach}
		<!--/Header Holder-->

		<!--Content Holder-->
				{foreach from=$mainList item=frame}
					{include file="$frame"}
				{/foreach}		
		<!--/Content Holder-->	 

		<!--Footer Holder-->
				{foreach from=$footerList item=frame}
					{include file="$frame"}
				{/foreach}
		<!-- /FooterHolder -->
   



	<!-- ***** Modal collections -->

	<!-- ajax use start -->
	<div id="viewProfile-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 id="myModalLabel">Profil public</h3>
			</div>
		<div class="modal-body">

		</div>

	</div>
	<!-- ajax use end -->

{literal} 	
 <script>

	$(".scroll,.anchor-top").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
		return false;
	});
	
    // placeholder mgt for old browsers
    $('input, textarea').placeholder();
	
	//File input 
    $('#filePJ').customFileInput({
        button_position : 'left'
    });
	
	// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();	
</script>
{/literal}
  </body>
</html>