<!DOCTYPE html>
{php}

ini_set('default_charset', 'UTF-8');
mb_internal_encoding('UTF-8');
{/php}

<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>edit-place Extranet, {$meta_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	<link rel="shortcut icon" href="/FO/favicon.ico" type="image/x-icon">

    <!-- Le styles -->

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{$livesite}/FO/script/common/html5.js"></script>
    <![endif]-->	
	{assign var='cssfiles' value=''}
	{foreach from=$cssList item=css}
		{assign var='cssfiles' value=$cssfiles$css,}
	{/foreach}
<link type="text/css" rel="stylesheet" href="/min/b=FO/css&f={$cssfiles|substr:-1}"/>
	<!--[if IE]>
      <link rel="stylesheet" type="text/css" href="/FO/css/Contrib/custom_ie.css"/>
    <![endif]-->
	{foreach from=$javascriptList item=jsfiles}
		<script language="JavaScript" type="text/javascript" src="{$livesite}/FO/script/{$jsfiles}"></script>
	{/foreach}
	<script language="JavaScript" type="text/javascript" src="{$livesite}/FO/script/contrib/jstz-1.0.4.min.js"></script>
	<script language="JavaScript" type="text/javascript" src="{$livesite}/FO/script/contrib/jquery.cookie.js"></script>
	<!--<script language="JavaScript" type="text/javascript" src="{$livesite}/FO/script/contrib/favicon.js"></script>-->
	<!--[if IE]>	
	<script type="text/javascript" src="{$livesite}/FO/script/common/respond.src.js"></script>
	<![endif]-->


</head>

 <body id="contributor" class="homepage secondnav-on">
 		<!--Header Holder-->
			{foreach from=$headerList item=frame}
				{include file="$frame"}
			{/foreach}
		<!--/Header Holder-->

		<!--Content Holder-->
				{foreach from=$mainList item=frame}
					{include file="$frame"}
				{/foreach}		
		<!--/Content Holder-->	 

		<!--Footer Holder-->
				{foreach from=$footerList item=frame}
					{include file="$frame"}
				{/foreach}
		<!-- /FooterHolder -->
<!-- ***** Modal collections -->

<!-- ajax use start -->

<div id="viewOffer-ajax" class="modal container fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">D&eacute;tail de l'annonce</h3>
	</div>
	<div class="modal-body">
	
	</div>
</div>
<div id="playQuizz-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>-->
		<button type="button" class="close" id="exitQuiz">&times;</button>
		<h3 id="myModalLabel">Quizz de pr&eacute;selection</h3>
	</div>
	<div class="modal-body">

	</div>

</div>
<!-- ajax use end --> 	
	
{literal} 	
<script type="text/javascript">
	 $(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
		return false;		
	}); 
	
    // placeholder mgt for old browsers
    // $('input, textarea').placeholder();
	
  
	$('#helpTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    });	
	$('#helpTab a:first').tab('show');
	
	// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();
	
	var cookie_time_zone='local_timezone';
	var time_zone_value=getTimezoneName();
	if(!cookieManager.readCookie(cookie_time_zone))
		cookieManager.writeSessionCookie(cookie_time_zone,time_zone_value);
	
	function getTimezoneName() {
		var timezone = jstz.determine();		
		return timezone.name();
	}
	
	
    </script>
{/literal}
  </body>
</html>