{literal}
	<script type="text/javascript">
	$("#menu_billing").addClass("active");
	
	$(function(){
		var billcount=$("#billcount").val();
		
		$('a[id^="popover_"]').live('click', function(){ 
			var id=$(this).attr('id'); 
			$('#'+id).popover('show');
			for(var i=0; i<billcount; i++)
			{ 
				var popid='popover_'+i;
				if(popid!=id)
				{
					$('#'+popid).popover('hide');
				}
			}
		});
	});
	
	function closepopover(ind)
	{
		$('#popover_'+ind).popover('hide');
	}	

	</script>

{/literal}

<div class="container">
	<div class="row">
		<div class="span12">
			<h1>Mes factures</h1>
		</div>
	</div>

	<div class="row">   
		<div class="span9">
			<section id="billing-list">
				{if $billings|@count>0}
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Date de facture</th>
							<th>Mission effectu&eacute;e</th>
							<th>Montant</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{foreach from=$billings item=bill name=loopbill}
						<tr>
							<td>{$bill.created_at|date_format:"%d/%m/%Y"}</td>
							<td>
								<a href="#" data-placement="bottom" id="popover_{$smarty.foreach.loopbill.index}"  rel="popover" data-html="true" data-original-title="Info mission <button type=button class=close onClick=closepopover('{$smarty.foreach.loopbill.index}') aria-hidden=true>&times;</button>"
								data-content="- Annonce parue le : {$bill.ddate|date_format:'%d/%m/%Y'}<br>- Projet livr&eacute; le : {$bill.article_sent_at|date_format:'%d/%m/%Y'}<br>- Par : {$bill.first_name|ucfirst}&nbsp;{$bill.last_name|ucfirst} <br><br> <a href='/client/quotes?id={$bill.aid}' class='btn btn-block btn-small'>Historique commande</a>" >{$bill.title}</a>
							</td>
							<td>{$bill.amount_paid|zero_cut:2} &euro;</td> 
							<td>
								{if $bill.client_firstname==""}
									<a data-target="#profile-update" data-toggle="modal" class="btn btn-small" ><i class="icon-file"></i> T&eacute;l&eacute;charger</a>
								{else}
									<a href="/client/downloadinvoice?id={$bill.aid}" class="btn btn-small"><i class="icon-file"></i> T&eacute;l&eacute;charger</a>
								{/if}
							</td>
						</tr>
						{/foreach}
						<input type="hidden" name="billcount" id="billcount" value="{$billings|@count}" />
					</tbody>
				</table>
				<div class="span9">
				<!---Pagination start-->
					<div class="pagination pull-right">
						{include file="Client/pagination.phtml"}
					</div>	
				</div>
				{else}
				<div class="well">
					<div class="pull-center">
						<h4>Aucune facture disponible pour le moment</h4>
						<i class="icon-info-sign"></i> Si vous êtes en attente d'une facture depuis plus de 24h, <a href="/client/compose-mail?serviceid=111201092609847">contactez nous</a>
					</div>
				</div>
				{/if}
			</section>
		</div>

		<div class="span3">
			<aside>
				<div class="aside-bg">
					<div id="quote-ongoing" class="aside-block">
						<h4>Vos devis en cours</h4>
						<ul class="nav nav-tabs nav-stacked {if $quotes|@count>9}pre-scrollable{/if}">
							{if $quotes|@count>0}
								{foreach from=$quotes item=quote}
									<li>
										{if $quote.title|@strlen > 28}
											<a href="/client/quotes?id={$quote.id}" rel="tooltip" data-original-title="{$quote.title}" data-placement="left">
												{if $quote.valid=='yes'}
													<span class="badge pull-right badge-warning">1</span>
												{else}	
													<span class="badge pull-right">{$quote.participations}</span>
												{/if}
											{$quote.title|truncate:28:"...":true}
											</a>
										{else}
											<a href="/client/quotes?id={$quote.id}">	
												{if $quote.valid=='yes'}
													<span class="badge pull-right badge-warning">1</span>
												{else}	
													<span class="badge pull-right">{$quote.participations}</span>
												{/if}

											{$quote.title}</a>
										{/if}	
									</li>
								{/foreach}
							{else}
								<li><b>Pas de devis en cours</b></li>
							{/if}
						</ul>	
						<ul class="nav nav-tabs nav-stacked">
							<li><a href="/client/liberte1"><i class="icon-edit"></i> <strong>Demander un nouveau devis</strong></a></li>
						</ul>	
					</div>
					<div class="aside-block" id="garantee">
						<h4>Vos garanties</h4>
						<dl>
							<dt><span class="umbrella"></span>edit-place est votre m&eacute;diateur</dt>
							<dd>En cas de contestation (d&eacute;lai de livraison, reprise d’articles, remboursement...)</dd>
							<dt><span class="locked"></span>Paiement s&eacute;curis&eacute;</dt>
							<dd>Notre solution de paiement en ligne vous garantit une transaction en toute tranquillit&eacute;</dd>
						</dl>
					</div>
				</div>
			</aside>  
		</div>
	</div>
</div>

{if $writerscount>0}
	<section id="known-users">
		<div class="container">
			<div class="row">
				<h3 class="sectiondivider pull-center"><span>Ils ont d&eacute;j&agrave; collabor&eacute; avec vous !</span></h3>
				
				{foreach from=$writers item=writer}
					<div class="span3">
						<div class="editor-container">
							<a  class="imgframe-large" onclick="loadcontribprofile('{$writer.user_id}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">
								<img src="{$writer.profileimage}">
							</a>
							<p class="editor-name"><a onclick="loadcontribprofile('{$writer.user_id}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">{$writer.name|ucfirst}</a></p>
						</div>
					</div>
				{/foreach}
			</div>
		</div>
	</section>
{/if}	

	<!-- contrib profile -->
	<div id="viewContribProfile" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
			<h3 id="myModalLabel">Profil du r&eacute;dacteur</h3>
		</div>
		<div class="modal-body">
			<div id="userprofile">
		
			</div>
		</div>
	</div>
	
	<!-- Client profile update -->
	<div id="profile-update" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 id="myModalLabel">Mise &agrave; jour du profil requise</h3>
		</div>
		<div class="modal-body">
			<p>Merci de mettre &agrave; jour votre profil pour t&eacute;l&eacute;charger votre facture.</p>
			<p><a href="/client/profile">Mon compte</a></p>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
		</div>
	</div>