{literal}
<script type="text/javascript">

 $(document).ready(function() {	
	$("#menu_mailbox").addClass("active");
	$("#menu_classifybox").addClass("active");	
});
</script>	
{/literal}
<div class="container">
	<section id="maibox">
		<form method="" action="">
			<div class="row">    
				<div class="span12">
					<!---Pagination start-->
					<div class="pagination pull-right">
						{include file="Client/pagination.phtml"}
					</div>	
					<!---Pagination END-->
					<h1>Messagerie privée</h1>
				<hr>
				</div>

				{include file="Client/pattern/mail_leftmenu.phtml"}

				<div class="span9">
					<div class="mod" id="mailbox-list">
						{if $paginator|@count gt 0}
							{foreach item=message from=$paginator}
								
								<!-- row -->
								<div class="clearfix read">
									<a href="/client/classify-messages&page={$smarty.request.page}&ticket={$message.ticket_id}">
										<ul class="unstyled">
											<li class="snd">{$message.sendername}</li>
											<li class="sbj">{$message.Subject|truncate:55:"...":true|stripslashes}
												<span class="m"></span>
											</li>
											<li class="d">
												{if $smarty.now|date_format:"%d/%m/%Y" eq $message.updated_at|date_format:"%d/%m/%Y"}
													{$message.updated_at|date_format:"%Hh%M"}
												{elseif $smarty.now|date_format:"%Y" eq $message.updated_at|date_format:"%Y"}
													{$message.updated_at|date_format:"%d %b"}
												{else}
													{$message.updated_at|date_format:"%d/%m/%y"}
												{/if}
											</li>
										</ul>
									</a>						
								</div>	
							{/foreach}						
						{else}
							<h4 class="no-results">{$ticket_classes}</h4>
						{/if}						
					</div>
				</div>
				<div class="span12">
					<!---Pagination start-->
					<div class="pagination pull-right">
						{include file="Client/pagination.phtml"}
					</div>	
					<!---Pagination END-->										
				</div>
			</div>
		</form>
	</section>
</div>