{literal}
<script type="text/javascript">

 $(document).ready(function() {	
	
	$("#menu_mailbox").addClass("active");
	$("#menu_compose").addClass("disabled");
	
	// call write email function
	$('#mail_message').wysihtml5({"html":true,locale: "fr-FR"});
	//compose email validation
		$("#send_message").click(function(){
			var error=0,top=200;
			var sendto=$("#sendto");
			var mail_object=$("#mail_object");
			var object=mail_object.val();
			var	mail_message=$("#mail_message");
			var message=mail_message.val();
				message = message.replace(/(<([^>]+)>)/ig,"");
				message = message.replace(/&nbsp;/gi,"");
			if(sendto.length)
			{
				if(sendto.val())
				{
					sendto.removeClass("error");
					$("#sendto_error").html('');
				}	
				else
				{
					sendto.addClass("error");
					$("#sendto_error").html('send to obligator');
					error+=1;
				}
			}
			if(mail_object.length)
			{	
				if($.trim(object).length <1 || object=='')
				{
					mail_object.addClass("error");
					$("#mail_object_error").html('Objet obligatoire');
					error+=1;
				}	
				else
				{
					$("#mail_object_error").html('');
					mail_object.removeClass("error");
				}
			}	
			if($.trim(message).length <1 || message=="")
			{
				mail_message.addClass("error");
				$("#mail_message_error").html('Votre message obligatoire ');
				error++;
			}
			else
			{
				mail_message.removeClass("error");
				$("#mail_message_error").html('');
			}	
			if(error>0)
			{
				if(sendto.length)
				{
					$('html, body').animate( { scrollTop: top }, 'slow' );
				}	
				return false;
			}	
			else
				return true;

		});	
	
	
	});		
</script>
{/literal}	

<div class="container">
	{if $actionmessages[0]}
		<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">&times;</button>
			<i class="icon-ok icon-white"></i> {$actionmessages[0]}.
		</div>  
	{/if}
	<section id="maibox">
		<form name="compose_mail" id="composeMail" method="post" action="/client/send-mail" enctype="multipart/form-data">
			<div class="row">    
				<div class="span12">
					<h1>Messagerie priv&eacute;e</h1>
					<hr>
				</div>
				
				{include file="Client/pattern/mail_leftmenu.phtml"}

				<div class="span9">
					<div class="mod row-fluid">
						<h4><i class="icon-pencil"></i> Nouveau message</h4>
						<div class="well clearfix" id="replybox">
							<div class="span1">
								<a href="/client/profile"><img src="{$profile_picture}" title="{$client_email}"></a>
							</div>
							<div class="span11">
								<div class="muted" id="to">
									<label>A :
									<select class="input-medium" name="sendto" id="sendto">
										<option value="">S&eacute;lectionnez</option>
										<optgroup label="Edit-place" name="service_contact">
											{html_options  options=$EP_contacts selected=$smarty.get.serviceid}
										</optgroup>
										<optgroup label="Vos r&eacute;dacteurs" name="client_contact">
											{html_options  options=$Cients_contacts selected=$toClientId} 
										</optgroup>
									</select>
									<label for="sendto" class="error" id="sendto_error"></label>
									<!--, <a href="#" class="muted">+ ajouter</a>-->
									</label> 
								</div>
								<hr>
								<input name="mail_object" id="mail_object" type="text" class="span12 inline input" placeholder="Objet de votre email..." value="{$smarty.get.object}">
								<label for="mail_object" class="error" id="mail_object_error"></label>
								<textarea name="mail_message" id="mail_message" class="textarea" placeholder="Votre message..."></textarea>
								<label for="mail_message" class="error" id="mail_message_error"></label>
								<button class="btn btn-small btn-primary" id="send_message">Envoyer</button>
								<input type="hidden" name="ordercl" id="ordercl" value="{$smarty.get.ord}" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</section>
</div>