{literal}
<script type="text/javascript">

 $(document).ready(function() {	
	
	$("#menu_mailbox").addClass("active");
	$("#menu_inbox").addClass("active");
	
});
</script>	
{/literal}
<div class="container">
	{if $actionmessages[0]}
		<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">&times;</button>
			<i class="icon-ok icon-white"></i> {$actionmessages[0]}.
		</div>  
	{/if}
	<section id="maibox">
		<form method="" action="">
			<div class="row">    
				<div class="span12">
					<!---Pagination start-->
						<div class="pagination pull-right">
							{include file="Client/pagination.phtml"}
						</div>	
						<!---Pagination END-->
					<!--<div class="pull-right mailbox-head-right">
						<div class="mail-pagenum">1 - 50 sur {$InboxCount}</div>
						<div class="btn-group">
							<button class="btn btn-small disabled"><i class="icon-chevron-left"></i></button>
							<button class="btn btn-small"><i class="icon-chevron-right"></i></button>
						</div>											
					</div>-->
					<h1>Messagerie priv&eacute;e</h1>
					<hr>
				</div>

				{include file="Client/pattern/mail_leftmenu.phtml"}

				<div class="span9">
					<div class="mod" id="mailbox-list">
						
						{if $paginator|@count gt 0}
							{foreach item=message from=$paginator}
								{if $message.status=='0'}
									<!-- row : not read email-->
									<div class="clearfix not-read">
								{else}
									<!-- row -->
									<div class="clearfix read">
								{/if}
									<a href="/client/view-mail?type=inbox&page={$smarty.request.page}&message={$message.messageId}&ticket={$message.ticket_id}">
										<ul class="unstyled">
											<li class="snd">{$message.sendername}</li>
											<li class="sbj">{$message.Subject|truncate:55:"...":true|stripslashes}
												<span class="m">&#9679;  {$message.text_message}</span>
											</li>
											<li class="d">
												{if $smarty.now|date_format:"%d/%m/%Y" eq $message.receivedDate|date_format:"%d/%m/%Y"}
													{$message.receivedDate|date_format:"%Hh%M"}
												{elseif $smarty.now|date_format:"%Y" eq $message.receivedDate|date_format:"%Y"}
													{$message.receivedDate|date_format:"%d %b"}
												{else}
													{$message.receivedDate|date_format:"%d/%m/%y"}
												{/if}
											</li>
										</ul>
									</a>						
								</div>	
							{/foreach}						
						{else}
							<h4 class="no-results">{$Inbox_Messages}</h4>
						{/if}
					</div>
				</div>
				<div class="span12">
					<!---Pagination start-->
						<div class="pagination pull-right">
							{include file="Client/pagination.phtml"}
						</div>	
						<!---Pagination END-->
					<!--<div class="pull-right mailbox-head-right">
						<div class="mail-pagenum">1 - 50 sur {$InboxCount}</div>
						<div class="btn-group">
							<button class="btn btn-small disabled"><i class="icon-chevron-left"></i></button>
							<button class="btn btn-small"><i class="icon-chevron-right"></i></button>
						</div>											
					</div>-->					
				</div>
			</div>
		</form>
	</section>
</div>