{literal}
<script>
	function payformsubmit(ptype)
	{  
		document.payform.action ="/client/paypalpayment?paytype="+ptype;
		document.payform.submit();
		return false;
	}
</script>
{/literal}

<div class="container">
	<!-- start, status -->
	<div class="row-fluid">
		<div id="state2" class="span12">
			<ul class="unstyled">
				<li class="span3" rel="tooltip" data-original-title="S&eacute;lectionnez celui qui travaillera sur votre projet"><span class="writer_select">Choix du r&eacute;dacteur</span></li>
				<li class="span3" rel="tooltip" data-original-title="Le r&eacute;dacteur s&eacute;lectionn&eacute; travaille sur votre projet"><span class="ongoing">Production en cours</span></li>
				<li class="span3 hightlight" rel="tooltip" data-original-title="Vous versez en d&eacute;pôt de garantie le montant de la commande"><span class="cb">D&eacute;pôt de garantie</span></li>
				<li class="span3" rel="tooltip" data-original-title="T&eacute;l&eacute;charger vos projets livr&eacute;s"><span class="dld">T&eacute;l&eacute;chargement</span></li>
			</ul>
		</div>
	</div>
	<!-- end, status -->
	
	<!-- start, Summary -->
	<section id="summary">
		<div class="row-fluid">
			<div class="span6">
				<h1><p>Mission</p> {$aoparticipation[0].title}</span></h1>
			</div>
			<div class="span3 stat">
				<p>Date de livraison</p>
				<p class="num-large less24">
					{if $aoparticipation[0].articlestatus=="closed_client"}
						Annul&eacute;e
					{else}
						Livr&eacute;e
					{/if}
				</p>
			</div>
			<div class="span2 stat">
				<p>Tarif</p>
				<p class="num-large">{$aoparticipation[0].price_user_total|ceil} &euro;</p> 
			</div>
			<div class="span1 stat">
				<div class="icon-comment-large" rel="tooltip" data-original-title="Nombre de commentaires sur cette mission"><a href="#comment" >{$commentcount}</a></div>
			</div>
		</div>
	</section>
	<!-- end, summary --> 

	<div class="row-fluid"> 
		{if $aoparticipation[0].premium_option=="0"}
		<div class="statusbar clearfix">
			<div class="btn-toolbar">
				<div class="btn-group">
					{if $aoparticipation[0].created_by=="FO"}
						<a class="btn btn-small" href="/client/quotes-1?article={$smarty.get.id}"><i class="icon-pencil"></i> Relancer un devis</a>
					{/if}
					{if $aoparticipation[0].articlestatus!="closed_client"}
						<a class="btn btn-small" href="/client/compose-mail?serviceid=111201092609847&object={$aoparticipation[0].title}><i class="icon-envelope"></i> Contacter Edit-place</a>
						<a class="btn btn-small" href="javascript:void(0);" onClick="CloseArticle('{$smarty.get.id}');" target="_blank"><i class="icon-remove"></i> Annuler cette mission</a>
					{/if}
				</div>
			</div>
		</div>
		{/if}
		<div class="row-fluid"> 
			<div class="span9">
			<section id="purchase">
				<div class="row-fluid">
					<div class="span12">
						<h3>R&egrave;glement du d&eacute;pôt de garantie</h3>
						<p>Edit-place garde en dépôt de garantie le montant demandé par le journaliste jusqu’à validation des articles par le client. edit-place vous rembourse la somme en cas de refus définitif de la commande.*</p>
					</div>
				</div>
				<div class="row-fluid">
					<br>
					<table class="table table-bordered table-hover span8 offset2">
						<thead>
							<tr>
								<th colspan=3><h4>Commande</h4></th>
							</tr>
						</thead>
						<tr><td colspan=3 class="span6">{$aoparticipation[0].title}</td></tr>
						<tr><td class="span6"></td><td class="span3 price">Prix HT</td><td class="span3 price">{$aoparticipation[0].price_user_total|ceil} &euro;</td></tr>
						{if $aoparticipation[0].client_type!="personal"}
						<tr>
							<td class="span6"></td>
							<td class="span3 price">TVA inclus</td>
							<td class="span3 price">{$tax|zero_cut:2} &euro;</td>
						</tr>
						{/if}
						{math assign="total" equation='x+y' x=$aoparticipation[0].price_user_total|ceil y=$tax"} 
						<tr class="info">
							<td class="span6"></td>
							<td class="span3 price totalprice">Total &agrave; r&eacute;gler</td>
							<td class="span3 price totalprice">{$total|zero_cut:2} &euro; ttc</td> 
						</tr>
					</table>

					<form method="POST" name="payform">
						<div class="span8 offset2">
							<div class="pull-center">
								{if $aoparticipation[0].articlestatus!="closed_client"}
								<hr>
								<h4>S&eacute;lectionnez un mode de paiement</h4>
									{if $first_name==""}
										<div class="btn btn-large" data-target="#profile-update" data-toggle="modal">Paypal</div>
										<div class="btn btn-large" data-target="#profile-update" data-toggle="modal">CB</div>
									{else} 
										<div class="btn btn-large" onClick="payformsubmit('PP');">Paypal</div>
										<div class="btn btn-large" onClick="payformsubmit('CC');">CB</div>
									{/if}
								{/if}
							</div>
						</div>
						<input type="hidden" name="delivery" id="delivery" value="{$smarty.get.id}" />
						<input type="hidden" name="article" id="article" value="{$aoparticipation[0].article_id}" />
						<input type="hidden" name="amount_topay" id="amount_topay" value="{$total}" />
						<input type="hidden" name="amount" id="amount" value="{$aoparticipation[0].price_user_total|ceil}" />
					</form>
				</div>
			</section>
		</div>
		<div class="span3">
			<!--  right column  -->
			<aside>
				<div class="aside-bg">
					{if $aoparticipation[0].premium_option=="0"}
						<div class="editor-price">
							<p class="quote-price">Prix total :<strong> {$aoparticipation[0].price_user_total|ceil} &euro;</strong></p>
							<ul class="unstyled stripe">
								<li>Tarif contributeur : {$aoparticipation[0].price_user|zero_cut:2} &euro;</li>
								<li>Commission Edit-place incluse : {$aoparticipation[0].ep_percent|zero_cut:2}%</li>
							</ul>
						</div> 
					{/if}
					<div id="selected-editor" class="aside-block">
						<div class="editor-container">
							<h4>Votre contact</h4>
							<a class="imgframe-large" onclick="loadcontribprofile('{$contact[0].identifier}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">
							<img src="{$contact[0].profilepic}" alt="{$contact[0].name}"></a>
							<p class="editor-name"><a onclick="loadcontribprofile('{$contact[0].identifier}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">{$contact[0].name}</a></p>
							<a href="/client/compose-mail?clientid={$contact[0].identifier}&ord=y1s" class="btn btn-small">contacter {$contact[0].first_name|ucfirst}</a>
							<address>
								<i class="icon-phone"></i> +{$contact[0].phone_number}<br>
								<a href="mailto:{$contact[0].email}"><i class="icon-email"></i> {$contact[0].email}</a>
							</address>
						</div>
					</div>
					
					{if $customerstrust|@count>0}
					<div id="we-trust" class="aside-block">
						<h4>IL A DEJA TRAVAILLE POUR</h4>
						<ul class="unstyled">
							{foreach from=$customerstrust item=clogo key=ckey}
								<li><img src="{$clogo}" rel="tooltip" data-original-title="{$ckey|utf8_decode}" data-placement="left"></li>
							{/foreach}
						</ul>
					</div>
					{/if}
					
					<div class="aside-block" id="garantee">
						<h4>Vos garanties</h4>
						<dl>
							<dt><span class="umbrella"></span>Edit-place est votre m&eacute;diateur</dt>
							<dd>En cas de contestation (d&eacute;lai de livraison, reprise d’articles, remboursement...)</dd>
							<dt><span class="locked"></span>Paiement s&eacute;curis&eacute;</dt>
							<dd>Notre solution de paiement en ligne vous garantit une transaction en toute tranquillit&eacute;</dd>
						</dl>
					</div>
				</div>
			</aside>  
		</div>
		</div>
	</div>
</div>

<!-- contrib profile -->
<div id="viewContribProfile" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h3 id="myModalLabel">Profil du r&eacute;dacteur</h3>
	</div>
	<div class="modal-body">
		<div id="userprofile">
	
		</div>
	</div>
</div>

<!-- Client profile update -->
<div id="profile-update" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">COMPLETER VOTRE PROFIL</h3>
	</div>
	<div class="modal-body">
		<p>Merci de compl&eacute;ter votre profil afin de g&eacute;n&eacute;rer la facture.</p>
		<p><a href="/client/profile?from=payment&article={$smarty.get.id}">Compl&eacute;ter mon profil</a></p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
	</div>
</div>