<!DOCTYPE html>

<html lang="fr">

	<head>

		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

		<title>{$page_title}</title>

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<meta name="description" content="{$meta_desc}">

		<meta name="author" content="">
		
		  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="/script/common/html5.js"></script>
		<![endif]-->
	
		{foreach from=$cssList item=css}
			<link type="text/css" rel="stylesheet" href="/FO/css/{$css}"/>  
		{/foreach}
		
		
		<!--<link type="text/css" rel="stylesheet" href="/min/b=FO/css&f={$cssfiles|substr:-1}"/>-->
		{foreach from=$javascriptList item=jsfiles}
			<script type="text/javascript" src="/FO/script/{$jsfiles}"></script>
		{/foreach}
		
		
		

		<!--[if IE]>
		<script type="text/javascript" src="/script/common/respond.src.js"></script>
		<![endif]-->
		
		<!-- Le styles -->


	</head>



	{if $clientidentifier!=""}

	<body id="client" class="secondnav-on">

	{else}

	<body >	

	{/if}

		{foreach from=$headerList item=frame}

			{include file="$frame"}

		{/foreach}

		

		{foreach from=$mainList item=frame}

			{include file="$frame"}

		{/foreach} 	

		

		{foreach from=$footerList item=frame}

			{include file="$frame"}

		{/foreach}

	<script type="text/javascript">

		// tooltip activation

		$("[rel=tooltip]").tooltip();

		$("[rel=popover]").popover();

	</script>

	

  </body>

</html>



