<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>edit-place : {$meta_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{$livesite}/FO/script/common/html5.js"></script>
    <![endif]-->
	{assign var='cssfiles' value=''}
	{foreach from=$cssList item=css}
		{assign var='cssfiles' value=$cssfiles$css,}
	{/foreach}
<link type="text/css" rel="stylesheet" href="/min/b=FO/css&f={$cssfiles|substr:-1}"/>
	{foreach from=$javascriptList item=jsfiles}
		<script language="JavaScript" type="text/javascript" src="{$livesite}/FO/script/{$jsfiles}"></script>
	{/foreach}


</head>

 <body id="contributor" class="homepage secondnav-on">
 		<!--Header Holder-->
			{foreach from=$headerList item=frame}
				{include file="$frame"}
			{/foreach}
		<!--/Header Holder-->

		<!--Content Holder-->
				{foreach from=$mainList item=frame}
					{include file="$frame"}
				{/foreach}		
		<!--/Content Holder-->	 

		<!--Footer Holder-->
				{foreach from=$footerList item=frame}
					{include file="$frame"}
				{/foreach}
		<!-- /FooterHolder -->
   



	<!-- ***** Modal collections -->

	<!-- ajax use start -->
	<div id="viewProfile-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="myModalLabel">dedicated profile modal - ajax</h3>
			</div>
		<div class="modal-body">

		</div>

	</div>
	<!-- ajax use end -->

	<div id="login" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Connexion</h3>
		</div>
		<div class="modal-body">
		<p>To design</p>
		</div>
		<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		<button class="btn btn-primary">Save changes</button>
		</div>
	</div> 
{literal} 	
<script type="text/javascript">
	
	 $(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
		return false;		
	}); 
	
    // placeholder mgt for old browsers
	$('input, textarea').placeholder();
	
	// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();	
	
	$('a.printnow').click(function() {
		window.print();
		return false;
	});
	
	
	 $('a.backnow').click(function() {
		//window.history.back(1);
		history.go(-1);return false;
		
	});
		
	
    </script>
{/literal}
  </body>
</html>