{literal}
<style>
td{text-align:center;}
</style>
{/literal}	<form action="" method="post" enctype="mulitpart/form-data">				<input type="file" multiple="" name="files[]">		<div class="controls">			<div data-provides="fileupload" class="span12 fileupload fileupload-new">				<input type="hidden" value="" name="">				<span class="btn btn-file span4" style="margin-left:0px">					<span class="fileupload-new"><img src="/BO/theme/gebo/img/gCons/pin.png" alt="" /> Upload files</span>					<span class="fileupload-exists">Change</span>					<input type="file" name="quote_documents" id="quote_documents" class="validate[required]" />				 </span>				<span class="fileupload-preview"></span>				<a style="float: none" data-dismiss="fileupload" class="close fileupload-exists" href="#">&times;</a>				<div id="file_name"></div>										</div>		</div>	</form>			
<div class="container">
{foreach from=$req_users item=item1 name=typeusers key=key1}
	{if $smarty.foreach.typeusers.first}
	<ul class="nav nav-tabs">
	<li class="active"><a href="#{$key1|capitalize}" data-toggle="tab">{$key1|capitalize}</a></li>
	{else}
	<li><a href="#{$key1|capitalize}" data-toggle="tab">{$key1|capitalize}</a></li>
	{/if}		
	{if $smarty.foreach.typeusers.last}
	</ul>
	{/if}
{/foreach}
{foreach from=$req_users item=item1 name=typeusers key=key1}
			{if $smarty.foreach.typeusers.first}
		<div class="tab-content">
			<div class="tab-pane active" id="{$key1|capitalize}">
			{else}
			<div class="tab-pane" id="{$key1|capitalize}">
			{/if}
			<table class="table table-hover">
			<thead>
				<tr>
					<!-- <th  width="3%">Initial</th> -->
					<th>First Name</th>
					<th>Last Name</th>
					<th>Email</th>
					<th>Type</th>
					<!-- <th  width="10%">Address</th>
					<th  width="5%">City</th>
					<th  width="5%">State</th>
					<th  width="3%">Zipcode</th>
					<th  width="10%">Phone Number</th> 
					<th  width="9%">Created At</th> 
					<th  width="5%">Type</th> -->
					{if $key1=="contributor"}
					<th>Profile Type</th> 
					<th>Corrector</th> 
					<th>Corrector Type</th> 
					<th>Mother Language</th> 
					<th>Other Language</th> 
					<th>Category</th> 
					<th>Other Category</th> 
					{/if}
					<th>Status</th>
				</tr>
			</thead>
			{foreach from=$item1 item=item name=users key=key2}
			<tr>
				<!-- <td>{$item->initial|capitalize}</td> -->
				<td>{$item->first_name}</td>
				<td>{$item->last_name}</td>
				<td>{$item->email}</td>
				<td>{$item->type}</td>
				<!-- <td>{$item->address}</td>
				<td>{$item->city}</td>
				<td>{$item->state}</td>
				<td>{$item->zipcode}</td>
				<td>{$item->phone_number}</td>
				<td>{$item->created_at|date_format:"%D"}</td> 
				<td>{$item->type}</td> -->
				{if $key1=="contributor"}
				<td>{$item->profile_type}</td> 
				<td>{$item->corrector}</td> 
				<td>{$item->profile_type2}</td> 
				<td>{$item->language}</td> 
				<td>{foreach from=$item->language_more item=item2 name=languagemore key=key3}{$key3}({$item2}%)&nbsp;{/foreach}</td> 
				<td>{$item->favourite_category}</td> 
				<td>{foreach from=$item->category_more item=item3 name=catmore key=key4}{$key4}({$item3}%)&nbsp;{/foreach}</td> 
				{/if}
				<td>{$item->status}</td>
			</tr>
			<tr height=5></tr>
			{if $smarty.foreach.users.last}
			<tr height=10></tr>
			</table>
			</div>
			{/if}
			{/foreach}
			{if $smarty.foreach.typeusers.last}
		</div>
	</div>
{/if}
	{/foreach}
	</div>
	
{literal}
<script>
	    $('#myTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    })
</script>
{/literal}
{* 2.6.19 *}
{* 
	{$smarty.version} 
	{assign var=type value=array()}
	{foreach from=$users key=key item=item name=user} 
		 {if in_array($item->type, $type)}
			
			{else}
			{assign var=typecount value={$type|count}}
			{$type[$typecount]=$item->type}
		 {/if}
	{/foreach}
	{$type|print_r} *}