<header class="dashit">
    <div id="header">
		<div id="topnav">
			<div class="container">
				<div class="pull-right">    
					<span id="switch-lang" class="dropdown">
						<a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="index.html"><span class="flag flag-fr"></span> FR <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li><a href="http://ep-test.edit-palce.co.uk"><span class="flag flag-gb"></span> UK</a></li>
						</ul>
					</span>
					| 
					
					{if $usertype eq 'client'}		 
					 <a data-toggle="dropdown" class="btn btn-mini btn-login dropdown-toggle">
						<i class="icon-user icon-white"></i> {$clientname} <span class="caret"></span>
					  </a>  
					  
						<!-- Link or button to toggle dropdown -->
					  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
						<li><a tabindex="-1" href="/client/home">Mon espace client</a></li>
						<li><a tabindex="-1" href="/client/profile">G&eacute;rer mon compte</a></li>
						<li><a tabindex="-1" href="/client/billing">Mes factures</a></li>
						<li class="divider"></li>
						<li><a tabindex="-1" href="/client/inbox">Ma messagerie</a></li>
						<li><a tabindex="-1" href="/client/logout">D&eacute;connexion</a></li>
					  </ul>
					   
					{elseif $usertype eq 'contributor'}	 
						<a data-toggle="dropdown" class="btn btn-mini btn-login dropdown-toggle">
							<i class="icon-user icon-white"></i> {$client_email} <span class="caret"></span>
						</a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li><a tabindex="-1" href="/contrib/home">Mon espace</a></li>
							<li><a tabindex="-1" href="/contrib/modify-profile">Modifier mon profil</a></li>
							<li class="divider"></li>
							<li><a tabindex="-1" href="/contrib/logout"><i class="icon-remove-sign"></i> D&eacute;connexion</a></li>
						</ul>
						
					{else}
						<a href="" data-target="#create-user" data-toggle="modal"><span class="glyphicon glyphicon-pencil"></span> Contributeur</a> | 
						<a href="" data-target="#login" data-toggle="modal"><span class="glyphicon glyphicon-user"></span> Connexion</a>
					{/if}
				</div>
			</div>
		</div>
		<nav class="navbar navbar_ep" role="navigation">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/index"><img src="/FO/images/imageB3/svg/logo-ep.svg" width="201" height="34" class="img-responsive"></a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="ep-effect"><a href="/index">Accueil</a></li>
						<li class="ep-effect"><a href="/index/qui-sommes-nous">Qui sommes-nous ?</a></li>
						<li class="ep-effect"><a href="/index/nos-references">Nos références</a></li>
						<li class="ep-effect"><a href="http://www.edit-place.com/blog/">Blog</a></li>
						{if $usertype neq 'contributor'}<li><a class="navbar-btn btn btn-primary btn-sm" href="/client/quotes-1">Nos tarifs</a></li>{/if}
					</ul>
				</div>
			</div>
		</nav>
	</div>
</header>
<div id="login" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			{include file="common/login.phtml"}
		</div>
	</div>	
</div>
<div id="create-user" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		{include file="common/create_contrib.phtml"}
		</div>
	</div>	
</div>
<div id="lost-password" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h3 id="myModalLabel"><i class="icon-user"></i> Mot de passe oubli&eacute; ?</h3>
				</div>
				<div class="modal-body">
					<div class="alert alert-info" id="alert"><button type="button" class="close" data-dismiss="alert">&times;</button>Pour recevoir &agrave; nouveau votre mot de passe, veuillez saisir votre e-mail.</div>
					<div class="row">  
						<div class="col-xs-12 col-md-6">
							<input type="text" name="forgotpwdemail" id="forgotpwdemail" placeholder="Votre Email" class="form-control" />
						</div>
					</div>
					<div class="error" id="forgotpwdemailerr"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" onClick="return forgotpasswordmailindex();">Valider</button>
					<button class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button">Annuler</button>
				</div>
			</form>
		</div>
	</div>
</div>