<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>{$meta_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{$meta_desc}">
    <meta name="author" content="">

    <!-- Le styles -->

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{$livesite}/FO/script/common/html5.js"></script>
    <![endif]-->
	{assign var='cssfiles' value=''}
	{foreach from=$cssList item=css}
		{assign var='cssfiles' value=$cssfiles$css,}
	{/foreach}
<link type="text/css" rel="stylesheet" href="/min/b=FO/css&f={$cssfiles|substr:-1}"/>
	{foreach from=$javascriptList item=jsfiles}
		<script language="JavaScript" type="text/javascript" src="{$livesite}/FO/script/{$jsfiles}"></script>
	{/foreach}
{literal}
<style>
body {
text-align:justify;
}
</style>
{/literal}

</head>

  <body class="corporate">
 		<!--Header Holder-->
			{foreach from=$headerList item=frame}
				{include file="$frame"}
			{/foreach}
		<!--/Header Holder-->

		<!--Content Holder-->
				{foreach from=$mainList item=frame}
					{include file="$frame"}
				{/foreach}		
		<!--/Content Holder-->	 

		<!--Footer Holder-->
				{foreach from=$footerList item=frame}
					{include file="$frame"}
				{/foreach}
		<!-- /FooterHolder -->
<!-- ***** Modal collections -->

<!-- ajax use start -->

<div id="viewOffer-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">D&eacute;tail de l'annonce</h3>
	</div>
	<div class="modal-body">

	</div>
</div>
<!-- ajax use end --> 	
	
{literal} 	
    <script>
	
	$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});
	
	 // placeholder mgt for old browsers
    $('input, textarea').placeholder();
	
    $('#skillsTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    })
	
	$('#skillsTab a:first').tab('show');
	
	// tooltip activation
    $("[rel=tooltip]").tooltip();
	 $("[rel=popover]").popover();
	
    </script>
{/literal}
  </body>
</html>
