<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>{$meta_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{$meta_desc}">
    <meta name="author" content="">
	<link rel="shortcut icon" type="image/x-icon" href="/FO/favicon.ico" />
	{assign var='cssfiles' value=''}
	{foreach from=$cssList item=css}
		{assign var='cssfiles' value=$cssfiles$css,}
	{/foreach}
	<link type="text/css" rel="stylesheet" href="/min/b=FO/css&f={$cssfiles|substr:-1}"/>
	
	<!--[if lt IE 9]>
      <script src="{$livesite}/FO/bootstrap3/html5shiv.js"></script>
      <script src="{$livesite}/FO/bootstrap3/respond.min.js"></script>
    <![endif]-->
	
	{foreach from=$javascriptList item=jsfiles}
		<script language="JavaScript" type="text/javascript" src="{$livesite}/FO/script/{$jsfiles}"></script>
	{/foreach}
	{literal}
	<style type="text/css">
	.modal.fade.in {
		top: 0;
	}
	#callus h4
	{
	text-transform: none;
	
	}
	.dropdown-menu {top:30px; right:50px !important}  
	</style>
	{/literal}
	
</head>

  <body class="page">
 		<!--Header Holder-->
			{foreach from=$headerList item=frame}
				{include file="$frame"}
			{/foreach}
		<!--/Header Holder-->

		<!--Content Holder-->
				{foreach from=$mainList item=frame}
					{include file="$frame"}
				{/foreach}		
		<!--/Content Holder-->	 

		<!--Footer Holder-->
				{foreach from=$footerList item=frame}
					{include file="$frame"}
				{/foreach}
		<!-- /FooterHolder -->
<!-- ***** Modal collections -->

<!-- ajax use start -->

<div id="viewOffer-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">D&eacute;tail de l'annonce</h3>
	</div>
	<div class="modal-body">

	</div>
</div>
<!-- ajax use end --> 	
 </body>
</html>
