<section id="tagline"> 
 <div class="container">
   <p>R&eacute;daction, Traduction et Optimisation SEO de contenus web exclusifs</p>
 </div>
</section>
<section id="content"> 
	<div class="container">
		<div class="row-fluid">
			<div class="alert alert-error">
				<h3>Error 404</h3>
		
				<p>Oops ! La page demand&eacute;e n'existe pas</p>
				<p>Veuillez v&eacute;rifier l'URL, notamment l'orthographe et les  majuscules.</p>
				<p>Si vous rencontrez  des difficult&eacute;s &agrave; trouver une page sur Edit-place, rendez-vous sur la page  d'accueil: <a href="http://www.edit-place.com" style="text-decoration:underline">http://www.edit-place.com</a></p>
			</div>	
		</div>
	</div>
</section>